### ISSUE TITLE
Option to prevent escaping in .properties files

### ISSUE THREAD

**Issue by tanyona** [crowdin/crowdin-cli#102]
Would there be an option to prevent escaping of characters (! : = #) in the value part of a .properties file.

e.g. `help = value=1` remains that way instead of `help = value\=1`

**Comment by yuliiaR** [comment]
Hi @tanyona You're welcome to add the following parameter to your configuration file **escape_special_characters: 0**

The special characters like =, :, ! and # won't be escaped

**Comment by tanyona** [comment]
This doesn't seem to work. Values are still escaped.

**Comment by v3ctorman** [comment]
@tanyona after adding `escape_special_characters: 0` you need to run `crowdin push` (or `crowdin upload sources`) to update export options in Crowdin project (because files are generated from scratch on our backend so the escape options are applied)

After that I recommend Build project from UI. That should make it work I believe

You can also share your project id with us, so we can recheck on our side too.

**Comment by tanyona** [comment]
For some reason the project was not updating and I was getting `Warning: Export was skipped. Please note that this method can be invoked only once per 30 minutes.` even after waiting for more than 30 minutes. I made the change in the browser UI and unchecked the **Escape special characters** export option for the file and when I downloaded, it was as expected.

The project id is `artreporting`. Is there a reason I'm getting the export warning even after waiting for more than 30 minutes.

**Comment by tanyona** [comment]
I've been able to download so I'll go ahead and close this issue. The only suggestion is that the **escape_special_characters** option be included in the [configuration file documentation](https://support.crowdin.com/configuration-file/) and in the default file generated by the `crowdin generate` command.

**Comment by rohalskyy** [comment]
@tanyona The _Warning: Export was skipped_ might also appear in case there were no new translations done in your project.
Glad to hear the download worked fine for you. Will forward your suggestions to the team.
Should you have any other questions you may contact us on support@crowdin.com

**Comment by tanyona** [comment]
OK. Thanks for the help I got from everyone.
