### ISSUE TITLE
macOS/iOS. Warning: Downloaded translations do not match current project configuration

### ISSUE THREAD

**Issue by nekrich** [crowdin/crowdin-cli#105]
Hi.

I'm another one who gets `Warning: Downloaded translations do not match current project configuration` (as in #69) for my macOS/iOS project.

Crowdin CLI version is 2.0.27
Command: `crowdin download --branch my_branch --language zh-CN` (w/o language option I have same output with `en.lproj` for all locales)

```
Building ZIP archive with the latest translations for 'zh-CN' - skipped
Warning: Export was skipped. Please note that this method can be invoked only once per 30 minutes.
Extracting: '/fastlane/metadata/macOS/zh-Hans/description.txt'
Extracting: '/fastlane/metadata/macOS/zh-Hans/promotional_text.txt'
Extracting: '/fastlane/metadata/macOS/zh-Hans/release_notes.txt'
Warning: Downloaded translations do not match current project configuration. The following files will be omitted:
 - '/Dependencies/Localizations/Resources/Localizations/Strings/en.lproj/Authorization.strings'
...
```

crowdin.yml
```
"preserve_hierarchy": true

files: [
 
 # Fails
 { 
  "source" : "Dependencies/Localizations/Resources/Localizations/Strings/en.lproj/*.strings",
  "translation" : "Dependencies/Localizations/Resources/Localizations/Strings/%osx_locale%.lproj/%original_file_name%",
  "escape_quotes" : 2,
  "languages_mapping" : {
   "osx_locale": {
    "zh-CN" : "zh-Hans",
   },
  },
 },
 
 # Works
 { 
  "source" : "fastlane/metadata/macOS/default/**/*.txt",
  "translation" : "fastlane/metadata/macOS/%locale%/**/%original_file_name%",
  "ignore" : [ # translate only description, promotional_text & release_notes
    "/**/keywords.txt",
    "/**/name.txt",
    "/**/subtitle.txt",
    "/**/marketing_url.txt",
    "/**/privacy_url.txt",
    "/**/support_url.txt",
  ],
  "escape_quotes" : 0,
  "languages_mapping" : {
   "locale": {
    "zh-CN" : "zh-Hans",
   },
  },
 },
]
```

When I build & DL .zip from the website I have such structure:
```
my_branch
  - fastlane
    - metadata
      - macOS
        - [locales] 🆗 
zh-CN ❓ 
  - my_branch
    - Dependencies
      - Localizations
        - Resources
          - Localizations
            - Strings
              - en.lproj ⚠️ 
```

Tried `locale` for `languages_mapping` - doesn't work either.
So I don't know who doesn' treat the `en.lproj` folder correctly: web or CLI.

**UPD**.
Looks like the problem is with `crowdin upload --branch`.
On the web in the folder properties `Resulting file name when exported:` is `en.lproj` but `%osx_locale%.lproj` is expected. When I change manually it on the web `crowdin download -- branch ` succeeds.

Tried: to use `..../en.lproj/**/*.strings` in the `source` pattern. `Resulting file name when exported:` is still `en.lproj`

**Comment by ira-sem** [comment]
@nekrich 

Hi! Could you, please tell us the project name where the issue occurs?

Thanks!

**Comment by Andrulko** [comment]
Thanks a lot for a detailed clarification!

The reason is missing slash in the beginning of `source` and `translation` keys. For example:

```
  "source" : "/Dependencies/Localizations/Resources/Localizations/Strings/en.lproj/*.strings",
  "translation" : "/Dependencies/Localizations/Resources/Localizations/Strings/%osx_locale%.lproj/%original_file_name%",
```

Afterward, run `crowdin push` -> build the project via UI and try `crowdin pull` to download translations

Also, there is no need to define `languages_mapping` if you use *osx_locale* pattern, we will export Chinese Simplified as `zh-Hans` in any case ;)

**Comment by nekrich** [comment]
Slash saved my day!

Thank you for the quick response.
