### ISSUE TITLE
"UnsupportedOperationException" during upload Android file

### ISSUE THREAD

**Issue by anis-campos** [crowdin/crowdin-cli#109]
Environment
-------------

-- Java -- :
openjdk 12 2019-03-19
OpenJDK Runtime Environment (build 12+33)
OpenJDK 64-Bit Server VM (build 12+33, mixed mode, sharing)

-- OS -- : 
System Version: macOS 10.14.3 (18D109)
Kernel Version: Darwin 18.2.0

-- CLI -- :
crowdin: stable 2.0.28

Reproduce 
--------------
 ```
$ crowdin upload sources --config crowdin.yml 
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.crowdin.cli.commands.Commands.initCli(Commands.java:858)
        at com.crowdin.cli.commands.Commands.initialize(Commands.java:128)
        at com.crowdin.cli.commands.Commands.run(Commands.java:232)
        at com.crowdin.cli.Cli.main(Cli.java:17)
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
        at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:555)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:580)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:567)
        at com.crowdin.client.CrowdinApiClientImpl.<clinit>(CrowdinApiClientImpl.java:22)
        ... 4 more
```

Update
----------

It's seems to be issue of compatibility with my java version. I got it working with 
```
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```
As I prefer to use the latest SDK system wide, i'm using [jenv](http://www.jenv.be/) to set the java version inside the folder where I use crowdin.

**Comment by anis-campos** [comment]
Could it be related to the log4j update on  https://github.com/crowdin/crowdin-cli-2/pull/106/commits/423c2301a1e070694cbda473105210a78a76362f ?  it's the change of v.2.0.28. To confirm I will try to go back t v2.0.27.

UPDATE
---------
It works with v2.0.27 and jdk 12. The issue is indeed related to release 2.0.28

**Comment by rohalskyy** [comment]
Hi there @anis-campos !
Our developers are aware of this kind of issue and already working to fix it in the nearest!
Really glad to hear that you've found a workaround for the time being.
We'll let you know as soon as everything is ready.

**Comment by rohalskyy** [comment]
Hi @anis-campos !
We've released a new version (2.0.29) of our CLI tool. Now it should work just fine with the latest Java. Kindly try to update CLI on your end and let me know whether it works fine now

**Comment by anis-campos** [comment]
Hi @rohalskyy 

Thanks for the work. Here what the result of my testing

Test protocole
===
- set java version with ```jenv global java_version_here``` 
- call ```java -jar crowdin-cli.jar upload``` for each release

Results
===
**v2.0.29**
###
- [X] java 1.8.0_202 ( java for mac)
- [X] java 11.0.2+9 (openjdk)
- [X] java 12+33 (openjdk)

**v2.0.28**
###
- [X] java 1.8.0_202 ( java for mac)
- [ ] java 11.0.2+9 (openjdk)
- [ ] java 12+33 (openjdk)

**v2.0.27**
###
- [X] java 1.8.0_202 ( java for mac)
- [X] java 11.0.2+9 (openjdk)
- [X] java 12+33 (openjdk)

Everything looks fine. Thanks a lot !

**Comment by rohalskyy** [comment]
This is great news! Thanks for the confirmation!
