### ISSUE TITLE
Homebrew. Tap

### ISSUE THREAD

**Issue by nekrich** [crowdin/crowdin-cli#111]
Hi.

Thanks for the quick fix of the #109 
But we had to manually override files on our CI cause [a brew formula](https://github.com/Homebrew/homebrew-core/pull/38786) is not updated yet. 

Did you ever consider a [standalone tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) (`homebrew-crowdin-cli` repo or `formula.rb` in the current one) for Homebrew installs to deliver updates faster & w/o waiting for the 3rd party PR review?

Thank you.

**Comment by yavorysynka** [comment]
Hi there! 

Will ask that our devs team - let's see whether we can speed up the process :)

**Comment by lifenautjoe** [comment]
Any updates on this?

**Comment by andrii-bodnar** [comment]
Please see the [Homebrew Crowdin repo](https://github.com/crowdin/homebrew-crowdin)
