### ISSUE TITLE
Provide version specific links to crowdin-cli

### ISSUE THREAD

**Issue by zkrzyzanowski** [crowdin/crowdin-cli#15]
We currently use the new `crowdin-cli` within a Docker container.  Since the containers are destroyed and created frequently, we download the CLI from https://crowdin.com/downloads/crowdin-cli.zip each time.

If a new version is released, we're forced onto it when we create a new crowdin container. 

It would be helpful to be able to download a specific version for our containers, for example:
https://crowdin.com/downloads/crowdin-cli-2.0.5.zip

**Comment by ihor-popyk** [comment]
@zkrzyzanowski thanks for the idea. We did it already.
[The newest version currently (2.0.7)](https://crowdin.com/downloads/crowdin-cli.zip)
[CLI 2.06](https://crowdin.com/downloads/crowdin-cli-2.0.6.zip)
[CLI 2.05](https://crowdin.com/downloads/crowdin-cli-2.0.5.zip)
[CLI 2.04](https://crowdin.com/downloads/crowdin-cli-2.0.4.zip)
[CLI 2.03](https://crowdin.com/downloads/crowdin-cli-2.0.3.zip)
[CLI 2.02](https://crowdin.com/downloads/crowdin-cli-2.0.2.zip)

**Comment by MarkTiedemann** [comment]
@ihor-popyk These download links no longer work.

```
$ curl -I https://crowdin.com/downloads/crowdin-cli-2.0.6.zip
HTTP/2 404
...

$ curl -I https://crowdin.com/downloads/crowdin-cli-2.0.31.zip
HTTP/2 404
...
```

**Comment by MarkTiedemann** [comment]
The links are now `https://downloads.crowdin.com/cli/v2/crowdin-cli-$version.zip`, e.g. [https://downloads.crowdin.com/cli/v2/crowdin-cli-2.0.31.zip](https://downloads.crowdin.com/cli/v2/crowdin-cli-2.0.31.zip).

**Comment by Andrulko** [comment]
@MarkTiedemann You are right, this link downloads the latest version:
https://downloads.crowdin.com/cli/v2/crowdin-cli.zip

To download the previous version (2.0.3.1 is the latest one atm):
https://downloads.crowdin.com/cli/v2/crowdin-cli-2.0.30.zip

CLI docs:
https://support.crowdin.com/cli-tool/
