### ISSUE TITLE
Option to not change `PO-Revision-Date` when file hasn't changed

### ISSUE THREAD

**Issue by Jackenmen** [crowdin/crowdin-cli#183]
It would be great to be able to disable changing `PO-Revision-Date` for files that haven't been changed, otherwise each translation update causes all po files to be updated which results in a lot of big commits when you update po files often.

This example commit that has 792 files changed could be reduced to 41 files simply by only editing `PO-Revision-Date` in po files that actually have been changed:
https://github.com/Cog-Creators/Red-DiscordBot/commit/0913b68a1ed38bb5fa909c6224a73f7daed58087

**Comment by Andrulko** [comment]
Hey @jack1142, sorry it is more about Crowdin since CLI only downloads files generated by the system and you cannot impact on exporter by CLI.

We have just tuned parser for your project, can you please try downloading translations now?

**Comment by Jackenmen** [comment]
Hi @Andrulko, it seems that it works a lot better for us now. Any chance that this parser option could be added to project settings on Crowdin in the future? This probably isn't the right place to ask about it, but I'm not sure where the right place is.

**Comment by MarynaAndriichuk** [comment]
Hello Jack! These settings are bit technically advanced, so they can be enabled on our side only. In case you'd need to disable this option or enable for any other project, feel free to hit us at support@crowdin.com

**Comment by taozhou-glean** [comment]
just to confirm that we still need to contact [support@crowdin.com](mailto:support@crowdin.com) to enable this as of now ?

**Comment by Andrulko** [comment]
Do you have any new project to which customization should be connected? Now it's possible for users to customize exported content, but that would require developing an app on your side:
https://developer.crowdin.com/crowdin-apps-module-file-pre-export-processing/

We have existing solution that can be activated on our side, so we will reach you back via email ;)

**Comment by taozhou-glean** [comment]
> 

ya https://crowdin.com/project/glean-messages is the project ;) we have our own automated process to sync the messages and having PRs with just data changes every time is a bit inconvenient, looking forward to your email then!

**Comment by Andrulko** [comment]
Done 👌 Please re-download translations now

**Comment by taozhou-glean** [comment]
oh, Thanks!

so we cleared `PO-Revision-Date` (and `X-Crowdin-File` is that expected ?), hmm that works, tho I am wondering if it's possible to keep that field, but just update the date value if has message changs ?

**Comment by Andrulko** [comment]
It appears that yes and we can't modify it easily because it will have impact on other projects 😬 Is it critical to keep `X-Crowdin-File` for you?

**Comment by taozhou-glean** [comment]
not really, I think this works for us just fine ;) Thanks!
