### ISSUE TITLE
Mapping android_code

### ISSUE THREAD

**Issue by dvasko** [crowdin/crowdin-cli#20]
let say i have this mapping
```
"files": [
  {
    "source": "/modules/common/src/main/res/values/strings.xml",
    "translation": "/modules/common/src/main/res/values-%android_code%/%original_file_name%",
    "languages_mapping": {
      "android_code": {
        "az": "az",
        "es-ES": "es",
        "zh-CN": "zh-rCN",
      }
    }
  }
]
```
CROWDIN v1
command: crowdin-cli list translations
gives output:
/modules/common/src/main/res/values-az/strings.xml
/modules/common/src/main/res/values-es/strings.xml
/modules/common/src/main/res/values-zh-rCN/strings.xml

CROWDIN v2
command: crowdin list translations
gives output:
/modules/common/src/main/res/values-az-rAZ/strings.xml
/modules/common/src/main/res/values-es/strings.xml
/modules/common/src/main/res/values-zh-rCN/strings.xml

v1 had correct behaviour, is this bug or is there any way v2 give same output as v1

**Comment by ihor-popyk** [comment]
Hello @dvasko 
I already fixed it. Please, try new version (2.0.9 https://crowdin.com/downloads/crowdin-cli.zip). 
Please notify me is everything are good for you.

**Comment by dvasko** [comment]
Works
