### ISSUE TITLE
Apostrophe not processeded by \ on Android

### ISSUE THREAD

**Issue by iandreyshev** [crowdin/crowdin-cli#216]
When I download translations with string contains apostrophe ('), Android lint show warning in string.xml

<string name="points_owned_title">You\'ve earned: {count}</string>

![image](https://user-images.githubusercontent.com/22149746/76314313-9aa9ad00-62e7-11ea-87f5-1a6d58244ff1.png)

Is this possible to put apostrophe automaticaly when I download translations?

**Comment by Andrulko** [comment]
Apostrophe should be either escaped (`\'`) or string should be surrounded with double quotes. Crowdin should escape quotes automatically on export, by the way. Checking why it did not happen but cannot reproduce in the test project. This translation:
Mike's apple

is exported the following way in Android XML:
```<string name="save_as">Mike\'s apple</string>```

If you surround the source text with double quotes inside XML and update file in Crowdin, translated files will also contain double quotes for the same string and you should not experience any lint errors. This is valid too:
```<string name="save_as">"Mike's apple"</string>```

**Comment by iandreyshev** [comment]
@Andrulko 
Can you test strings with CDATA and HTML?

Example:
`<![CDATA[Akkauntingiz iSpring Learn-da ro'yxatdan o'tkazilganda, URL havolani olasiz va u orqali akkauntingizga kirasiz.<br><br>]]>`

**Comment by andrii-bodnar** [comment]
@iandreyshev, are you still having issues exporting Android XML files? Probably this issue is not related directly to CLI

**Comment by Andrulko** [comment]
@iandreyshev Just activated some tweaks on our side for your project, now quotes in CDATA strings should be escaped as well
