### ISSUE TITLE
ClassCastException when downloading the project translations

### ISSUE THREAD

**Issue by kingiw** [crowdin/crowdin-cli#257]
**Describe the bug**
When I try to call `crowdin download --config crowdin.yaml`, the following exception occurs:
```bash
» crowdin download  --config crowdin.yaml
❌ Fetching project info     
❌ Failed to collect project info. Please contact our support team for help
❌ Unhandled Exception: java.lang.ClassCastException: class com.crowdin.client.projectsgroups.model.Project cannot be cast to class com.crowdin.client.projectsgroups.model.ProjectSettings (com.crowdin.client.projectsgroups.model.Project and com.crowdin.client.projectsgroups.model.ProjectSettings are in unnamed module of loader 'app')
```

**To Reproduce**
1. Configuration file:
```yaml
"project_id": "a_project_id"
"api_token": "my_personla_api_token"
"base_path": "."
"preserve_hierarchy": true
files: [
  {
    "source": "*",
    "translation": "/resources/%locale%/%original_file_name%'",
  }
]
```
2. Execute CLI command: `crowdin download --config crowdin.yaml`

**Expected behavior**
Download the target translation projects as expected.

**Environment:**
OS: macOS Catalina 10.15.4
Java:
```
» java -version                                         
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
```
Crowdin version: 3.1.13

**Comment by MarynaAndriichuk** [comment]
Hello! Let us pass it to the team for investigation

**Comment by andrii-bodnar** [comment]
PR #258

**Comment by kingiw** [comment]
I fetched and built the project from the #258 and the mentioned error was gone! Great job!

However, I ran into another issue, which shows
```
> crowdin download --config crowdin.yaml
✔️  Fetching project info     
✔️  Building ZIP archive with the latest translations
❌ Building translation     
❌ Failed to build translation. Please contact our support team for help
❌ 403: Forbidden
```
This may be related to another issues.

**Comment by BozhenaDobrovolska** [comment]
Hello! We're investigating  the behaviour and will get back to you soon

Sorry for the inconvenience!

**Comment by andrii-bodnar** [comment]
Hi, @kingiw !
You need to have manager access in the project to perform this action. 
403: Forbidden - is a permissions error.
