### ISSUE TITLE
install-crowdin-cli.sh compares versions incorrectly, thinks java version 1.14 is older than version 1.8

### ISSUE THREAD

**Issue by mortie** [crowdin/crowdin-cli#260]
**Describe the bug**
The way the `install-crowdin-cli.sh` script verifies your java version is:

``` bash
if [[ "$version" > "1.8" ]]
    # OK
else
    # Error
fi
```

This doesn't work, because although Java version 1.14 is newer than Java version 1.8, the `>` operator compares the strings "1.14" and "1.8" lexicographically. The correct way would be to split the strings by the dot, then compare the first parts and the second parts numerically.

**To Reproduce**
1. Have Java version >=1.10 installed.
2. Run `bash scripts/install-crowdin-cli.sh`.
3. See an error like: `Your Java version is 14.0.1 - needs to be updated. You can download it from https://www.java.com/`

**Expected behavior**
Java versions >=1.10 should be considered to be >=1.8.

**Environment:**
 - OS: Ubuntu
 - Version 20.04

**Comment by andrii-bodnar** [comment]
Hi @mortie , thank you for the suggestion!

Could you please try [this](https://github.com/crowdin/crowdin-cli/pull/261/files) fix?

**Comment by mortie** [comment]
I don't think that would work, [GNU's bash conditional constructs documentation](https://www.gnu.org/software/bash/manual/html_node/Conditional-Constructs.html#index-_005b_005b) says that "when used with [[, the ‘<’ and ‘>’ operators sort lexicographically using the current locale", so `[[ 14 > 7 ]]` is still false because 14 comes before 7 lexicographically.

Replacing `[[...]]` with `((...))` should work though, because `((...))` evaluates the expression arithmetically. `if (( "$version" > 7 )); then` should be fine.

**Comment by andrii-bodnar** [comment]
@mortie, just updated the script in PR, could you check with your Java version?

**Comment by mortie** [comment]
Yeah, that looks good :)

You're probably aware already, but I want to point out that there's some behavior change between the old code and the new:
* The old code looked like it intended to only accept java versions 1.9 and up (I accidentally used `>=1.8` one place in my bug report, but the code used `> "1.8"`). The new code accepts java versions 1.8 and up
* The new code would technically accept java version 0.9. This is probably a complete non-issue considering the context.

**Comment by andrii-bodnar** [comment]
- CLI supports Java 1.8 and up, so it's ok. If the old code was intended to only accept Java 1.9 - it was a bug :) 
- we may miss this due to a very low probability of such.
