### ISSUE TITLE
Support documentation not up to date

### ISSUE THREAD

**Issue by Mycose** [crowdin/crowdin-cli#285]
Don't know if I should post this here or not but I noticed it while fixing my scripts not working anymore when I updated to Crowdin 3.x 

**Describe the bug**
Documentation online for upload translations is not up to date
https://support.crowdin.com/configuration-file-v2/

**To Reproduce**
````
Translations Upload
The command upload translations uploads existing translations to Crowdin. If no options specified, uploaded translations will not be imported even if they are duplicated or if they are equal with the source strings, and will not be approved.

The values are:

-l, –language=language_code - defines the language translations that should be uploaded to Crowdin. By default, translations are uploaded to all project’s target languages. (Crowdin Language Codes)
–[no-]import-duplicates - defines whether to add translation if there is the same translation already existing in Crowdin project
–[no-]import-eq-suggestions - defines whether to add translation if it is equal to source string in Crowdin project
–[no-]auto-approve-imported - automatically approves uploaded translations
````

And doing `crowdin upload help` show:
`--[no-]auto-approve-imported
                          Approve added translations automatically
  --[no-]import-eq-suggestions
                          Add translations even if they're the same as the`

**Expected behavior**
The online documentation options should have -- and not - 

**Environment:**
 - OS: Mac
 - Version 10.15

**Screenshots**

**Additional context**

**Comment by og-fox** [comment]
Hi @Mycose! Please, accept our sincerest apologies for any inconveniences with CLI you experienced!

I will ask the team to update documentation, so the information will be relevant. Are there any other challenges you experience after switching to the newer version?

**Comment by Mycose** [comment]
No other inconveniences for the moment.
Thanks for the reactivity :)

**Comment by og-fox** [comment]
@Mycose always our pleasure 🚀

**Comment by andrii-bodnar** [comment]
Hi @Mycose! 

The documentation is already [up to date](https://support.crowdin.com/configuration-file/#translations-upload). Thanks again for pointing out!
