### ISSUE TITLE
Catch relative path errors with `crowdin lint`

### ISSUE THREAD

**Issue by infotexture** [crowdin/crowdin-cli#291]
According to the [Usage](https://support.crowdin.com/cli-tool/#usage) docs, the `crowdin lint` command is designed to check the configuration file for mistakes, but I've found one it misses.

I tried to add a relative path with `../` uplevel syntax to point the `translation` key to a folder one level up from the configuration file location:

```yaml
  "translation" : "../some/other/folder/locales/%two_letters_code%/%original_file_name%",
```

Even with this syntax, the `crowdin lint` command says:

     Your configuration file looks good

— but when I try to upload source files with `crowdin upload sources`, the process fails with a cryptic error that doesn't mention the `translation` key at all:

```bash
$ crowdin upload sources
✔️  Fetching project info     
✔️  Directory 'src'
✔️  Directory 'src/locales'
✔️  Directory 'src/locales/en'
❌ File 'src/locales/en/strings.json'
❌ exportOptions: optionsValidationInvalid: Invalid options given : 
   [exportPattern][exportPattern - File name can't contain any of the following characters: \ / : * ? " < > |]
```

When I removed the `../` uplevel syntax from the `translation` key as instructed by your support team, the `upload` command completed successfully.

It would be nice if the `crowdin lint` command could be extended with a check to catch this error and provide a helpful error message to help users diagnose the problem.

**Comment by Yuliya-Crowdinteam** [comment]
Thank you for bringing this information to our attention!
