### ISSUE TITLE
*Not* a real bug report

### ISSUE THREAD

**Issue by wartomato** [crowdin/crowdin-cli#292]
Hello,

while trying out the CLIv3 on my Android Project, I found something that might be a minor issue.
It is a confusing help text in the download options.

- crowdin option for downloading: --skip-untranslated-files
- string: crowdin.download.skipUntranslatedFiles
- string description provided: "Omit downloading not fully downloaded files"
- source-link: https://github.com/crowdin/crowdin-cli/blob/cli3/src/main/resources/messages/messages.properties#L36

The help text / description is confusing, as it currently states that _"not fully downloaded" files will not be downloaded_.
Is this intended? - Because i thought the option's purpose was to skip files during download that do not contain translated strings (=empty files)

Thank you.

**Comment by og-fox** [comment]
Hi @wartomato! 

It looks confusing indeed. We will look into it with the team and surely we will come up with more detailed and less confusing message :)

Thanks a million for pointing that out to us!

**Comment by andrii-bodnar** [comment]
Hi @wartomato!
Thanks for pointing out, fixed - https://github.com/crowdin/crowdin-cli/commit/66380a82f01b7d616b4ef5903ae3cc4c99140813. Will be available in the nearest update.

**Comment by wartomato** [comment]
Thank you! So, i guess, this Issue can be closed then.
