### ISSUE TITLE
Language variation not downloaded

### ISSUE THREAD

**Issue by paulofierro** [crowdin/crowdin-cli#307]
**Describe the bug**
When calling `crowdin download` I can successfully download all the translated strings files for our iOS project. However, we have translations for both `pt` 🇵🇹 and `pt-BR` 🇧🇷 and the `pt-BR` variation does not get downloaded.

**To Reproduce**
1. Configuration file: Any project that contains both `pt` and `pt-BR`
2. Execute CLI command: 'crowdin download'
3. See an error: No error, but you can see from the output that `pt-BR` is missing:

```
crowdin download
✔️  Fetching project info
✔️  Building ZIP archive with the latest translations
✔️  Building translation (100%)
✔️  Downloading translation
✔️  Extracted: 'ar.lproj/Internal.strings'
✔️  Extracted: 'de.lproj/Internal.strings'
✔️  Extracted: 'es.lproj/Internal.strings'
✔️  Extracted: 'fr.lproj/Internal.strings'
✔️  Extracted: 'it.lproj/Internal.strings'
✔️  Extracted: 'ja.lproj/Internal.strings'
✔️  Extracted: 'pl.lproj/Internal.strings'
✔️  Extracted: 'pt.lproj/Internal.strings'
✔️  Extracted: 'ru.lproj/Internal.strings'
✔️  Extracted: 'zh.lproj/Internal.strings'
```

**Expected behavior**
The tool should download `'pt-BR.lproj/Internal.strings'` as well.

**Environment:**
 - OS: macOS
 - Version 10.15.6

**Screenshots**
N/A

**Additional context**
When I download the `pt-BR` translations from the Crowdin site, the ZIP file contains a folder called `pt.lproj`, although it should be `pt-BR.lproj` so that may be related.

**Comment by denisqua** [comment]
Dear @paulofierro,

Thanks a lot for letting us know!

Our developers will definitely check it out once they come back to office 🙂

**Comment by andrii-bodnar** [comment]
Hi @paulofierro !

Could you please share your *crowdin.yml* configuration file also? (without credentials, of course)

**Comment by paulofierro** [comment]
@andrii-bodnar here you go:

```
"project_id" : "REDACTED"
"api_token" : "REDACTED"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
 {
  #
  # Source files filter
  # e.g. "/resources/en/*.json"
  #
  "source" : "/sdk/Persona/Persona/en.lproj/*.strings",

  #
  # Where translations will be placed
  # e.g. "/resources/%two_letters_code%/%original_file_name%"
  #
  "translation" : "/sdk/Persona/Persona/%two_letters_code%.lproj/%original_file_name%",
 }
]
```

**Comment by andrii-bodnar** [comment]
Hi @paulofierro !

In the *crowdin.yml* configuration file, you are using *%two_letters_code%* placeholder. For both _Portuguese_ and _Portuguese, Brazilian_ this is the same code - `pt`. During the export, _Portuguese_ translations are overriding _Portuguese, Brazilian_ translations.

I suggest you use another [placeholder](https://support.crowdin.com/configuration-file/#placeholders), for example `%locale%` which will be unique for both languages. Also, if your local language codes are different than `%locale%` code, you could use [Language Mapping](https://support.crowdin.com/configuration-file/#language-mapping)
