### ISSUE TITLE
pick Crowdin api token from the env as in CROWDIN_TOKEN and fallback to token from the config

### ISSUE THREAD

**Issue by iamstarkov** [crowdin/crowdin-cli#314]
**Is your feature request related to a problem? Please describe.**
Its a feature. among distributed teams, you want to have one config shared between teammates, but you also dont want to share personal access token. thus having a shared `crowdin.yml` in the root of the config makes sense but it doesnt make sense to keep personal tokens in it. Given this it will be nice if tokens are picked up from the environment.

**Describe the solution you'd like**
api_token is either taken from the config or if its not there taken from environment variable `CROWDIN_TOKEN`

**Comment by andrii-bodnar** [comment]
Hi @iamstarkov !

This feature already exists in CLI - [API Credentials from Environment Variables](https://support.crowdin.com/configuration-file/#api-credentials-from-environment-variables)

Did you try to use `CROWDIN_PERSONAL_TOKEN` env variable?

**Comment by kolaente** [comment]
@andrii-bodnar Is it possible to use this with project api keys instead of a personal access token?

**Comment by andrii-bodnar** [comment]
@kolaente, project API keys can't be used here. A project API key is suitable only for API v1, and CLI is based on API v2 which is using personal access tokens.

P.S. Sorry for the long response.

**Comment by kolaente** [comment]
@andrii-bodnar I see, thanks for clarifying. Will there be some way of creating a token per project? I don't feel exactly safe putting my personal access token in a ci config (use case: updating translations on every push through CI).

**Comment by andrii-bodnar** [comment]
@kolaente in the future, we are planning to add a possibility to create tokens per project, but it won't be so soon.

For now, you can create a separate user, invite this user as a manager to the needed project and use a token generated under this account.
