### ISSUE TITLE
Error code `streamIsEmpty`

### ISSUE THREAD

**Issue by achambriard** [crowdin/crowdin-cli#315]
**Describe the bug**
When I try to upload my translations with the cli command : `crowdin upload translations --auto-approve-imported --import-eq-suggestions -b xxx`. On some files, I have the following error :
```
❌ Failed to upload the translation file to the storage. Please contact our support team for help
❌ Wrong parameters:
<key: fileStream, code: streamIsEmpty, message: Stream size is null. Not empty content expected>
```
**⚠️ We have no error with crowdin version `3.2.X` but it appears with version `3.3.0`**
It may be related to this (in your changelog for version `3.3.0`) : 
`Return non-zero code when errors presented in upload command (#304)`

**To Reproduce**
1. Configuration file:
```
#
# Choose file structure in crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
 {
  "source" : "/XXX/Resources/Common/en.lproj/XXX.strings",
  "translation" : "/XXX/Resources/Common/%osx_code%/XXX.strings",
  "dest" : "/XXX/XXX.strings",
  "update_option" : "update_without_changes"
}
]
```
2. Execute CLI command: `crowdin upload translations --auto-approve-imported --import-eq-suggestions -b xxx`
3. See an error

**Expected behavior**
No error 🤷 

**Environment:**
 - OS: Mac OS Catalina
 - Version: 10.15.7 (19H2)

Thanks !

**Comment by frombetelgeuse** [comment]
Hi @achambriard!
I could reproduce your error only by trying to upload an empty file. Could you please make sure you don't have empty translation files? You can see a full list of files by using '--dryrun' argument.
And, if none of your files are empty, could you please tell me if you're using a proxy? This may lead to some hints.
I have no idea how this problem could be connected with the new version.

**Comment by Legion112** [comment]
I use proxy @frombetelgeuse could you tell me what should I do to solve this problem?

**Comment by andrii-bodnar** [comment]
Hi @Legion112!

Please check this out - https://support.crowdin.com/cli-tool/#using-crowdin-cli-with-proxy-server

**Comment by Legion112** [comment]
There is zero information about the error above and how proxy can cause it. @andrii-bodnar 
```
crowdin upload sources --config=./crowdin-articles.yml --no-progress
✔️  Fetching project info
❌ Failed to upload the '/builds/paxful/zendesk-crowdin-sync-php/storage/export_articles/360000380594/360000951173/4555682128540.html' file to the storage. Please contact our support team for help
❌ Wrong parameters: 
<key: fileStream, code: streamIsEmpty, message: Stream size is null. Not empty content expected>
✔️  File '360000380594/360000951173/360008914373.html'
✔️  File '360000380594/360000951173/360012481154.html'
✔️  File '360000380594/360000951173/360013974953.html'
✔️  File '360000409494/360002007274/360014037113.html'
✔️  File '360000829193/360001812594/360014035873.html'
✔️  File '360000829193/360001812594/360011713960.html'
✔️  File '360000829193/360001812594/360011819839.html'
✔️  File '360000829193/360001812594/360011629800.html'

❌ Current execution finished with errors
```

**Comment by andrii-bodnar** [comment]
@Legion112 your error is not related to the proxy.

Please check the `builds/paxful/zendesk-crowdin-sync-php/storage/export_articles/360000380594/360000951173/4555682128540.html` file. Probably this file is empty.

**Comment by Legion112** [comment]
@andrii-bodnar yes indeed it's empy.
