### ISSUE TITLE
crowdin init via npm doesn't show errors

### ISSUE THREAD

**Issue by L4ngu0r** [crowdin/crowdin-cli#321]
**Describe the bug**
When using command `crowdin init` and setting Project id with a string, for instance, no error is returned, the prompt is frozen.

**To Reproduce**
1. `npm i -g @crowdin/cli`
2. `crowdin init`
3. Authorize via browser
4. Set `Project Id: site`
5. Nothing happens

**Expected behavior**
An error is thrown for wrong project id.
=> tested with deb install, it does work.

**Environment:**
 - OS: Ubuntu
 - Version 18.04
 - NodeJS: 12.18.1

**Additional context**
Also notice a warning about a missing gtk package, but changes nothing after install.

**Comment by Yuliya-Crowdinteam** [comment]
Hello,

Thank you for the details provided!

We are investigating all information and will keep you updated on the matter,

**Comment by andrii-bodnar** [comment]
Hi @L4ngu0r!

This issue was fixed in the **3.5.1** version. Could you please check if everything is ok now?
