### ISSUE TITLE
Error: Calling depends_on java: "1.8+" is disabled! Use depends_on "openjdk@11", depends_on "openjdk@8" or depends_on "openjdk" instead.

### ISSUE THREAD

**Issue by romaincointepas** [crowdin/crowdin-cli#329]
**Describe the bug**
`brew upgrade crowdin@3` fails on latest macOS Big Sur.

**To Reproduce**
1. Run `brew upgrade crowdin@3` (or `brew install crowdin@3`).
2. `Error: Calling depends_on java: "1.8+" is disabled! Use depends_on "openjdk@11", depends_on "openjdk@8" or depends_on "openjdk" instead.`

**Environment:**
 - OS: macOS Big Sur
 - Version 11.0.1

**Comment by Natalia936** [comment]
We're sorry for the inconvenience, our tech guys will take a look into this

**Comment by andrii-bodnar** [comment]
Hi @romaincointepas!

Just released a new version of CLI and fixed this deprecated statement in the Formula.

Could you please check if everything is ok now?

**Comment by romaincointepas** [comment]
@andrii-bodnar Works, thanks!

**Comment by madhukarbanoth** [comment]
Invalid formula: /usr/local/Homebrew/Library/Taps/facebook/homebrew-fb/buck.rb
buck: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.

To Reproduce 
brew tap facebook/fb

**Comment by madhukarbanoth** [comment]
Hi 
Describe on bug:
brew tap facebook/fb  fails on MacBook Pro
 To reproduce:
brew tap facebook/fb 
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/facebook/homebrew-fb/buck.rb
buck: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.

**Comment by andrii-bodnar** [comment]
@madhukarbanoth, this is not related to the Crowdin CLI. This is related to [facebook/homebrew-fb](https://github.com/facebook/homebrew-fb) repository.
