### ISSUE TITLE
Configuration file is invalid

### ISSUE THREAD

**Issue by MR-Shegby** [crowdin/crowdin-cli#336]
In my project root directory I have

crowdin.yml: 
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN

.env:
CROWDIN_PROJECT_ID=111111
CROWDIN_API_TOKEN="qwer..."

when I run crowdin lint 
I get: 
Configuration file is invalid. Check the following parameters in your configuration file:
        - Required option 'api_token' is missing in the configuration file
        - Required option 'project_id' is missing in the configuration file

Crowdin CLI version - 3.5.0

**Comment by andrii-bodnar** [comment]
Hi @MR-Shegby!

Thank you for pointing this out. This is a bug in `crowdin lint` command.

Your configuration file is valid.

**Comment by MR-Shegby** [comment]
and in crowdin download command as well

**Comment by andrii-bodnar** [comment]
@MR-Shegby, we are in the process of fixing the error, 
for now, as a workaround, you can add `project_id` and `api_token` properties to your configuration file or [Split Project Configuration and API Credentials](https://support.crowdin.com/configuration-file/#split-project-configuration-and-api-credentials)

**Comment by andrii-bodnar** [comment]
Hi @MR-Shegby!

There is a version of CLI with a `.env` support, could you please check if everything is working now for you? 

Attaching a .jar file: [crowdin-cli-3.5.1.zip](https://github.com/crowdin/crowdin-cli/files/5754711/crowdin-cli-3.5.1.zip)

**Comment by MR-Shegby** [comment]
yes, everything works using this file

**Comment by OlenkaCrowdin** [comment]
@MR-Shegby happy to hear that it works!
Have a nice day😊

**Comment by MR-Shegby** [comment]
thanks

**Comment by MR-Shegby** [comment]
can you tell me please, when you're gonna publish stable version of crowdin-cli with this fix

**Comment by andrii-bodnar** [comment]
@MR-Shegby happy to hear that your issue is fixed!

We are going to release a new version of CLI on 5-6 Jan. Our QA team needs to test it more.

**Comment by andriyslyusar** [comment]
@andrii-bodnar Are you going to update `brew`, as the latest version is 3.5.0.

**Comment by andrii-bodnar** [comment]
@andriyslyusar , hmm, [Brew Formula](https://github.com/crowdin/homebrew-crowdin/blob/master/Formula/crowdin%403.rb) is already updated :thinking:

**Comment by andriyslyusar** [comment]
Both locally and GitHub Actions latst-macos env `brew install crowdin` version 3.5.0. 
![image](https://user-images.githubusercontent.com/1401690/104580858-15f19300-565e-11eb-9047-0f3f6de97be5.png)

**Comment by andrii-bodnar** [comment]
Probably you need to run `brew upgrade` to actualize all the information about Formulas

**Comment by andriyslyusar** [comment]
Sorry, you are totally right, the issue was https://github.com/Homebrew/discussions/discussions/226. I gave up to use `brew` and will use `npm` instead, on the better side it will allow version pining.

**Comment by nam-hle** [comment]
My project is suffering the same issue. Please take a look:

- [Project](https://github.com/w3f/polkadot-wiki)
- [Action](https://github.com/w3f/polkadot-wiki/runs/2877323656)

Do I need to wrap the env variable by the quote?

Thanks.

**Comment by andrii-bodnar** [comment]
Hi @nam-hle,

please try to wrap the env variables by the quotes and make sure your Action is using environment variables - https://docs.github.com/en/actions/reference/environment-variables

**Comment by nam-hle** [comment]
Many thanks. Will try.

**Comment by nam-hle** [comment]
It does not work by wrapping with quotes. https://github.com/w3f/polkadot-wiki/actions/runs/964470133

**Comment by andrii-bodnar** [comment]
@nam-hle please make sure you set `CROWDIN_DOCUSAURUS_PROJECT_ID` and `CROWDIN_DOCUSAURUS_API_KEY` environment variables

https://docs.github.com/en/actions/reference/environment-variables

**Comment by jaredmoody** [comment]
I'm experiencing this same issue on 3.10.0:

```
❯ crowdin --version
3.10.0

❯ crowdin status
❌ Configuration file is invalid. Check the following parameters in your configuration file:
	- Required option 'api_token' is missing
	- Required option 'project_id' is missing
```

```
# crowdin.yml
'project_id_env': 'CROWDIN_PROJECT_ID'
'api_token_env': 'CROWDIN_PERSONAL_TOKEN'
...
```

**Comment by andrii-bodnar** [comment]
@jaredmoody it seems like the environment variables are not set up correctly, please make sure you have the `CROWDIN_PROJECT_ID`, `CROWDIN_PERSONAL_TOKEN` env variables set

**Comment by jaredmoody** [comment]
No, the variables are there:

```
❯ [[ -v CROWDIN_PERSONAL_TOKEN ]] && echo "CROWDIN_PERSONAL_TOKEN is set"
CROWDIN_PERSONAL_TOKEN is set

❯ [[ -v CROWDIN_PROJECT_ID ]] && echo "CROWDIN_PROJECT_ID is set"
CROWDIN_PROJECT_ID is set

❯ crowdin status
❌ Configuration file is invalid. Check the following parameters in your configuration file:
	- Required option 'api_token' is missing
	- Required option 'project_id' is missing

```

**Comment by andrii-bodnar** [comment]
@jaredmoody could you please share more details about your environment? Just did a quick test and everything works as expected for me (macOS).

Another suggestion - make sure that CLI uses the correct `crowdin.yml` configuration file and that your environment variables are set with the correct values.

![env](https://user-images.githubusercontent.com/29282228/222365342-e8621647-1bbd-4818-8006-fa8d8a6c2324.png)

**Comment by jaredmoody** [comment]
This was my error/lack of understanding of env vars. I had the variables specified in a `.env.development.local` file in the format:

```
CROWDIN_PROJECT_ID=123
CROWDIN_PERSONAL_TOKEN=456
```

and then I had called `source .env.development.local`. It looked like they were available, and I could echo the variables, but they weren't available to crowdin. Adding `export` to each line in file fixed the issue.

Thanks for responding and helping!
