### ISSUE TITLE
Add an option to download only files with minimum translation percentage

### ISSUE THREAD

**Issue by erickskrauch** [crowdin/crowdin-cli#351]
**Is your feature request related to a problem? Please describe.**
There is no way to download files, that translated for at least some percentage.

**Describe the solution you'd like**
I need some option for the `download` command, that will pull only files with some translation/approve percentage.

For example:
```
crowdin pull --min-translated=80 --min-approved=20
```

**Describe alternatives you've considered**
As an alternative, I can only see a self-implementation of the downloading process through the API.

**Comment by gndzkrkc** [comment]
I think this is a must.

**Comment by KlemenDEV** [comment]
This option would be really handy

**Comment by erickskrauch** [comment]
😢

**Comment by andrii-bodnar** [comment]
@erickskrauch currently, it's not possible due to API limitations. I will reopen this issue in case this possibility appears in the API

**Comment by KlemenDEV** [comment]
Are there any plans for this? This would be super helpful for our project where some languages get forgotten with time, and then software has languages with say 1-10% of translation done. Those languages would be better to be omitted until further translated.

Is there at least some workaround possible?

**Comment by andrii-bodnar** [comment]
Hi @KlemenDEV!

Currently, there is no such option at the API level. It's possible to export all strings, only translated and only approved. From an API perspective, there is no clear vision of how this should work either. 

The main concern is caching. Any combination of export options should be cacheable, and in the case of percentage options - we'll need to cache all possible variations, which could lead to storage issues.

As a workaround, you can manually [disable some languages](https://support.crowdin.com/file-management/#file-target-languages) from being exported. There is also a [Mass File Target Languages](https://store.crowdin.com/files-target-languages) application which helps to do this for multiple files at once.

**Comment by KlemenDEV** [comment]
> As a workaround, you can manually [disable some languages](https://support.crowdin.com/file-management/#file-target-languages) from being exported.

Reading documentation, this disable disables translations, not exporting:

![image](https://github.com/user-attachments/assets/c0fbf034-fb6b-42ae-bedf-b8ac07f33839)

Our goal is right the opposite. Allow translators to translate until they reach some threshold and at that threshold, the files start pouring into the GitHub repository.

Your suggested solution will unfortunately not just discourage but prevent already low-translated languages from being translated

**Comment by andrii-bodnar** [comment]
@KlemenDEV you're right, I apologize for the misleading information.

There is another workaround. You can use the [`crowdin status translation`](https://crowdin.github.io/crowdin-cli/commands/crowdin-status-translation) command and based on the result, download only specific languages from your project by explicitly specifying the `-l` option in the [`crowdin download`](https://crowdin.github.io/crowdin-cli/commands/crowdin-download) command.

You can wrap it in the helper script:

```bash
#!/bin/bash

# Get translation status in plain format and process line by line
crowdin status translation --plain | while IFS=' ' read -r language percentage; do
    # Skip empty lines
    [ -z "$language" ] && continue
    
    # Convert percentage to integer for comparison
    percentage=${percentage:-0}  # Default to 0 if empty
    
    echo "Processing $language: $percentage%"
    
    # Check if percentage is greater than 10
    if [ "$percentage" -gt 10 ]; then
        echo "Downloading translations for $language (${percentage}%)"
        crowdin download -l "$language"
    else
        echo "Skipping $language: translation progress below threshold (${percentage}%)"
    fi
done
```

A quick test on my project shows the following output:

```console
> chmod +x ./percentage.sh && ./percentage.sh

Processing de: 0%
Skipping de: translation progress below threshold (0%)
Processing es-ES: 0%
Skipping es-ES: translation progress below threshold (0%)
Processing et: 0%
Skipping et: translation progress below threshold (0%)
Processing fr: 0%
Skipping fr: translation progress below threshold (0%)
Processing pt-BR: 0%
Skipping pt-BR: translation progress below threshold (0%)
Processing uk: 31%
Downloading translations for uk (31%)
```

As you can see, the script downloaded only Ukrainian translations, since the progress there was 31%. All other languages have been skipped.

**Comment by KlemenDEV** [comment]
Thanks for this example, I will look into it!
