### ISSUE TITLE
Crowd-In  CLI hangs when trying to report an error

### ISSUE THREAD

**Issue by allen-ziegenfus** [crowdin/crowdin-cli#364]
**Crowd-In hangs when trying to report an error**
If the crowd-in CLI cannot find translation files when trying to upload translations and encounters an error, the threads of the CLI block each other because they are all trying to print output and the CLI process hangs

**To Reproduce**
1. Start crowdin cli sync with it expecting a file say `bundle_hi_IN.properties` which does not exist
2. Crowdin CLI hangs

**Expected behavior**
Crowdin CLI exits with an error 

**Environment:**
- `python:3.7-stretch` docker image

**Additional context**
Here is a threaddump illustrating the deadlock 

[translated-threaddump.txt](https://github.com/crowdin/crowdin-cli/files/6581331/translated-threaddump.txt)

**Comment by BozhenaDobrovolska** [comment]
Hi, Allen! Thanks for pointing out
Our developers will have a look and will update you soon

**Comment by andrii-bodnar** [comment]
Hi @allen-ziegenfus,

could you please share your `crowdin.yml` configuration? (without credentials)

This should help us to reproduce this issue

**Comment by allen-ziegenfus** [comment]
hi @andrii-bodnar

here it is: https://gist.github.com/allen-ziegenfus/9371d3788f2545209f1f94613d0d87e8

**Comment by allen-ziegenfus** [comment]
i looked a little further into the heap dump of the JVM and found that multiple threads are somehow running into FileNotFound exceptions for different files - and they then seem to block each other. i'm also not sure why the files are not getting these errors as the files seem to be there on the file system

**Comment by andrii-bodnar** [comment]
Hi @allen-ziegenfus!

Three of the threads are waiting for the 4th, but this thread hung for another reason - it hung at the output of the stream stderr. Probably the CLI trying to write to the stream, but on the other hand, no one accepts it. There may be a problem with the system thread in the container reading this stderr. https://github.com/moby/moby/issues/31540 - here there was a similar problem, and the `сat /proc/1/fd/1 `helped to fix it.

Regarding FileNotFoundException - maybe the CLI does not have the necessary permissions to these files.

Is there any output from CLI? Probably there are some issues with stdout in the container.

**Comment by andrii-bodnar** [comment]
Also, please try this version of CLI with the possible fix:

[crowdin-cli-3.6.1.zip](https://github.com/crowdin/crowdin-cli/files/6622466/crowdin-cli-3.6.1.zip)

**Comment by allen-ziegenfus** [comment]
@andrii-bodnar  sorry for the radio silence - it looks like this has been cleared up now through a combination of better stderr handling / updating the cli version! thanks!

**Comment by DimaYashchyshyn-zz** [comment]
Hi @allen-ziegenfus 
Thanks for informing us 🙂
