### ISSUE TITLE
JRE exception on Apple M1 

### ISSUE THREAD

**Issue by sylvaindeloux** [crowdin/crowdin-cli#366]
**Describe the bug**
Tried to run Crowdin cli with no specific parameter nor config file.

**To Reproduce**
1. Execute CLI command: `crowdin`
2. See a Java exception:

```shell
$ crowdin

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (sharedRuntime.cpp:531), pid=22613, tid=6147
#  Error: ShouldNotReachHere()
#
# JRE version: OpenJDK Runtime Environment (16.0+14) (build 16+14)
# Java VM: OpenJDK 64-Bit Server VM (16+14, mixed mode, tiered, compressed oops, g1 gc, bsd-aarch64)
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/sylvain/hs_err_pid22613.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
```

**Environment:**
 - macOS Big Sur 11.4 up-to-date
 - Apple M1 processor

**Comment by Olena1234** [comment]
Hi there! It looks like this error indicates on some issues with your Java, we have found such information about that:
https://stackoverflow.com/questions/67684430/apple-siliconm1-11-4-get-a-java-error-jdk16
Another user have mentioned that Java had a new version today and upgrading to it have helped to resolve this issue

**Comment by sylvaindeloux** [comment]
Ok, a simple Java update solved the problem

In my case:

```shell
$ brew update openjdk
```

**Comment by nataliacrowdin** [comment]
Great to hear that. Thank you for confirmation!
