### ISSUE TITLE
Translation Status by Branch

### ISSUE THREAD

**Issue by blytheaw** [crowdin/crowdin-cli#369]
**Is your feature request related to a problem? Please describe.**
The CLI currently supports getting translation status by project/language only. I would like to be able to get the status of a particular branch in Crowdin.

**Describe the solution you'd like**
Many other commands in the CLI have a branch parameter (i.e. `-b branch-name`). The status command could follow the same pattern. The API already supports getting status by branch.

A command like this would be nice: `crowdin status translation -b branch_name`

**Describe alternatives you've considered**
The only alternative I know of would be to automate it ourselves and call the API directly. It would be wonderful to just use a single CLI command for this.

**Additional context**
My use case is we are creating a branch for every Pull Request and using machine translation to get translations for all new/updated strings in the Pull Request. I would like to be able to check and make sure that all strings on that particular branch in Crowdin have been translated.

**Comment by OlenkaCrowdin** [comment]
Thanks for the request! We'll discuss it and we'll update you once it will be possible
