### ISSUE TITLE
--plain does not provide processable output when new version is available

### ISSUE THREAD

**Issue by schnapster** [crowdin/crowdin-cli#382]
**Describe the bug**
When a new version is available, a banner gets appended to the output of commands, including one run with the `--plain` flag.

[According to the wiki and help](https://github.com/crowdin/crowdin-cli/wiki/List-project-target-languages), the `--plain` flag is supposed to "Provide plain, processable output" - the banner however is not very much processable.

**To Reproduce**
1. Use an outdated version of crowdin cli.
2. Execute CLI command: `crowdin list languages --plain`
3. Notice the version banner at the bottom

**Expected behavior**
Don't output the version banner when the `--plain` flag is provided

**Environment:**
irrelevant
 
**Screenshots**
![image](https://user-images.githubusercontent.com/6048348/126082001-aab42646-a840-43c3-ba1f-a367e946271e.png)

**Additional context**
As a workaround, one can modify the output before processing it, for example by piping it through sed replacing everything past the two newlines: `sed -z 's/\n\n.*/\n/g'`, however, the ideal situation imho would be respecting the `--plain`.

**Comment by matias904** [comment]
Ok
