### ISSUE TITLE
Missing `crowdin-cli.zip` artifact for 3.6.5 release

### ISSUE THREAD

**Issue by chenrui333** [crowdin/crowdin-cli#390]
👋 it looks like `crowdin-cli.zip` artifact is missed in the latest 3.6.5 release. Thanks!

cc @andrii-bodnar

**Comment by andrii-bodnar** [comment]
@chenrui333 thanks for pointing it out!

Just updated the release artifacts.

**Comment by chenrui333** [comment]
thanks for the quick turnaround!!
