### ISSUE TITLE
Download/Upload files concurrency

### ISSUE THREAD

**Issue by guyisra** [crowdin/crowdin-cli#395]
Our project has many files for translation and this get multiplied everytime we add a new language. 
Downloading and uploading files takes really long time (20+ minutes on fast internet connection) as it is done one file at a time without any concurrency

**Describe the solution you'd like**
Please provide some way to download/upload the files in parallel

**Comment by andrii-bodnar** [comment]
Hi @guyisra!

CLI already has a concurrency feature - for uploading sources, uploading translations, and downloading translations. It creates 4 parallel threads for these actions.
