### ISSUE TITLE
Failed to extract files. Try to run the application with admin permission

### ISSUE THREAD

**Issue by DamienCassou** [crowdin/crowdin-cli#405]
**Describe the bug**

I get this error message when trying to download translations:

> ❌ Failed to extract files. Try to run the application with admin permission

I'm not sure what this error means. The `api_token` in the configuration file usually works fine.

**To Reproduce**

```
"project_identifier" : "xxx"
"api_key" : ""
"preserve_hierarchy": true
"project_id" : "372541"
"api_token" : "xxx"

files: [
 {
  "source" : "/translations-client/en-US.json",
  "dest": /Client.json,
  "translation" : "/translations-client/%locale%.json",
  "update_option" : "update_as_unapproved"
 },
 {
  "source" : "/translations-server/Translations.en-US.resx",
  "dest": /Server.resx,
  "translation" : "/translations-server/Translations.%locale%.resx",
  "update_option" : "update_as_unapproved"
 }
]
```

```
$ crowdin --version
3.7.0
$ crowdin download -b master --language=nb
✔️  Fetching project info     
✔️  Building ZIP archive with the latest translations for 'nb'
✔️  Building translation (100%)
✔️  Downloading translation     
❌ Extracting archive     
❌ Failed to extract files. Try to run the application with admin permission
❌ Failed to extract the '/home/cassou/Documents/projects/ftgp/monitor/CrowdinTranslations_82948866561.zip' archive. Try to run the command once again
```

**Expected behavior**

I was expecting the Norwegian translations to be downloaded to the `translations-server` directory.

**Environment:**
 - OS: Fedora
 - Version 34

**Comment by DamienCassou** [comment]
I think this is due to this Crowdin setting:

![2021-10-26-161445](https://user-images.githubusercontent.com/217543/138897363-ecb848fa-0c09-40c0-b7c0-2be6e15a0bdb.png)

- setting activated with checkbox checked: the error message above appears
- setting deactivated with checkbox unchecked: seems to work fine

**Comment by ira-sem** [comment]
Hi @DamienCassou ! Yes, already had a talk with a colleague and indeed, the files for Norwegian (from master branch) weren't exported since they are not fully translated/approved and the option was enabled

**Comment by DamienCassou** [comment]
Would it be possible to improve the error message?

**Comment by ira-sem** [comment]
@DamienCassou as I was informed, this is a default message when something unexpected is happening. I've already passed this to the team so hopefully will improve the message in the future
