### ISSUE TITLE
Github Action uses a two-letter language in our `pt-BR` file.  

### ISSUE THREAD

**Issue by froger** [crowdin/crowdin-cli#408]
Hello, not sur I post the issue on the right repo, as it's about github action. Reading the code, the github action heavily uses the cli, so I am guessing it is a cli concerns more than a github action one.

**Describe the bug**
On the [decidim repository](https://github.com/decidim/decidim), the `pt-BR.yml` file have the `pt:` entry ([see file](https://github.com/decidim/decidim/blame/develop/decidim-accountability/config/locales/pt-BR.yml)). 

We have this issue for several months now, and we don't find a correct configuration for this. 

**To Reproduce**
1. Configuration file: https://github.com/decidim/decidim/blob/03800aaf58046211c05ea8facc56d756b4076525/crowdin.yaml#L39
2. Change some file in the crowdin to force update, run the github action to sync crowdin
3. `pt-BR.yml` still have `pt:` entry

**Expected behavior**
`pt-BR.yml` use `pt-BR:` entry, and `pt.yml` uses `pt:`

Related Decidim issue: https://github.com/decidim/decidim/pull/8523#issuecomment-973861497

Thanks for your support

**Comment by andrii-bodnar** [comment]
Hi @froger!
This issue is probably related to Crowdin import/export. Could you please share your Crowdin Project ID? It will be better to share this using the [contact form](https://crowdin.com/contacts) with mention of this issue. Then a customer success manager will discuss further actions with you.

**Comment by froger** [comment]
Thanks, just leaved a message in the contact form. I close the issue for now and open again if it's not a import/export issue :P

Have a great week.

**Comment by ira-sem** [comment]
Hi @froger ! Checking on our side!
