### ISSUE TITLE
Unable to use @crowdin/cli from NPM when running on a M1 computer

### ISSUE THREAD

**Issue by josh-** [crowdin/crowdin-cli#425]
**Describe the bug**
It's not possible to use the Crowdin CLI from NPM on M1 computers because `jdeploy` isn't able to install the appropriate Java runtime for the architecture.

**To Reproduce**
1. On an Apple M1 computer
2. Execute CLI command: `npx @crowdin/cli`
3. See an error

```
Need to install the following packages:
  @crowdin/cli
Ok to proceed? (y) y
Installing/Updating JRE in /Users/josh/.jdeploy...
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated node-jre@0.2.3: discontinued
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Users/josh/.jdeploy/node_modules/node-jre
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! unsupported architecture: arm64

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/josh/.npm/_logs/2022-01-16T21_44_06_851Z-debug-0.log
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
```

**Expected behavior**
The `crowdin` CLI binary to successfully install the JRE runtime for Apple M1 computers and then be successfully able to be used.

**Environment:**
 - OS: macOS
 - Version 12.1 (21C52)

**Screenshots**
N/A

**Additional context**
It appears that the CLI uses `jdeploy` to [install the appropriate JRE runtime](https://github.com/crowdin/crowdin-cli/blob/cli3/.github/workflows/publish-npm.yml#L24). I've sent a patch to jdeploy to handle this architecture: https://github.com/shannah/jdeploy/pull/21, however it appears that crowdin currently uses an old version of jdeploy so I'm not sure how easy it is to upgrade to the current one (or a fork with this patch applied)

**Comment by andrii-bodnar** [comment]
Hi @josh-!

Thanks a lot for your request, we will check the possibility to upgrade the Jdeploy version.

**Comment by josh-** [comment]
Thanks @andrii-bodnar 👍

**Comment by andrii-bodnar** [comment]
Hi @shannah!

I can see a lot of alpha versions of the jDeploy library in the NPM registry. Could you please tell me what version is safe to use that is working on the M1 chip?

**Comment by shannah** [comment]
@andrii-bodnar Version 2.0.11 will work.  You'll need to use it to repackage/republish your app after updating jdeploy on your development machine since the fix is applied at the time that your app is packaged.

Generally for versions:

1.x releases -> Used old Oracle JRE
2.x releases -> Use AdoptOpenJDK JRE
3.x releases (all alpha right now) -> Same as 2.x but will include new support for distributing desktop (GUI) apps.

**Comment by andrii-bodnar** [comment]
@shannah thanks for the response! Checked the [npm package](https://www.npmjs.com/package/jdeploy) and it seems that version 2.0.11 is missing here. Did you mean 2.0.10?

**Comment by shannah** [comment]
Sorry.  Thought it had published.  It is there now.  2.0.11

**Comment by andrii-bodnar** [comment]
@shannah great, thank you!

**Comment by andrii-bodnar** [comment]
Hi @shannah!

I have tried both 2.0.10 and 2.0.11 jDeploy versions and I am faced with the error.

After running `jdeploy install` and then some CLI command (for example, `crowdin -V`) I'm getting an error:

```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node-fetch'
Require stack:
- /Users/andrii/crowdin/crowdin-cli/jdeploy-bundle/jdeploy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at njreWrap (/Users/andrii/crowdin/crowdin-cli/jdeploy-bundle/jdeploy.js:18:19)
    at Object.<anonymous> (/Users/andrii/crowdin/crowdin-cli/jdeploy-bundle/jdeploy.js:254:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/andrii/crowdin/crowdin-cli/jdeploy-bundle/jdeploy.js' ]
}
```

Could you please help with this?

**Comment by shannah** [comment]
In your package.json, check to make sure that you have the njre dependency.    Your "dependencies" section should look like:

`"dependencies": {"shelljs": "^0.8.4", "njre": "^0.2.0"},`

**Comment by andrii-bodnar** [comment]
@shannah thanks a lot, it works now! 🎉

**Comment by andrii-bodnar** [comment]
Hi @josh-,

Fixed, will be available in the next version of CLI.

**Comment by josh-** [comment]
Amazing! Thanks so much for the quick resolution @andrii-bodnar and for your help @shannah 🙌
