### ISSUE TITLE
Option to download multiple specific languages

### ISSUE THREAD

**Issue by Epicpkmn11** [crowdin/crowdin-cli#427]
**Is your feature request related to a problem? Please describe.**
On some projects I only want to pull translations for specific languages that are a certain amount translated, but the `-l` option only allows for one language.

**Describe the solution you'd like**
- Allow specifying multiple languages to download somehow, my ideas are either a comma separated list (ex. `-l es-ES,fr,he`) or multiple `-l` options (ex. `-l es-ES -l fr -l he`)

**Describe alternatives you've considered**
- Using a script to call `crowdin pull -l $LANGUAGE` multiple times, which is what I'm [currently doing](https://github.com/DS-Homebrew/wiki/blob/main/crowdin-pull.sh)
   - This is much slower than a single call would be though since it redownloads for each language
- I suppose I could also download the zip manually and extract just what I want, that's less convenient though
- #351 would also solve this for me since that's the reason I'm filtering languages to begin with, some aren't complete enough

**Comment by andrii-bodnar** [comment]
Hi @Epicpkmn11, thanks a lot for your suggestion!

From my perspective, the best way will be to pass the `-l` parameter multiple times.

**Comment by jeromecambon** [comment]
I have the same issue: I want to download translations for specific languages only. I use the default (all languages) but then have to remove the unwanted ones.
Moreover, using the Crowdin github action, it prevents me to use the "Create pull request" feature.
