### ISSUE TITLE
[3.7.8] Not working, complains about missing Java, downgrade to 3.7.7 works

### ISSUE THREAD

**Issue by madsmadsen** [crowdin/crowdin-cli#436]
**Describe the bug**
```bash
$ crowdin download -l en-GB
Downloading java runtime environment for version 11
/bin/sh: /root/.jdeploy/jre/11/jre/jdk-11.0.14.1+1-jre/bin/java: not found
```

**To Reproduce**
Install 3.7.8 on Linux

**Expected behavior**
It just works?

**Environment:**
 - OS: Alpine Linux
 - Version: LTS

**Comment by andrii-bodnar** [comment]
@shannah is this somehow related to the jDeploy v 2.0.11 upgrade?

**Comment by shannah** [comment]
@andrii-bodnar It's possible.  Try deploying with jdeploy 3.1.5 (the latest).

**Comment by honzajerabek** [comment]
same here, unable to run at 3.7.8, downgrading to 3.7.7 fixes the issue

```
$ java -version
openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-alpine-r0)
OpenJDK 64-Bit Server VM (build 11.0.14+9-alpine-r0, mixed mode)
$ crowdin download
Downloading java runtime environment for version 11
/bin/sh: /root/.jdeploy/jre/11/jre/jdk-11.0.14.1+1-jre/bin/java: not found
```

**Comment by madsmadsen** [comment]
Any update on this?

**Comment by andrii-bodnar** [comment]
Hi @madsmadsen!

We are going to release a new version soon - #437 

In this version we have updated the jDeploy version and hope it will fix the issue

**Comment by shannah** [comment]
@andrii-bodnar Can you provide me with instructions to reproduce this issue so that I can look into it on my end?

**Comment by andrii-bodnar** [comment]
@shannah you need to install the Crowdin CLI using the command `npm i -g @crowdin/cli` and then try to run `crowdin -h`

According to the issue descriptions, the error happened when running the CLI command `crowdin download -l en-GB`, but I think the same behavior will occur for any CLI command.

And this issue is reproducible only for some cases, mostly it works good

**Comment by shannah** [comment]
@andrii-bodnar Have you tried to reproduce it in a github actions runner environment yet?

**Comment by andrii-bodnar** [comment]
@shannah I have tried only on MacOS 12.1 and Ubuntu 18.04

**Comment by shannah** [comment]
@andrii-bodnar OK.  I'll see what I can do to reproduce the issue.

**Comment by andrii-bodnar** [comment]
@shannah Thanks a lot! 

by the way, the new jDeploy site looks great 🙂

**Comment by Peanutbear** [comment]
I have encountered similar issues during concurrent execution of Crowdin Down

**Comment by jguddas** [comment]
> I have encountered similar issues during concurrent execution of Crowdin Down

I was able to reproduce this, running the CLI sequentially works, however.

**Comment by andrii-bodnar** [comment]
Hi @jguddas, this issue is quite old and already closed. If you encounter such an issue with the latest version of the CLI, please create a new one. Thank you very much!
