### ISSUE TITLE
Some format error in docs

### ISSUE THREAD

**Issue by Marvelousp4** [crowdin/crowdin-cli#441]
**Describe the bug**
The formatting is wrong in all languages except for the English document, which is correct. No matter how to edit the document in crowdin, there are still several tips colons do not match. The syntax belongs to the docusaurus platform.

**To Reproduce**
1. Configuration file: 'https://crowdin.com/project/casdoor-website/'
2. Can't edit the right colon.
![image](https://user-images.githubusercontent.com/50507788/158113543-1bf5b40b-4af5-4e50-bf28-cb3e8bac41fa.png)
3. The tips colon should have matched the red colon which I can't edit, but instead it matches the bottom colon.
4. ![1](https://user-images.githubusercontent.com/50507788/158108696-7554c04c-9713-49e4-84b4-a708f9b709a5.png)
![image](https://user-images.githubusercontent.com/50507788/158113841-d38d20ef-375e-45ca-844a-eb2a86cfc42f.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/50507788/158113055-cc182528-fc8f-4dd8-b311-e40c4c823602.png)
The colons match correctly.

**Environment:**
 - OS: windows
 - Version: windows11
 - docusaurus/core: 2.0.0-beta.7

**Additional context**
https://casdoor.org/zh/docs/how-to-connect/sdk/
https://casdoor.org/zh/docs/provider/oauth/baidu
https://casdoor.org/zh/docs/provider/saml/keycloak

**Comment by andrii-bodnar** [comment]
Hi @Marvelousp4,

Probably it's not a CLI issue but something related to the import/export process. Please [contact](https://crowdin.com/contacts) our support team for further help

Also, please provide the specific .md files where the exported version is unexpected and wrong

**Comment by andrii-bodnar** [comment]
Hi @Marvelousp4!

We made a lot of improvements in md-files import/export. Could you please check if this issue is still relevant to you?
