### ISSUE TITLE
Compatibility with fbt v1

### ISSUE THREAD

**Issue by alexandernanberg** [crowdin/crowdin-cli#443]
**Describe the bug**

Crowdin does not support the new FBT file format

**To Reproduce**

1. Clone https://github.com/facebook/fbt/tree/main/demo-app and run the build scripts 
2. Try uploading the `source_strings.json` file to Crowdin
3. See an error 
```
❌ File 'source_strings.json'
❌ Wrong parameters: 
<key: storageId, code: fileInvalid, message: Uploaded file "source_strings.json" is invalid and cannot be processed>
```

**Expected behavior**

Crowdin supports the new file format

**Environment:**
 - OS: MacOS
 - Version: 12.3.1

**Screenshots**
N/A

**Additional context**

https://github.com/facebook/fbt/blob/main/website/blog/2022-04-12-blog-post.md

**Comment by DimaYashchyshyn-zz** [comment]
Hi, @alexandernanberg I guess it's something with the file, we've checked and CLI works as expected. Any chance you can share the file sample you're using with us?

**Comment by alexandernanberg** [comment]
Here is a small sample, the biggest difference seems to be that `hashToText` was refactored into `hashToLeaf` with some additional changes

```json5
// v0.x
{
 "phrases": [
  {
   "hashToText": {
    "Qgg/fJlAlUZy7fTxo4mxeA==": "{number} days after publish",
    "ArUKBE2CUNDfqSCjistnfw==": "1 day after publish"
   },
   "filepath": "src/components/charts/LineChart.js",
   "line_beg": 168,
   "col_beg": 24,
   "line_end": 173,
   "col_end": 30,
   "desc": "Label",
   "project": "",
   "type": "table",
   "jsfbt": {
    "t": {
     "*": "{number} days after publish",
     "_1": "1 day after publish"
    },
    "m": [
     {
      "token": "number",
      "type": 2,
      "singular": true
     }
    ]
   }
  }
]
```

```json5
// v1
{
 "phrases": [
  {
   "hashToLeaf": {
    "Qgg/fJlAlUZy7fTxo4mxeA==": {
     "text": "{number} days after publish",
     "desc": "Label"
    },
    "ArUKBE2CUNDfqSCjistnfw==": {
     "text": "1 day after publish",
     "desc": "Label"
    }
   },
   "filepath": "src/components/charts/LineChart.js",
   "line_beg": 168,
   "col_beg": 24,
   "line_end": 173,
   "col_end": 30,
   "project": "",
   "jsfbt": {
    "t": {
     "*": {
      "desc": "Label",
      "text": "{number} days after publish"
     },
     "_1": {
      "desc": "Label",
      "text": "1 day after publish"
     }
    },
    "m": [
     {
      "token": "number",
      "type": 2,
      "singular": true
     }
    ]
   }
  }
]
```

**Comment by DimaYashchyshyn-zz** [comment]
@alexandernanberg thanks for sharing, we'll review it 👍

**Comment by Andrulko** [comment]
@alexandernanberg Did you specify `type: fbt` parameter in the configuration file? This configuration worked pretty well 🙏
https://github.com/Andrulko/fbt/blob/main/crowdin.yml

**Comment by alexandernanberg** [comment]
I did not! I will try that out when I get some time, thanks!

**Comment by Andrulko** [comment]
From what I've noticed, the file gets a bit different icon and strings with plurals are parsed in a specific way
![image](https://user-images.githubusercontent.com/9363547/185917474-231b60d7-0e87-4477-bdc8-c0e5089dd0d1.png)

**Comment by alexandernanberg** [comment]
I can no longer reproduce this, seems to be fixed 👍
