### ISSUE TITLE
Downloading sources doesn't work

### ISSUE THREAD

**Issue by BigBerny** [crowdin/crowdin-cli#444]
**Describe the bug**
Downloading sources doesn't work (but downloading translation does). The trans

**To Reproduce**

CLI version: 3.7.8
Configuration file:
> "project_id" : "XXXX"
> "api_token" : "XXXX"
> "base_path" : "."
> "base_url" : "https://api.crowdin.com"
> 
> "preserve_hierarchy": true
> 
> files: [
>   {
>     "source" : "src/assets/i18n/en.json",
>     "translation" : "src/assets/i18n/%two_letters_code%.json",
>     "dest" : "src/assets/i18n/en.json",
>   }
> ]

Execute CLI command:
> crowdin list sources
> ✔️  Fetching project info     
> ✔️  File 'src/assets/i18n/en.json'
> 
> crowdin download sources
> ✔️  Fetching project info     
> ⚠️  No sources found for 'src/assets/i18n/en.json' pattern. Check the source paths in your configuration file

**Expected behavior**
`crowdin download sources` should download the 'src/assets/i18n/en.json' and put it into the local folder 'src/assets/i18n'

**Environment:**
 - OS: MacOS
 - Version 12.3.1

**Additional context**
Changing the paths from 'src/...' to '/src/...' didn't help. Also I'm quite sure it worked a few versions ago.
Interestingly `crowdin download -l de` to download a translation works fine.
The folder structure should be fine (if I change it to a non-existing path, `crowdin list sources` doesn't return the file)
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/1528504/165249778-b578a2dd-5f1f-4ea4-a9ac-2d6df75708dc.png">

**Comment by andrii-bodnar** [comment]
Hi @BigBerny, could you please specify what version of Crowdin CLI you are using?

**Comment by BigBerny** [comment]
Sorry, 3.7.8

**Comment by andrii-bodnar** [comment]
@BigBerny just tried the same configuration and its working as expected:

> % crowdin push
> ✔️  Fetching project info     
> ✔️  Directory 'src'
> ✔️  Directory 'src/assets'
> ✔️  Directory 'src/assets/i18n'
> ✔️  File 'src/assets/i18n/en.json'

> % crowdin list sources
> ✔️  Fetching project info     
> ✔️  File 'src/assets/i18n/en.json'

> % crowdin download sources
> ✔️  Fetching project info     
> ✔️  File 'src/assets/i18n/en.json'

I am running the commands from the directory where my `crowdin.yml` is located:

> % ls
> crowdin.yml	src

**Comment by BigBerny** [comment]
What could it be then? I'm also running the commands where crowdin.yml and src-folder are located. My team colleague with a different machine has the same issue and it worked for both of us in the past. There were a few changes regarding the download of sources in the last few updates, so one of these broke something for us.

**Comment by BigBerny** [comment]
We didn't push the file with the CLI because we already had localizations.

**Comment by andrii-bodnar** [comment]
@BigBerny could you please check the `Resulting file after translations export` in your Crowdin file settings?

**Comment by BigBerny** [comment]
> @BigBerny could you please check the `Resulting file after translations export` in your Crowdin file settings?

<img width="714" alt="image" src="https://user-images.githubusercontent.com/1528504/165273323-2b3579bd-c55f-4389-bd5d-34af885eb344.png">

Do I have to change that?

**Comment by andrii-bodnar** [comment]
@BigBerny please change it to `/src/assets/i18n/%two_letters_code%.json`

For CLI this export pattern should be the same as the `translation` pattern in the `crowdin.yml` configuration file. CLI passing it during the sources upload, but in case of files were uploaded in a different way, it should be specified manually.

It might affect some existing integrations because files structure will change in an exported archive with translations.

**Comment by BigBerny** [comment]
@andrii-bodnar Thanks, that worked fine.

To be honest it's not clear that this pattern has to be the same when reading the Docs or the error message. You would think that when using the CLI the crowdin.yml specifications are used.

**Comment by andrii-bodnar** [comment]
@BigBerny, great. We will definitely add this to the documentation or CLI Wiki.

**Comment by andrii-bodnar** [comment]
https://github.com/crowdin/crowdin-cli/wiki/FAQ
