### ISSUE TITLE
Not possible to call croQL via CLI (double quotes)

### ISSUE THREAD

**Issue by beshur** [crowdin/crowdin-cli#450]
**Describe the bug**
Not possible to call croQL via CLI.
Originally reported in https://github.com/crowdin/crowdin-cli/discussions/449

**To Reproduce**
```
% crowdin string list --croql='identifier="apply"'   
✔️  Fetching project info     
❌ Wrong parameters: 
<key: croql, code: croqlInvalidLogic, message: Invalid logic in CroQL. Identifier 'apply' is undefined>
```
**Expected behavior**
Get a proper response

**Environment:**
 - OS: MacOS
 - Version 12.1
 - crowdin -V 3.7.8

**Comment by andrii-bodnar** [comment]
Hi @beshur!

Checked more deeply about this issue and found that there is a requirement to escape double quotes in query (otherwise Java UrlEncoder will drop these quotes from a query).

Please try the following command:

```
crowdin string list --croql='identifier=\"apply\"'
```

**Comment by beshur** [comment]
Thank you!
Seems it works, though we moved to the javascript lib at this point.
