### ISSUE TITLE
Android: Couldn't find any file to download

### ISSUE THREAD

**Issue by Afolayan** [crowdin/crowdin-cli#451]
**Describe the bug**
I tried setting up Crowdin CLI for an android project. I came up with a configuration file shown below to download translation files.

**To Reproduce**
1. Configuration file: '...'
```
"base_path" : "."
"base_url" : "https://api.crowdin.com"

"preserve_hierarchy": true

files: [
 {
 "source" : "/values/*.*",
 "translation" : "/values-%android_code%/%original_file_name%",
 "translation_replace": {
      "pt_BR": "pt",
  },
 }
]
```
2. Execute CLI command: 
```
crowdin list sources
crowdin download ##Credentials & config
```
3. See an error
```
I got this warning without any translations file added:
Couldn't find any file to download
Downloaded translations don't match the current project configuration. The translations for the following sources will be omitted (use --verbose to get the list of the omitted translations):
```

**Expected behavior**
I expect to be able to pull translations. 

`crowdin list sources` works by listing all the english string files but `crowdin download` does not seem to work as expected.

**Environment:**
 - OS: Mac
 - Version: 3.7.8

**Screenshots**

**Additional context**
I see that a zip file got downloaded and extracted but this happens in split seconds, and then the extracted folder is no longer found.

**Comment by andrii-bodnar** [comment]
Hi @Afolayan!

Could you please provide the `crowdin download --verbose` command output?

**Comment by Afolayan** [comment]
Hi @andrii-bodnar,

<img width="738" alt="Screenshot 2022-05-17 at 16 56 54" src="https://user-images.githubusercontent.com/9561500/168842635-3e668cb7-283f-4de7-93e1-41865acc19c4.png">
It goes on to list all the files and their different languages
<img width="704" alt="Screenshot 2022-05-17 at 16 58 24" src="https://user-images.githubusercontent.com/9561500/168842816-8af55d3d-712c-486d-89a2-d2cd6925acfc.png">

**Comment by andrii-bodnar** [comment]
@Afolayan thank you!

Please see this [comment](https://github.com/crowdin/crowdin-cli/issues/444#issuecomment-1109560099) and below. Your issue is also related to the `Resulting file after translations export`.

For CLI this export pattern should be the same as the `translation` pattern in the `crowdin.yml` configuration file. CLI passing it during the sources upload, but in case of files were uploaded in a different way, it should be specified manually.

It might affect some existing integrations because files structure will change in an exported archive with translations.

**Comment by Afolayan** [comment]
Thanks @andrii-bodnar, 
I just changed the `Resulting file after translations export` section and I could pull the translations. Big thanks.

I found a different issue with the format `%osx_locale%` I used. I got `zh-Hans and zh-Hant` instead of `zh-CN and zh-TW`; is there a format mismatch somewhere?

**Comment by andrii-bodnar** [comment]
@Afolayan you could use the [Language Mapping](https://support.crowdin.com/advanced-project-setup/#export) feature to change the language code for this placeholder to the preferred one.

**Comment by Afolayan** [comment]
That worked out.
The last item to get the script up is to be able to download the English sources; since I'm using the Crowdin-Figma plugin, devs do not have access to the untranslated texts. I would like to pull this source language alongside the translations. Could not find that in the docs.

**Comment by andrii-bodnar** [comment]
@Afolayan there is a separate CLI command for that:

```
crowdin download sources
```

**Comment by Afolayan** [comment]
Yes @andrii-bodnar, I later found that and tried it then got this error below:
It only works if the file is on the local machine, in a specified directory, and not pulling from Crowdin.

<img width="798" alt="Screenshot 2022-05-18 at 11 27 15" src="https://user-images.githubusercontent.com/9561500/169006575-16764079-2138-4279-9b69-7d1ecf55e1f5.png">

**Comment by andrii-bodnar** [comment]
@Afolayan probably the source files structure somehow mismatch the patterns in the configuration

**Comment by andrii-bodnar** [comment]
@Afolayan any updates? Is it still relevant for you?

**Comment by Afolayan** [comment]
Yes @andrii-bodnar . 
I found a solution by using different config files for downloading sources and downloading translations. All looks good now.

**Comment by andrii-bodnar** [comment]
@Afolayan great!
