### ISSUE TITLE
Can't delete or reset a translation string using "crowdin upload translations"

### ISSUE THREAD

**Issue by leonchabbey** [crowdin/crowdin-cli#459]
## Describe the bug

For instance, I have a `translations.json` file which is translated in English and French with:
```json
// en
{
  "greeting": "Hello"
}

// fr
{
  "greeting": "Bonjour"
}
```

### Update
if i update the french version with:
```json
{
  "greeting": "Salut"
}
```
and then run the command `crowdin upload translations` ---> **It works. The translation is updated in crowdin.**

### Delete
if i would like to "delete" or "reset" the translation, I should be able to update it with:
```json
// Replacing by an empty string:
{
  "greeting": ""
}

// or maybe by removing the key:
{
}
```
and then run the command `crowdin upload translations` ---> **Its not updated even though the cli said it has been uploaded.**

## Expected behavior
Changing a translation string to `""` (or deleting the json key) should remove the translation.

## Environment
 - OS: macOS Monterey
 - Version 12.3.1
 - Crowdin version: 3.7.9

**Comment by VadymSobchuk** [comment]
Hello,
It is expected behavior from our side. You can only upload new values as translations via CLI or update existing ones (the same will be via API or via similar actions in UI).
Deleting existing translations is only possible from the UI.
