### ISSUE TITLE
Can not store downloaded translations

### ISSUE THREAD

**Issue by Neralem** [crowdin/crowdin-cli#460]
**Describe the bug**
If I want to download translations I get an error.

**To Reproduce**
1. Configuration file: 

> "project_id": "projectId"
> "api_token": "apiToken"
> "base_path": "." # path to your project directory on a local machine
> "base_url": "https://api.crowdin.com" # https://{organization-name}.crowdin.com for Crowdin Enterprise
> "preserve_hierarchy": true
> 
> "files": [
>     {
>       "source": "/wwwroot/Translations/de/trans.json", #source files filter
>       "translation": "/wwwroot/Translations/%two_letters_code%/%original_file_name%", #where translations are stored
>     },
>   ]
> 

3. Execute CLI command: crowdin download -l nl --config crowdin.yml
4. See an error

> [OK] Fetching project info
> [OK] Building ZIP archive with the latest translations for 'nl'
> [OK] Building translation (100%)
> [OK] Downloading translations
> [OK] Extracting archive
> [ERROR] Failed to replace the file 'C:\ProjectPath\wwwroot\Translations\nl\trans.json'. Try to run the application with admin permission
> [ERROR] C:\ProjectPath\wwwroot\Translations\nl\trans.json

**Expected behavior**
Create/Overwrite the files with the downloaded ones.

**Environment:**
 - OS: Windows 11
 - Version 21H2

**Additional context**
I've startet the command prompt with admin privileges and removed write protection of the files but still the the same error. Also deleted / renamed the file but stills says that it could not replace it.

**Comment by tattiza** [comment]
Hi! Thanks for reporting a bug, we'll check it on our side and contact you back

**Comment by tattiza** [comment]
Could you please try to run the `crowdin download -l nl --config crowdin.yml --debug` command and share the result? Also, please let us know the CLI version you're using?

**Comment by Neralem** [comment]
> [OK] Fetching project info
> [OK] Building ZIP archive with the latest translations for 'nl'
> [OK] Building translation (100%)
> [OK] Downloading translations
> [OK] Extracting archive
> java.lang.RuntimeException: Failed to replace the file 'C:\ProjectPath\wwwroot\Translations\nl\trans.json'. Try to run the application with admin permission
>         at com.crowdin.cli.commands.functionality.FsFiles.copyFile(FsFiles.java:33)
>         at com.crowdin.cli.commands.actions.DownloadAction.lambda$act$6(DownloadAction.java:216)
>         at java.util.TreeMap.forEach(Unknown Source)
>         at com.crowdin.cli.commands.actions.DownloadAction.act(DownloadAction.java:215)
>         at com.crowdin.cli.commands.actions.DownloadAction.act(DownloadAction.java:58)
>         at com.crowdin.cli.commands.picocli.GenericActCommand.run(GenericActCommand.java:37)
>         at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
>         at picocli.CommandLine.access$1300(CommandLine.java:145)
>         at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
>         at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
>         at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
>         at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
>         at picocli.CommandLine.execute(CommandLine.java:2078)
>         at com.crowdin.cli.commands.picocli.PicocliRunner.execute(PicocliRunner.java:37)
>         at com.crowdin.cli.Cli.main(Cli.java:16)
> Caused by: java.nio.file.AccessDeniedException: C:\ProjectPath\wwwroot\Translations\nl\trans.json
>         at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
>         at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
>         at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
>         at sun.nio.fs.WindowsFileCopy.copy(Unknown Source)
>         at sun.nio.fs.WindowsFileSystemProvider.copy(Unknown Source)
>         at java.nio.file.Files.copy(Unknown Source)
>         at com.crowdin.cli.commands.functionality.FsFiles.copyFile(FsFiles.java:31)
>         ... 14 more

Version 3.7.9

I've copied the wwwroot folder and the config file to my desktop and tried the same there. The same error. I can not imagine that there is no permission.

**Comment by andrii-bodnar** [comment]
Hi @Neralem, it looks like the CLI has no permissions to write files on your file system: `AccessDeniedException: C:\ProjectPath\wwwroot\Translations\nl\trans.json`

**Comment by Neralem** [comment]
I've found out that the wwwroot folder also had write protection on it due to the TFS source control we are using. Removing this fixed my issue. Thanks
