### ISSUE TITLE
Cannot download jre11

### ISSUE THREAD

**Issue by BlackHole1** [crowdin/crowdin-cli#467]
**Describe the bug**

Execute `crowdin download` failed.

gist: https://gist.github.com/BlackHole1/f03751a7c38bc79d9484828527a78e7c

**To Reproduce**
1. `crowdin download`

**Expected behavior**

Normal Download

**Environment:**
 - OS: ubuntu
 - Version 18.04
 - Arch: x64

**Screenshots**

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/8198408/186067369-7337b675-927d-460a-af76-ecab77b6b78b.png">

https://github.com/electron/electronjs.org-new/runs/7965075991?check_suite_focus=true#step:5:11

**Additional context**

1. `crowdin-cli` use `jdeploy`
2. `jdeploy` use `njre`
3. `njre` download jre failed. Because it uses the adoptopenjdk v2 api
4. Currently the adoptopenjdk v2 api is not available.

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/8198408/186068224-b82daf08-d8a5-4dd9-9f68-e0ef20531767.png">

> https://api.adoptopenjdk.net/v2/info/releases/openjdk11?openjdk_impl=hotspot&release=latest&type=jre&os=linux&arch=x64

**Fix Suggest**

1. use `node-java-connector`

**Comment by Olena1234** [comment]
Hello! Thank you for the details, looking into this

**Comment by shannah** [comment]
jDeploy 3+ uses zulu as the default provider, and the CI script indicates that crowdin uses jDeploy 3.2.0 for current builds.
It is likely that this bug was produced by an old version of crowdin which uses an older version of jDeploy.

**Comment by BlackHole1** [comment]
@crowdin/cli fixed this bug in 3.7.9. See: https://github.com/crowdin/crowdin-cli/commit/4e7d9320c08f412d6fbe70d13076564fe7469cbb
