### ISSUE TITLE
Spanish not downloaded with  crowdin  command

### ISSUE THREAD

**Issue by ibeeger** [crowdin/crowdin-cli#468]
**Describe the bug**
crowdin download  lost  Spanish (es) every time  

**To Reproduce**
```yml
 "source" : "/WEB/教学报告-s_newreport/zh-CN.js",
  #
  # Where translations will be placed
  # e.g. "/resources/%two_letters_code%/%original_file_name%"
  #
  # "translation" : "/WEB/%two_letters_code%/%language%/%locale%.js",
  "translation" : "%two_letters_code%/WEB/教学报告-s_newreport/%locale%.js",
```
**Expected behavior**

**Environment:**
 - OS: macOS Monterey
 - Version 12.1

**Screenshots**
![image](https://user-images.githubusercontent.com/1124832/186805880-4e93dcd7-a614-4041-bfd4-66281ae9e298.png)

**Additional context**

**Comment by andrii-bodnar** [comment]
Hi @ibeeger, do you have some Spanish dialects as target languages in your Crowdin project?
