### ISSUE TITLE
Add Unit tests for the `crowdin download sources --reviewed` case

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-cli#490]
The new functionality was added In #471 PR without Unit tests covering it. It's a `--reviewed` parameter for the `crowdin download sources` command that allows downloading reviewed source files from the Source Text Review WF step in Crowdin Enterprise.

It would be great to add the Unit tests coverage for this case.

API methods that are used in this feature:
- [Build Reviewed Source Files](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.strings.reviewed-builds.post)
- [Check Reviewed Source Files Build Status](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.strings.reviewed-builds.get)
- [Download Reviewed Source Files](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.strings.reviewed-builds.download.download)

Test - [DownloadSourcesActionTest.java](https://github.com/crowdin/crowdin-cli/blob/cli3/src/test/java/com/crowdin/cli/commands/actions/DownloadSourcesActionTest.java)

**Comment by Genne23v** [comment]
Can I contribute to this?

**Comment by andrii-bodnar** [comment]
@Genne23v sure, thank you! Please let me know if you need any assistance with that

**Comment by andrii-bodnar** [comment]
HI @Genne23v, do you need any assistance here? Just wondering what the progress on this issue

**Comment by Genne23v** [comment]
Sorry that I had to follow up some of PRs for other repos. I will push something by tomorrow. Thanks for your reminding.

**Comment by andrii-bodnar** [comment]
Reopened this issue since we still have some uncovered code related to the "reviewed sources download" feature.

[CodeCov DownloadSourcesAction.java](https://app.codecov.io/gh/crowdin/crowdin-cli/blob/cli3/src/main/java/com/crowdin/cli/commands/actions/DownloadSourcesAction.java)
