### ISSUE TITLE
Increase the `StatusAction.java` class coverage by Unit tests

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-cli#492]
The [StatusAction.java](https://github.com/crowdin/crowdin-cli/blob/cli3/src/main/java/com/crowdin/cli/commands/actions/StatusAction.java) has a low coverage by Unit tests - [CodeCov Report](https://app.codecov.io/gh/crowdin/crowdin-cli/blob/cli3/src/main/java/com/crowdin/cli/commands/actions/StatusAction.java). 

It would be great to add coverage for the rest of the class methods.

**Comment by robertberes** [comment]
Hi @andrii-bodnar
I would like to work on this. Can you assign it to me?

**Comment by andrii-bodnar** [comment]
Hi @robertberes, thank you! Please let me know if you need any assistance with that
