### ISSUE TITLE
Empty strings when using `skip_untranslated_strings`

### ISSUE THREAD

**Issue by nicolas-godefroy-dev** [crowdin/crowdin-cli#497]
**Describe the bug**
I'm having the same problem described in [https://github.com/crowdin/crowdin-cli/issues/457](https://github.com/crowdin/crowdin-cli/issues/457) I updated my config file to use the skip_untranslated_strings: true option, however when I run the crowdin download via [crowdin github action](https://github.com/crowdin/github-action) the download files come with a bunch of empty strings where there is no translation yet.

**Expected behavior**
Terms without translations should not be present, instead of coming with an empty string.

Environment:
Crowdin CLI via github action
**Environment:**
 - OS: Ubuntu
 - Version latest

**Screenshots**
![Screenshot 2022-10-20 at 13 46 41](https://user-images.githubusercontent.com/10993705/196941373-4a027bda-6920-4e66-baab-787b7a4997d7.png)

**Comment by OlenkaCrowdin** [comment]
Hi @nicolas-godefroy-dev! 

Could you please share the link to the project in Crowdin as well?

**Comment by nicolas-godefroy-dev** [comment]
> Hi @nicolas-godefroy-dev!
> 
> Could you please share the link to the project in Crowdin as well?

Hi, sure [https://bounce.crowdin.com/u/projects/5](https://bounce.crowdin.com/u/projects/5).

**Comment by OlenkaCrowdin** [comment]
Dear @nicolas-godefroy-dev ,

We have applied the special post-processor for your project - as a result, the untranslated strings should be trimmed completely from the exported JSON files now.

Would you please try to download the translations once again and let me know how it goes? :)

**Comment by nicolas-godefroy-dev** [comment]
> Dear @nicolas-godefroy-dev ,
> 
> We have applied the special post-processor for your project - as a result, the untranslated strings should be trimmed completely from the exported JSON files now.
> 
> Would you please try to download the translations once again and let me know how it goes? :)

It works, thank you
