### ISSUE TITLE
Download jdk expirence should be improved

### ISSUE THREAD

**Issue by WestFarmer** [crowdin/crowdin-cli#501]
Hi, I am new to crowdin, I want to build some open source project's docs, which use crowdin for translating.

when running crowdin cli without internet access.

It just hangs forever, no timeout.

can't set alternative url to download jdk.

set `HTTP_PROX_HOST` and `HTTP_PROX_PORT` doesn't work.

set 'http_poxy' and 'https_proxy' doesn't work too.

also local jre is not used too, why waste time to download one while local JRE is already installed.

**Comment by andrii-bodnar** [comment]
Hi @WestFarmer!

Could you please clarify which way of installing the CLI you are using?

**Comment by WestFarmer** [comment]
it's pnpm's docs project.
see : https://github.com/pnpm/pnpm.github.io.git
@andrii-bodnar

**Comment by WestFarmer** [comment]
crowdin-cli -> jDeploy -> njre -> node-fetch
it seems I can't set proxy at runtime.

**Comment by andrii-bodnar** [comment]
@WestFarmer the Crowdin CLI NPM package is based on the jDeploy which uses the node-fetch library and this library handles the jdk fetching

Unfortunately, there is no possibility of passing the proxy from CLI through jDeploy to node-fetch

**Comment by WestFarmer** [comment]
I have modified jdeploy.js in node_modules skip njre install process and pass local JDK path to `run(ENV['JAVA_HOME'])`,  it works for me.

**Comment by andrii-bodnar** [comment]
@WestFarmer maybe it's a good point to create a PR with improvement into the jDeploy project?

https://github.com/shannah/jdeploy
