### ISSUE TITLE
`--skip-untranslated-strings` exports untranslated strings

### ISSUE THREAD

**Issue by djbb7** [crowdin/crowdin-cli#502]
**Describe the bug**
I have untranslated strings in Crowdin, yet when I call the CLI with `--skip-unstranslated-strings` flag those untranslated strings are part of the export.

**To Reproduce**
1. Create a nested string in the source file `en/bugreport.json`:
```json
{
    "someKey": {
        "TestString": "This is a test string"
    }
}
```
2. Push sources:
```bash
crowdin push sources
```
3. Push 'en' translations:
```bash
crowdin push translations --no-auto-approve-imported --language=en
```
4. Check in the UI that the Spanish string is **untranslated**:
<img width="2094" alt="image" src="https://user-images.githubusercontent.com/14298289/200868634-85d78078-1959-460c-bc7f-daa77a442fbd.png">

5. Pull translations and skip untranslated strings:
```bash
crowdin pull --skip-untranslated-strings
```
7. The empty string is cart of the export:
```bash
$ cat es/bugreport.json
{
    "someKey": {
        "TestString": ""
    }
}
```

**Expected behavior**
The unstranslated string should not be exported an the contents of `es/bugreport.json` should be: 
```
{}
```

**Environment:**
 - OS: OS X
 - Version 12.3

**Screenshots**

**Additional context**

**Comment by OlenkaCrowdin** [comment]
Hi @djbb7 !
Could you please share the link to the project in Crowdin?

**Comment by djbb7** [comment]
Hi @OlenkaCrowdin, I created a test project to verify the bug: `548195`.

This issue is also affecting our production project.

**Comment by OlenkaCrowdin** [comment]
Hi @djbb7 !

We have applied the special post-processor for your test project - as a result, the untranslated strings should be trimmed completely from the exported JSON files now.

Would you please try to download the translations once again and let me know how it goes? :)

Once it looks good, we can apply the same processor to other projects, just say the id of these projects.

**Comment by andrii-bodnar** [comment]
Hi @djbb7!

Is this issue still relevant or we can close it?
