### ISSUE TITLE
Crowdin CLI fails to install when using OpenJDK.

### ISSUE THREAD

**Issue by vxern** [crowdin/crowdin-cli#507]
**Describe the bug**
The installation script fails to detect the version, even when running the latest version of OpenJDK.

**To Reproduce**
1. Set %JAVA_HOME% to use an OpenJDK Java binary.
2. Run either the .bat installation script or the Windows installer.
3. Fails on basis of the Java version being too old.

**Expected behavior**
The CLI app should detect that the version is greater than required correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/56321034/203157686-2ef2b1e4-9fdd-4485-b365-479d2d09fed6.png)
![image](https://user-images.githubusercontent.com/56321034/203157755-bc9e305a-d555-4076-9357-d632541dc9ec.png)

**Comment by andrii-bodnar** [comment]
Hi @vxern, sorry for the inconvenience!

As a workaround, you can try using the npm (`npm i -g @crowdin/cli`) to install a CLI or the Standalone jar file.

We will look into that. By the way, we are happy to accept contributions 🙂 
The `.bat` script is located in the [scripts](https://github.com/crowdin/crowdin-cli/tree/cli3/scripts) directory.

**Comment by andrii-bodnar** [comment]
Another alternative solution - [Chocolatey](https://crowdin.github.io/crowdin-cli/installation#chocolatey)
