### ISSUE TITLE
Can I also update the source language translation file when push the source file？

### ISSUE THREAD

**Issue by cz1996** [crowdin/crowdin-cli#513]
My crowdin project's source language is English.

I wanna update en file when push upload resources in cli.

I don't know how to resolve it. Can anyone help me!!!!!

Thanks!

**Comment by andrii-bodnar** [comment]
@cz1996 could you please provide more details?

> I wanna update en file when push upload resources in cli.

The current repo is related to the Crowdin VS Code plugins. Please clarify which tool you use: CLI or VS Code plugin.

Where exactly do you need to update en file: Crowdin project or locally on your computer?

**Comment by cz1996** [comment]
I use crowdin cli.

just when running 'crowdin push', It'll update the source language in the crowdin project.

And my corwdin project's source language is English.

but English translation file do not update, so I have to upload en translations manually.

<img width="1274" alt="ff" src="https://user-images.githubusercontent.com/23058861/207229460-ae304e6b-4c01-4a35-a980-ce7e2a80581a.png">

**Comment by cz1996** [comment]
So is there any way for me to update the English translation when updating the source files?

I don't want to have to manually upload the English translation file after each update.

**Comment by andrii-bodnar** [comment]
@cz1996 try the following command:

```
crowdin upload translations -l en --import-eq-suggestions
```

There is no way to upload translations along with sources uploading. It's separate commands.
