### ISSUE TITLE
Versions `v3.7.8` and above aren't working in Docker based on `node:alpine`

### ISSUE THREAD

**Issue by Ky6uk** [crowdin/crowdin-cli#514]
**Describe the bug**
`@crowdin/cli` doesn't work in Docker.

**To Reproduce**
Steps to reproduce the behaviour:

1. `docker run -it --rm node:18-alpine /bin/sh`
2. `apk add openjdk11`
3. `npx @crowdin/cli@3.7.7` <- works
4. `npx @crowdin/cli@3.11.0` <- does not work

**Expected behavior**
Everything works.

**Environment:**
 - OS: Docker, `node:18-alpine`

**Additional context**
```
/app # npx @crowdin/cli@3.9.1 download
Downloading java runtime environment for version 11
/bin/sh: /root/.jdeploy/jre/11/jre/zulu11.60.19-ca-jre11.0.17-linux_x64/bin/java: not found
```

Getting an error that a file isn't found, but I have no idea what the file is because `/root/.jdeploy/jre/11/jre/zulu11.60.19-ca-jre11.0.17-linux_x64/bin/java` is here.

By the way, it works in `v3.7.7` and it's kind of a long-lasting issue.

**Comment by andrii-bodnar** [comment]
@Ky6uk probably, it's somehow related to the jDeploy version that was bumped exactly in the [3.7.8 release](https://github.com/crowdin/crowdin-cli/releases/tag/3.7.8).

CLI doesn't have control over the JRE downloading. Currently, we are using the 3.2.0 version of jDeploy. We will try to update to the latest 3.4.1 on the next CLI release.

**Comment by Ky6uk** [comment]
@andrii-bodnar I've installed `openjdk11` and `openjdk11-jre` using `apk` in the Docker image also, but it doesn't help. If you know what exactly should be installed or configured additionally (maybe some environment variables or so) to avoid this problem, it would be great. Currently, it's even not clear what the problem is exactly.

**Comment by andrii-bodnar** [comment]
@shannah is it something related to the jDeploy?

**Comment by andrii-bodnar** [comment]
@Ky6uk could you please check the latest version of CLI - 3.9.3? There was some update of the jDeploy package and CLI dependencies that could potentially fix your error

**Comment by shannah** [comment]
Fwiw, I tested out crowdin 3.9.3 and it appears to have fixed the issue.
My test procedure:

On Mac, Linux, or Windows:
Delete the existing jre and jdk directories to ensure that it has to download it again:

```bash
rm -rf ~/.jdeploy/jre* ~/.jdeploy/jdk*
```

Then create a temp directory and run crowdin using npx

```bash
mkdir /tmp/testcrowdin
npx @crowdin/cli@3.9.3
```

You'll notice that if you did `npx @crowdin/cli@3.9.2` it would fail with the error described in this issue, but with 3.9.3, it works.

**Comment by Ky6uk** [comment]
@shannah the problem is related to `node:18-alpine` Docker image that is mentioned in the initial post. There're no issues in other systems.

**Comment by shannah** [comment]
@Ky6uk Sorry.  Mixed this up with a different issue.

**Comment by Ky6uk** [comment]
@andrii-bodnar I did some small research regarding the problem. It looks like the Alpine Linux in the minimal `node:18-alpine` Docker image has some [specific things](https://stackoverflow.com/a/66974607/579745).

So even if the OpenJDK package is installed in the system by the `apk` package manager, `jdeploy` is trying to install its own Java runtime. But this version installed by `jdeploy` has some links to shared libraries that are not working

```
~ # ldd .jdeploy/jre/11/jre/zulu11.60.19-ca-jre11.0.17-linux_x64/bin/java
	/lib64/ld-linux-x86-64.so.2 (0x7f14a1f5c000)
	libz.so.1 => /lib/libz.so.1 (0x7f14a1f3e000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f14a1f5c000)
	libjli.so => .jdeploy/jre/11/jre/zulu11.60.19-ca-jre11.0.17-linux_x64/bin/../lib/jli/libjli.so (0x7f14a1f2d000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f14a1f5c000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f14a1f5c000)
Error relocating .jdeploy/jre/11/jre/zulu11.60.19-ca-jre11.0.17-linux_x64/bin/../lib/jli/libjli.so: __strdup: symbol not found
Error relocating .jdeploy/jre/11/jre/zulu11.60.19-ca-jre11.0.17-linux_x64/bin/../lib/jli/libjli.so: __rawmemchr: symbol not found
```

I've tried to install `gcompat` and run `npx @crowdin/cli@3.9.3` again, but got this

```
Unable to load native library: Error loading shared library libjvm.so: No such file or directory (needed by /root/.jdeploy/jre/11/jre/zulu11.60.19-ca-jre11.0.17-linux_x64/lib/libjava.so)
```

Not sure what's the exact problem here. But what I'm sure is the `crowdin@3.7.7` is using the system version of `openjdk-jre` installed and working perfectly even in the `node:18-alpine` in Docker. When `@crowdin/cli@3.7.8` and above are ignoring the system installed `openjdk-jre` and are trying to use the version provided by `jdeploy` that doesn't work in Alpine Linux.

**Comment by shannah** [comment]
If you set the JAVA_HOME environment variable, and the version of that JAVA_HOME is compatible with the version specified by crowdin (currently crowdin specifies java version 11), then it will use the version at JAVA_HOME.

So, if you want to install Java with a package manager, just make sure that:
1. The java version is "11"
2. Set the JAVA_HOME environment variable.

I've had many problems in the past with Alpine docker images for this same reason.  You just never know if they've cut a corner that is needed.

**Comment by Ky6uk** [comment]
@shannah it was the first thing I've tried tbh, but it doesn't work also. Maybe I'm doing it wrong, but still. I'm wondering why `@crowdin/cli@3.7.7` is working fine and just using the system-installed package without additional effort. 🤔 

```
~ # export | grep JAVA_HOME
export JAVA_HOME='/usr/lib/jvm/java-11-openjdk'
```

```
~ # ls -lh /usr/lib/jvm/java-11-openjdk
total 72K
-rw-r--r--    1 root     root        1.5K Oct 28 13:06 ASSEMBLY_EXCEPTION
-rw-r--r--    1 root     root       18.8K Oct 28 13:06 LICENSE
-rw-r--r--    1 root     root         376 Oct 28 13:06 README.md
drwxr-xr-x    2 root     root        4.0K Jan 17 23:23 bin
drwxr-xr-x    4 root     root        4.0K Jan 17 23:21 conf
drwxr-xr-x    4 root     root        4.0K Jan 17 23:23 demo
drwxr-xr-x    3 root     root        4.0K Jan 17 23:23 include
drwxr-xr-x    2 root     root       12.0K Jan 17 23:23 jmods
lrwxrwxrwx    1 root     root           1 Jan 17 23:20 jre -> .
drwxr-xr-x   72 root     root        4.0K Jan 17 23:20 legal
drwxr-xr-x    6 root     root        4.0K Jan 17 23:23 lib
drwxr-xr-x    4 root     root        4.0K Jan 17 23:23 man
-rw-r--r--    1 root     root        1.1K Oct 28 13:06 release
```

**Comment by shannah** [comment]
Can you provide the bones of the Dockerfile so I can try it myself?

**Comment by Ky6uk** [comment]
@shannah I'm using the pure `node:alpine` or `node:18-alpine`

```
docker run -it --rm node:alpine /bin/sh
```

And [`openjdk11`](https://pkgs.alpinelinux.org/packages?name=openjdk11*&branch=edge&repo=&arch=x86_64&maintainer=) installed through the `apk add`.

**Comment by shannah** [comment]
Thanks.
I see now.  Looks like I disabled the hook to use JAVA_HOME.  I'll look into adding that back.
In the mean time, here is a hack to get you unblocked.

1. Delete the `~/.jdeploy` directory. (this will be the default state).
2:  Symlink the system java into a place where jdeploy will look for it:

```bash
mkdir -p ~/.jdeploy/jre/11/jre && ln -s $JAVA_HOME ~/.jdeploy/jre/11/jre/openjdk11
```

3. Run crowdin:

```bash
npx @crowdin/cli@3.9.3
```

I don't think I'll add JAVA_HOME support directly back.  I think, instead I'll add a different environment variable that can be set.  E.g. JDEPLOY_OVERRIDE_JAVA_HOME or something.

**Comment by Ky6uk** [comment]
@shannah Thanks. It's not a blocker currently, but I'm a bit interested in how it was done in `v3.7.7` because `JAVA_HOME` there is still not set as an environment variable, but it's using the system installed version if it's available. What I can assume is the `jdeploy` is checking `java` in `PATH` somehow instead of checking `JAVA_HOME`.

**Comment by shannah** [comment]
@Ky6uk Yes, older versions of jDeploy looked on the PATH for java first, but this was problematic because jDeploy applications can specify some JVM requirements that aren't easily detectable on the PATH.  E.g. They can require that the JVM include JavaFX - and using java on the PATH would break this.

I've just pushed a change that adds support for a `JDEPLOY_JAVA_HOME_OVERRIDE` environment variable that will allow you to override the JAVA_HOME used.
https://github.com/shannah/jdeploy/commit/50efda35e530465aca031c25686d5ed0a7c7268a

I probably won't back-port it to 3.x, but will be in 4.0.2 when I release that.  And if crowdin chooses to build future releases using that, then it will be an option.

**Comment by andrii-bodnar** [comment]
@shannah thanks a lot for your help! 🚀 

Is it safe to upgrade to the `4.x.x` version?

**Comment by andrii-bodnar** [comment]
Released the [3.11.0](https://github.com/crowdin/crowdin-cli/releases/tag/3.11.0) version using the jDeploy **v4.0.22** for the npm package.

**Comment by Ky6uk** [comment]
@andrii-bodnar it's still the issue. Should it be configured somehow additionally after the upgrade? Maybe new parameters or environment variables?

```
> npx @crowdin/cli@3.11.0 download
npm WARN exec The following package was not found and will be installed: @crowdin/cli@3.11.0
Downloading java runtime environment for version 11
/bin/sh: /root/.jdeploy/jre/11/jre/zulu11.64.19-ca-jre11.0.19-linux_x64/bin/java: not found
```

**Comment by andrii-bodnar** [comment]
@Ky6uk it still feels like a jDeploy issue, unfortunately. @shannah do you have any ideas? We already use the latest version

**Comment by shannah** [comment]
I'm having trouble reproducing this.  Will try some more tomorrow.

**Comment by Ky6uk** [comment]
@shannah the reproduction steps that can help you:

1. `docker run -it --rm node:18-alpine /bin/sh`
2. `apk add openjdk11`
3. `npx @crowdin/cli@3.7.7` <- works
4. `npx @crowdin/cli@3.11.0` <- does not work

**Comment by shannah** [comment]
This appears to be an issue with alpine containers not including glibc which is necessary to zulu Java, which it downloads automatically.  Described here:

https://stackoverflow.com/a/66974607

Since in your reproduction example, you are installing your own java into the container, you can tell jdeploy to use that Java via the `JDEPLOY_JAVA_HOME_OVERRIDE` environment variable.  E.g. change item 4 to:

`JDEPLOY_JAVA_HOME_OVERRIDE=/usr/lib/jvm/java-11-openjdk npx @crowdin/cli@3.11.0`

and it will work.

**Comment by Ky6uk** [comment]
@shannah thanks.

@andrii-bodnar Is it possible to handle this case automatically or to add this somewhere to the documentation? 🤔

**Comment by andrii-bodnar** [comment]
@shannah thanks a lot!

**Comment by andrii-bodnar** [comment]
@Ky6uk I will consider adding it to the documentation. I don't have ideas how it can be handled automatically in this case
