### ISSUE TITLE
`download sources` doesn't handle configuration files with `**` wildcards in `source` when  `dest` is configured

### ISSUE THREAD

**Issue by rbioteau** [crowdin/crowdin-cli#519]
**Describe the bug**

When using a `**` wildcardis used in a `source` property of a `file` object in the configuration in addition to a `dest` property, the `download source` command does not find source files and display the following warning message:

```
⚠️  No sources found for '/folder_on_crowdin/%original_path%/%file_name%.properties' pattern. Check the source paths in your configuration file
```

**To Reproduce**
1. Configuration file: 

```json

"base_path": "."
"preserve_hierarchy": true

"files": [
    {
    "source": "folder1/folder2/**/messages.properties",
    "dest" : "/folder_on_crowdin/%original_path%/%file_name%.properties",
    "translation": "folder1/folder2/**/%file_name%_%two_letters_code%.properties"
   }
]
```

3. Execute CLI command: 
```
crowdin download sources -b <branch> -i <projectId> -T <api_token>
```
5. See an error

```
⚠️  No sources found for '/folder_on_crowdin/%original_path%/%file_name%.properties' pattern. Check the source paths in your configuration file
```

**Expected behavior**
Source files should be found and downloaded.

**Environment:**
 - OS: Ubuntu
 - Version 20.04

**Additional context**

I found a painful workaround by removing the `**` wildcard and explicit all my path in the configuration file.

```json

"base_path": "."
"preserve_hierarchy": true

"files": [
    {
    "source": "folder1/folder2/folder3/folder4/messages.properties",
    "dest" : "/folder_on_crowdin/folder1/folder2/folder3/folder4/%file_name%.properties",
    "translation": "folder1/folder2/folder3/folder4/%file_name%_%two_letters_code%.properties"
   }
]
```
In my use case, it requires having 90+ `file` objects in my configuration.

**Comment by rbioteau** [comment]
After testing the new version (3.11) it doesn't behave as expected (ant style pattern matcher ?) in the following use case:

```json
"base_path": "."
"preserve_hierarchy": true

"files": [
    {
    "source": "folder1/folder2/**/messages.properties",
    "dest" : "/folder_on_crowdin/%original_path%/%file_name%.properties",
    "translation": "folder1/folder2/**/%file_name%_%two_letters_code%.properties"
   },
  {
    "source": "folder1/folder2/**/plugin.properties",
    "dest" : "/folder_on_crowdin/%original_path%/%file_name%.properties",
    "translation": "folder1/folder2/**/%file_name%_%two_letters_code%.properties"
   }
]
```

When downloading sources, a `plugin.properties` file is created with the content of the `messages.properties` file and
`messages.properties` content is replaced with `plugin.properties` content.

**Comment by andrii-bodnar** [comment]
@rbioteau I just tested your configuration and can confirm that there is an issue with the sources download in this case. As a workaround, I would recommend adjusting your configuration to a single file group:

```yml
"base_path": "."
"preserve_hierarchy": true

"files": [
  {
    "source": "folder1/folder2/**/*.properties",
    "dest" : "/folder_on_crowdin/%original_path%/%file_name%.properties",
    "translation": "folder1/folder2/**/%file_name%_%two_letters_code%.properties"
  }
]
```

**Comment by rbioteau** [comment]
@andrii-bodnar Thanks for the tips !

However, it won't work for my use case as it will include all sort of properties files like localized `messages_<locale>.properties` and other properties files that has nothing to do with crowdin and l10n.

**Comment by andrii-bodnar** [comment]
#574

**Comment by andrii-bodnar** [comment]
https://github.com/crowdin/crowdin-cli/releases/tag/3.11.1
