### ISSUE TITLE
New node-fetch release, breaks crowdin upload

### ISSUE THREAD

**Issue by JellyfishCreations** [crowdin/crowdin-cli#523]
**Describe the bug**
The new 2.6.8 release of node-fetch has an error that breaks the `crowdin upload` command.

**To Reproduce**
1. Install newest version of `crowdin/cli`
3. Run `crowdin upload`

**Expected behavior**
The CLI should upload my newest translations to Crowdin

**Environment:**
 - OS: Docker: `node:18.12.1`

**Screenshots**
![image](https://user-images.githubusercontent.com/2675193/212302465-5576e080-2011-4bbc-8f3c-6023a6c33771.png)

**Comment by jsowinskiBC** [comment]
I have same issue
OS: Ubuntu 18
node: `16.19.0, 16.15.1`

```Downloading java runtime environment for version 11
/home/rof/.nvm/versions/node/v16.19.0/lib/node_modules/@crowdin/cli/node_modules/node-fetch/lib/index.js:1519
                        destroyStream(response.body, err);
                                               ^

TypeError: Cannot read properties of null (reading 'body')
    at /home/rof/.nvm/versions/node/v16.19.0/lib/node_modules/@crowdin/cli/node_modules/node-fetch/lib/index.js:1519:27
    at IncomingMessage.<anonymous> (/home/rof/.nvm/versions/node/v16.19.0/lib/node_modules/@crowdin/cli/node_modules/node-fetch/lib/index.js:1749:6)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:513:28)
    at emitCloseNT (node:internal/streams/destroy:138:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)```

**Comment by andrii-bodnar** [comment]
It's interesting. CLI uses the [JDeploy](https://github.com/shannah/jdeploy) tool to package the NPM package and Jdeploy uses node-fetch under the hood

@shannah, do you have any ideas on how to fix this issue or at least lock the node-fetch version?

**Comment by shannah** [comment]
@andrii-bodnar I think node-fetch may be a red herring.  More likely that it was an issue fixed by [this commit](https://github.com/shannah/jdeploy/commit/139a7a993f4c7bbd7f074852997cb6b7618926e1).

I would try updating jdeploy to the latest (3.4.2+ or 4.x) and redeploy crowdin-cli with it.  That will include the update.

**Comment by andrii-bodnar** [comment]
@shannah currently, the `jdeploy@3.2.0` is used. Will it be enough to update to the **3.4.2** version?

**Comment by DamienCassou** [comment]
jdeploy@3.4.2 doesn't fix anything for me

**Comment by DamienCassou** [comment]
For me the workaround was to force installation of `node-fetch@2.6.7`:

```json
{
  "devDependencies": {
    "@crowdin/cli": "^3.9.1"
  },
  "resolutions": {
    "node-fetch": "2.6.7"
  }
}
```

**Comment by shannah** [comment]
That's interesting,  When you say that `jdeploy@3.4.2` doesn't fix anything, does that mean you updated to jdeploy and used it to bundle a new release of crowdin, and then tried to use that newly built crowdin? or something else.

I have just pushed some changes to use this new version of node-fetch and will be releasing soon as jdeploy 3.4.3.  However, this really only affects how jdeploy sets up projects.  Crowdin-cli should replace its njre dependency (in its package.json file) with:

```json
        "command-exists-promise": "^2.0.2",
        "node-fetch": "^2.6.7",
        "tar": "^4.4.8",
        "yauzl": "^2.10.0"
```

Then publish a new version.

**Comment by DamienCassou** [comment]
> When you say that jdeploy@3.4.2 doesn't fix anything, does that mean you updated to jdeploy and used it to bundle a new release of crowdin, and then tried to use that newly built crowdin?

I didn't pay attention and just tried to have jdeploy@3.4.2 along with crowdin before executing crowdin.

**Comment by andrii-bodnar** [comment]
The new version of CLI has been released - [3.9.2](https://github.com/crowdin/crowdin-cli/releases/tag/3.9.2)

**Comment by DamienCassou** [comment]
I can still reproduce the issue: https://github.com/crowdin/crowdin-cli/issues/526.

**Comment by andrii-bodnar** [comment]
@shannah I did it as you suggested - https://github.com/crowdin/crowdin-cli/pull/524/files

do you have any ideas why this still happens?

BTW, it works on my machine:

```
openjdk version "18.0.1" 2022-04-19
OpenJDK Runtime Environment Homebrew (build 18.0.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.1+0, mixed mode, sharing)
```

**Comment by shannah** [comment]
Hmm..  Yes.  I can reproduce this.  I think the node-fetch bug is in 2.6.8, based on the observations here.  So my advice to set `"node-fetch": "^2.6.7",` should have been `"node-fetch": "2.6.7",`

Haven't had a chance to test this out, but pretty sure that will do it.

**Comment by andrii-bodnar** [comment]
@shannah thank you, the `^` indeed allows downloading the 2.6.8 version 😬
