### ISSUE TITLE
discord bot wrong message sent

### ISSUE THREAD

**Issue by Geczy** [crowdin/crowdin-cli#534]
**Describe the bug**

github bot is not saying the correct strings, but its saying the correct ids

![image](https://user-images.githubusercontent.com/1036968/216099205-69a3144e-f7e3-4436-802b-5da33b14583a.png)

![image](https://user-images.githubusercontent.com/1036968/216137613-085975fc-9a34-4e9c-bada-8f1e300dd55a.png)

**Comment by TaniaMal** [comment]
Hi @Geczy! Could you please share some more details on the matter?

**Comment by Geczy** [comment]
oops sorry i was just reading too fast, no bug here 🆗
