### ISSUE TITLE
Successful translation status when version branch has nothing to translate

### ISSUE THREAD

**Issue by blytheaw** [crowdin/crowdin-cli#535]
**Is your feature request related to a problem? Please describe.**
We have a use case where we want to check if a (strict) version branch has been fully translated. The `crowdin status` command works great for the most part when there is at least one new string on the version branch since the `--fail-if-incomplete` has been added. However, sometimes a version branch is created that has no new strings (i.e. "Nothing to translate"), but the `crowdin status` command with `--fail-if-incomplete` fails saying the translation status is at 0%. 

**Describe the solution you'd like**
I would like the translation status command to return successful if the specific branch has nothing to translate.

**Describe alternatives you've considered**
I have looked for a way to identity if the branch has nothing to translate before running the status, but I have not been successful. If there is a way to do this, please let me know.

**Additional Context**
We are getting around this currently by directly hitting the API in our GitHub Action, but this is verbose and error prone and hard to maintain over time:

```
PROJECT_ID=${{ secrets.CROWDIN_PROJECT_ID }}
TOKEN=${{ secrets.CROWDIN_API_TOKEN }}
BRANCH_ID=$(curl -s -X GET -H "Authorization: Bearer $TOKEN" "https://api.crowdin.com/api/v2/projects/$PROJECT_ID/branches?name=${{ steps.extract_branch.outputs.branch }}" | jq -r '.data[0].data.id')
INCOMPLETE_LANGUAGES=$(curl -s -X GET -H "Authorization: Bearer $TOKEN" https://api.crowdin.com/api/v2/projects/$PROJECT_ID/branches/$BRANCH_ID/languages/progress | jq '.data[].data | select(.words.total > 0 and .translationProgress != 100) | .translationProgress' | wc -l)
if [ $INCOMPLETE_LANGUAGES -ne 0 ]; then
  echo "Failure: Not all strings have been translated in Crowdin!"
  exit 1
else
  echo "Success: Translations are complete in Crowdin!"
fi
```

Ideally we could have a cleaner, more concise way to solve this problem using the CLI alone.

**Comment by andrii-bodnar** [comment]
The `crowdin status` command relies on the `translationProgress`/`approvalProgress` API response to determine the translation or approval progress. It's possible to check if the branch has nothing to translate via the `data.words.total` (or `phrases`) value. 

But in the case when the `data.words.total` is `0`, the `*Progress` response value is still `0`:

```json
"data": {
    "languageId": "de",
    "words": {
        "total": 0,
        "translated": 0,
        "approved": 0
    },
    "phrases": {
        "total": 0,
        "translated": 0,
        "approved": 0
    },
    "translationProgress": 0,
    "approvalProgress": 0
}
```

So I'm not sure if it would be correct behavior to consider the progress as 100% on the CLI side in this case.

As a workaround, you can use the [Crowdin Request Action](https://github.com/andrii-bodnar/crowdin-request-action) to easily check the branch words or phrases count in your workflow.
