### ISSUE TITLE
Crowdin Branch being created when there are no Translations

### ISSUE THREAD

**Issue by safa007** [crowdin/crowdin-cli#550]
**Describe the bug**
We've just started having an issue today at Turo where a branch on crowdin is being created when there are no translation/string changes to be uploaded. This is causing some weird behavior on our Pull Requests where strings that were already translated are being reverted to English.

**To Reproduce**
1. crowdin upload sources -b {branch_name}
2. crowdin branch is created

**Expected behavior**
Crowdin branch should not be created if there are no strings to be uploaded.

**Environment:**
 - OS: Linux
 - version 4.4.0-1101-aws

**Screenshots**

![Screenshot 2023-03-27 at 4 21 19 PM](https://user-images.githubusercontent.com/26886907/228088472-0feb002a-5a43-412d-9fdf-6535cafd5cfb.png)

**Comment by andrii-bodnar** [comment]
@safa007 as I can see, you're using a deprecated CLI v2. Please try updating to the latest CLI v3 (3.10.1).

The migration between v2 and v3 requires changes in the `crowdin.yml` configuration file related only to the authorization (`project_id`, `api_token`).

Thanks.
