### ISSUE TITLE
Illegal repetition near index 1 when module path contains characters like '{{' in the name

### ISSUE THREAD

**Issue by anthonymonori** [crowdin/crowdin-cli#551]
**Describe the bug**

Crowdin CLI breaks on `upload sources` or `download` commmand when the root project contains `values.xml` in a template directory

```
❌ Illegal repetition near index 1
{{cookiecutter\.module_name}}
```

Full path is:
`tools/cookiecut/src/templates/multiplatform_implementation_module/{{cookiecutter.module_name}}/src/androidMain/res/values/strings.xml`

**To Reproduce**
1. Add a folder with `strings.xml` into a folder that has `{{}}` in its name
2. Execute CLI command: 'download' or 'upload sources'
3. ❌ Illegal repetition near index 1

**Expected behavior**
It wouldn't fail uploading those sources because of illegal repetition in the name

**Environment:**
 - Java CLI 3.9.0

**Additional context**

I know the solution is to not upload such folder names, and it's easy to ignore and not generate a file entry for it in `crowdin.yml` so it doesn't get parsed by the CLI, but it's still a sub-optimal result. What do you think?

**Comment by andrii-bodnar** [comment]
https://github.com/crowdin/crowdin-cli/releases/tag/3.11.1
