### ISSUE TITLE
CROWDIN_HOME env won't be removed after running unins000.exe

### ISSUE THREAD

**Issue by hwhsu1231** [crowdin/crowdin-cli#577]
**Describe the bug**

`CROWDIN_HOME` env won't be removed after running `unins000.exe` to uninstall the Windows Installer version of [crowdin-cli](https://downloads.crowdin.com/cli/v3/crowdin.exe). 

Therefore, after running `setup_crowdin.bat` to install Standalone version of [crowdin-cli](https://crowdin.github.io/crowdin-cli/installation#standalone-version), it cannot find the `crowdin-cli.jar` in the current directory. Instead, it will show the following error:

```cmd
D:\Test\3.11.0# crowdin --version
Error: Unable to access jarfile C:\Program Files (x86)\CrowdinCLI\crowdin-cli.jar
```

**To Reproduce**

1. Download and run [crowdin.exe](https://downloads.crowdin.com/cli/v3/crowdin.exe) Windows installer to install crowdin-cli in the default location.
2. Download and unzip the [crowdin-cli.zip](https://github.com/crowdin/crowdin-cli/releases/download/3.11.0/crowdin-cli.zip) from the release of GitHub, and then run the `setup_crowdin.bat` with Admin permission in the terminal.
3. Run `unins000.exe` to uninstall the Windows Installer version of crowdin-cli.
4. Reopen the Terminal and run the command `crowdin --version`.

**Expected behavior**

Show the version of crowdin-cli installed without any error message.

**Environment:**

 - OS version: `Windows 11`
 - crowdin-cli version: `3.11`

**Screenshots**

![image](https://user-images.githubusercontent.com/71438617/235359094-f9436813-7c07-4273-b435-d9f9188a0867.png)
![image](https://user-images.githubusercontent.com/71438617/235359100-1a1e4304-fadb-461c-ba84-248a387aae9f.png)
![image](https://user-images.githubusercontent.com/71438617/235359044-f4b69d93-8f32-4874-8eab-65f727dde842.png)

**Additional context**

And after removing the `CROWDIN_HOME` of Windows Installer version, I found that the Standalone version of crowdin-cli can work successfully. Therefore, I think `unins000.exe` should  remove this `CROWDIN_HOME` env together.

![image](https://user-images.githubusercontent.com/71438617/235359757-e885efb4-fd59-424b-b6cf-45a518020191.png)

**Comment by andrii-bodnar** [comment]
@hwhsu1231 the `CROWDIN_HOME` is being set in the Crowdin ISS installer script as follows:

```iss
[Registry]
Root: HKCU; Subkey: "Environment"; ValueType:string; ValueName:"PATH"; ValueData:"{olddata};{app}"; Flags: preservestringtype
Root: HKCU; Subkey: "Environment"; ValueType:string; ValueName:"CROWDIN_HOME"; ValueData:"{app}"; Flags: preservestringtype
```

Do you have any ideas on how to declare the uninstall instruction to remove this variable?

**Comment by hwhsu1231** [comment]
> Do you have any ideas on how to declare the uninstall instruction to remove this variable?

@andrii-bodnar - Sorry, I don't have any idea for now since I haven't researched this part yet. Hope someone can fix this problem.

**Comment by andrii-bodnar** [comment]
@hwhsu1231 by the way, as an alternative solution you can use our [Chocolatey package](https://crowdin.github.io/crowdin-cli/installation#chocolatey)
