### ISSUE TITLE
Is CROWDIN_HOME environment variable only needed on Windows platform?

### ISSUE THREAD

**Issue by hwhsu1231** [crowdin/crowdin-cli#607]
### Problem Description

When I follow the installation instructions for the [Standalone Version of Crowdin-CLI](https://crowdin.github.io/crowdin-cli/installation#standalone-version) on the Windows platform, it will set an environment variable called `CROWDIN_HOME` in the system environment and append the value of `CROWDIN_HOME` to the `PATH` environment variable. (See [setup_crowdin.bat](https://github.com/crowdin/crowdin-cli/blob/3.13.0/scripts/setup_crowdin.bat) for details)

However, I found that if I don't add `CROWDIN_HOME` to the system environment, and instead directly add the path where `crowdin.bat` is located to the `PATH` environment variable, then even if `where crowdin.bat` can locate the batch file, `crowdin.bat` still cannot function properly (displaying an error message: **"crowdin is NOT defined"**). For example:

```cmd
D:\Test\crowdin\3.13.0>crowdin --version
crowdin is NOT defined
```

Since I didn't find any `CROWDIN_HOME` string inside the [install-crowdin-cli.sh](https://github.com/crowdin/crowdin-cli/blob/3.13.0/scripts/install-crowdin-cli.sh), I wonder whether this ENV is only needed on Windows platoform?

### Version and Platform

* OS version: `Windows 11`
* Crowdin version: `3.13.0`

**Comment by andrii-bodnar** [comment]
Hi @hwhsu1231, yes, it's only needed for this bat script
