### ISSUE TITLE
Space before semi-colon in`crowdin.yml`

### ISSUE THREAD

**Issue by mrleblanc101** [crowdin/crowdin-cli#610]
**Describe the bug**
Sometime there is a space before the semi-colon, sometime there is not.

```yml
#
# Your Crowdin credentials
#
"project_id" : "" # Space before colon
"api_token" : "" # Space before colon
"base_path" : "" # Space before colon
"base_url" : "" # Space before colon
#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true # No space before colon
```

**To Reproduce**
1. Execute `crowdin init`

**Expected behavior**
The spacing should be consistant.
I suggest removing the space between the key and the semi-colon, but keeping the space after the semi-colon.

**Environment:**
 - OS: macOS
 - Version 13.4.0

```diff
#
# Your Crowdin credentials
#
- "project_id" : ""
- "api_token" : ""
- "base_path" : ""
- "base_url" : ""
+ "project_id": ""
+ "api_token": ""
+ "base_path": ""
+ "base_url": ""
#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true
```

**Comment by andrii-bodnar** [comment]
Hi @mrleblanc101, this has been fixed in version [3.12.0](https://github.com/crowdin/crowdin-cli/releases/tag/3.12.0) in PR #584. Please update the CLI to the latest version
