### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-cli#615]
[versions.properties](https://github.com/crowdin/crowdin-cli/blob/main/versions.properties)

only minor and patch versions

**Comment by SunilKumar-K** [comment]
Can you assign this issue for me.

**Comment by SunilKumar-K** [comment]
@andrii-bodnar I can see that some of the dependencies already have the caret (^) symbol before their version numbers, which indicates that minor and patch updates are allowed right in package.json .
```shell
  "dependencies": {
    "command-exists-promise": "^2.0.2",
    "node-fetch": "2.6.7",
    "shelljs": "^0.8.4",
    "tar": "^4.4.8",
    "yauzl": "^2.10.0"
  },.

``` 
  
  and also I wanna know is there any modifications in devdepencies to update .  or anything else please let me know

**Comment by andrii-bodnar** [comment]
@SunilKumar-K we need to update dependencies in the [versions.properties](https://github.com/crowdin/crowdin-cli/blob/main/versions.properties) file, not `package.json`

**Comment by SunilKumar-K** [comment]
Okay , I have one doubt here i wanna edit with available versions or any things else.

```version.junit.jupiter=5.9.3
##        # available=5.10.0-M1
##        # available=5.10.0-RC1
##        # available=5.10.0-RC2
##        # available=5.10.0
``` 

like I wanna remove 5.9.3 and put 5.10.0 and i wanna run this command right  ./gradlew refreshVersions

need to remove old versions and need to add available versions that are putting in below that right

**Comment by andrii-bodnar** [comment]
@SunilKumar-K I'm not sure if I understood you correctly. How can I help you with your question?

**Comment by SunilKumar-K** [comment]
I'm asking like need to remove older versions and add new versions right

**Comment by andrii-bodnar** [comment]
Yes, but only minor and patch versions

**Comment by SunilKumar-K** [comment]
can I know more about minor and patch versions in this repository ?

**Comment by andrii-bodnar** [comment]
https://semver.org/

Given a version number MAJOR.MINOR.PATCH, increment the:

- MAJOR version when you make incompatible API changes
- MINOR version when you add functionality in a backward compatible manner
- PATCH version when you make backward compatible bug fixes

Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by andrii-bodnar** [comment]
@SunilKumar-K do you have any updates on this?

**Comment by SunilKumar-K** [comment]
yes, I did something on it but don't know is it correct or not, I will make a pull request today okay you can check it once .

**Comment by ddninja** [comment]
@andrii-bodnar Can I work on this?

**Comment by ddninja** [comment]
hi @andrii-bodnar have raise the pull request with the fix, can you please check.
