### ISSUE TITLE
"Building translation" progress message eats into other lines

### ISSUE THREAD

**Issue by ervinchai** [crowdin/crowdin-cli#619]
**Describe the bug**
When pulling translations from Crowdin through the Crowdin CLI, the "Building translation" progress output message eats into other lines. See screenshots for a visualization of this happening.

**To Reproduce**
1. Configuration file: 
```
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"project_id": "27"
"base_path": "."
"base_url": "<REDACTED>"
"preserve_hierarchy": false
files: [
  {
    "source": "/config/locales/en.yml",
    "translation": "/config/locales/%two_letters_code%.yml"
  },
  {
    "source": "/config/locales/javascript/en.yml",
    "translation": "/config/locales/javascript/%two_letters_code%.yml"
  }
]
```
2. Execute CLI command: `crowdin pull`
3. See an error

**Expected behavior**
The "Building translation" message stays in its own line and does not eat into other lines.

**Environment:**
 - OS: `macOS Ventura 13.4.1`
 - Version: `3.13.0`

**Screenshots**
<img width="1041" alt="Screenshot 2023-08-07 at 4 41 22 PM" src="https://github.com/crowdin/crowdin-cli/assets/88306776/10b10258-e585-4614-bb44-d66fec62edaf">
<img width="1042" alt="Screenshot 2023-08-07 at 4 41 28 PM" src="https://github.com/crowdin/crowdin-cli/assets/88306776/9432c836-46b5-41fc-9f0a-03da9b31aa15">
<img width="1036" alt="Screenshot 2023-08-07 at 4 41 58 PM" src="https://github.com/crowdin/crowdin-cli/assets/88306776/6e235185-dd73-40a6-a1a9-f02ba7da8219">

**Comment by andrii-bodnar** [comment]
Hi @ervinchai, 

could you please check if the issue is reproducible in another terminal?

Thank you!

**Comment by andrii-bodnar** [comment]
By the way, you can also try adding the `--no-progress` parameter to the executed command
