### ISSUE TITLE
pre-translate all project languages

### ISSUE THREAD

**Issue by weakfl** [crowdin/crowdin-cli#620]
**Is your feature request related to a problem? Please describe.**

When working with multiple feature branches it happens that translations are lost, depending on the order of branch creation/deletion. If that happens it's necessary to pre-translate all target languages via TM to restore the translations.

**Describe the solution you'd like**

It would be great if it would be possible to pre-translate all target languages at once instead of having to specify each language code separately. Eg. `crowdin pre-translate -l=all --method=tm --translate-with-perfect-match-only`

**Comment by andrii-bodnar** [comment]
@weakfl thanks for the request!

Having the `all` value for the `-l` parameter sounds good but has several downsides. It's a new approach that hasn't been used in the CLI before. Then, it becomes hard to validate. The user can pass `-l all -l fr -l de` and it's not clear how to behave in this case.

So, I would suggest making the `-l`/`--language` parameter optional and passing all the project target languages in the [Apply Pre-Translation](https://developer.crowdin.com/api/v2/#operation/api.projects.pre-translations.post) API request in case the user didn't pass any language.

**Comment by weakfl** [comment]
> So, I would suggest making the -l/--language parameter optional and passing all the project target languages in the [Apply Pre-Translation](https://developer.crowdin.com/api/v2/#operation/api.projects.pre-translations.post) API request in case the user didn't pass any language.

@andrii-bodnar yes, that sounds like a reasonable approach. Would love to see this implemented, thanks.

**Comment by weakfl** [comment]
@andrii-bodnar thanks for implementing this so quickly. Any timeframe for the next release?

**Comment by andrii-bodnar** [comment]
@weakfl Actually, it should work even without the release. Please check the #624 for the related changes

**Comment by weakfl** [comment]
@andrii-bodnar ah, nice. Does this also apply if called through the [crowdin/github-action](https://github.com/crowdin/github-action)?

**Comment by andrii-bodnar** [comment]
@weakfl sure, it should work with the GitHub Action as well
