### ISSUE TITLE
support upload screenshot from cli

### ISSUE THREAD

**Issue by taozhou-glean** [crowdin/crowdin-cli#625]
**Is your feature request related to a problem? Please describe.**

We have automated pipelines that will upload the message catalog upon commits, right now we rely on manual effort to upload screenshots for our translators, it would be great if we can support upload screenshots from cli, then we can make that process automated as well.

**Describe the solution you'd like**

`crowdin screenshot upload image_url/blob`

**Comment by andrii-bodnar** [comment]
@taozhou-glean thank you for your request, this is already on our roadmap :)

**Comment by andrii-bodnar** [comment]
@taozhou-glean already available in [3.14.0](https://github.com/crowdin/crowdin-cli/releases/tag/3.14.0)
