### ISSUE TITLE
Add the '--label' parameter to the 'pre-translate' command

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-cli#640]
**Description**

Crowdin has recently enhanced the [Apply Pre-Translation](https://developer.crowdin.com/api/v2/#operation/api.projects.pre-translations.post) API to allow passing labels to filter strings for pre-translation.

The new `--label` option should be added to the `crowdin pre-translate` command as well. 

```yml
SYNOPSIS:
crowdin pre-translate [CONFIG OPTIONS] [OPTIONS]

DESCRIPTION:
Pre-translate files via Machine Translation (MT) or Translation Memory (TM)

OPTIONS:
...
      --label=...         Label identifier. Could be specified multiple times
...
```

It should accept **string** values of label names. Use should be able to specify multiple labels simultaneously (e.g. `crowdin pre-translate --label android --label ios --label web ...`)

**Additional Context**

Similar commands for reference: `BundleAddSubcommand`, `StringAddSubcommand`, `TaskAddSubcommand`.
Documentation:[`crowdin pre-translate`](https://crowdin.github.io/crowdin-cli/commands/crowdin-pre-translate)
Blocked by: https://github.com/crowdin/crowdin-api-client-java/issues/188

**Comment by debanjanc01** [comment]
Hey @andrii-bodnar is this up for grabs?

**Comment by andrii-bodnar** [comment]
Hi @debanjanc01, sure, would you like it to be assigned to yourself?

**Comment by andrii-bodnar** [comment]
UPD: need to update the `crowdin-api-client-java` to the [1.11.4](https://github.com/crowdin/crowdin-api-client-java/releases/tag/1.11.4) version

**Comment by debanjanc01** [comment]
@andrii-bodnar I'll give a go at this.

**Comment by debanjanc01** [comment]
Hey @andrii-bodnar is the `crowdin-api-client-java` 1.11.4 available on jitpack.io? I'm unable to find it.
https://jitpack.io/com/github/crowdin/crowdin-api-client-java/1.11.4/build.log

Going by the build.log, it seems that the artifact wasn't pushed to remote.
```
Found artifact: com.github.crowdin:crowdin-api-client-java:1.11.4
Found artifact: :crowdin-api-client-java:1.11.4
ERROR: Time-out getting container status
Error building
```

I've attached the build.log file for reference. 
[jitpack.io_com_github_crowdin_crowdin-api-client-java_1.11.4_build.log](https://github.com/crowdin/crowdin-cli/files/12795397/jitpack.io_com_github_crowdin_crowdin-api-client-java_1.11.4_build.log)

**Comment by andrii-bodnar** [comment]
@debanjanc01 thanks for noticing that! 

There was indeed some build error. I just deployed a new version - [1.11.5](https://github.com/crowdin/crowdin-api-client-java/releases/tag/1.11.5)

**Comment by debanjanc01** [comment]
Hey @andrii-bodnar I can see the artifacts are available now for 1.11.5

I'll update the version accordingly then to 1.11.5

**Comment by debanjanc01** [comment]
@andrii-bodnar can you please confirm if the Pre Translate expects labels as String or Integer?
The [ApplyPreTranslationRequest.java ](https://github.com/crowdin/crowdin-api-client-java/blob/4788ea505dae3335deab16aa83a4e59fa725eeeb/src/main/java/com/crowdin/client/translations/model/ApplyPreTranslationRequest.java#L19) in `crowdin-api-client-java` also takes in List of integers.

**Comment by andrii-bodnar** [comment]
@debanjanc01 the `--label` parameter should accept a string. It means that before making an API call, we need to additionally collect IDs based on the passed label names.

**Comment by debanjanc01** [comment]
@andrii-bodnar got it. Could you help me understand where to collect/translate the IDs from? Is there an existing mapping I can refer to? I'm unable to find something similar on the codebase

**Comment by andrii-bodnar** [comment]
@debanjanc01 you need to use the [listLabels](https://github.com/crowdin/crowdin-api-client-java/blob/master/src/main/java/com/crowdin/client/labels/LabelsApi.java#L48) method.

Please refer to the following commands for reference: `BundleAddSubcommand`, `StringAddSubcommand`, `TaskAddSubcommand`. These commands already contain the exact same functionality.

**Comment by debanjanc01** [comment]
Hey @andrii-bodnar found it! Thanks!

**Comment by debanjanc01** [comment]
Hey @andrii-bodnar , I've raised the PR. Please have a look and let me know.
Also, we could put the `prepareLabelIds` method as a Util and use it in all actions that use it, rather than duplicating code. What do you think?

**Comment by andrii-bodnar** [comment]
@debanjanc01 thank you!

Yes, it would be great to extract this method to avoid code duplication

**Comment by debanjanc01** [comment]
@andrii-bodnar shall I make it a part of the [src/main/java/com/crowdin/cli/utils/Utils.java](https://github.com/crowdin/crowdin-cli/blob/main/src/main/java/com/crowdin/cli/utils/Utils.java) class?

**Comment by andrii-bodnar** [comment]
@debanjanc01 yes, I think this class is a good candidate. If possible, it would be good to have a Unit test as well for this method
