### ISSUE TITLE
Ambigious error and download failure 

### ISSUE THREAD

**Issue by rosenpin** [crowdin/crowdin-cli#642]
**Describe the bug**
Every time I'm trying to run the script to pull translations it exists with an "error" message without any other information

**To Reproduce**
Not sure what's the cause so can't really help with that. All I know is that the script used to work and stopped working at some point.

**Expected behavior**
Download the translations

**Environment:**
 - OS: MacOS
 - Version 13.5.1

**Screenshots**
<img width="696" alt="image" src="https://github.com/crowdin/crowdin-cli/assets/5289630/b4e96b9c-6401-4ea4-8e08-5696571532c6">

**Additional context**
The verbose mode doesn't add much:
<img width="1251" alt="image" src="https://github.com/crowdin/crowdin-cli/assets/5289630/4e7f9c6c-aabd-446d-81ac-5b4a839972ce">

**Comment by andrii-bodnar** [comment]
Hi @rosenpin, it looks like you're using an extremely outdated version of the Crowdin CLI (probably, some 2.x). This version is no longer supported. Please try updating to the latest version.
