### ISSUE TITLE
Unable to download sources when source and dest are different

### ISSUE THREAD

**Issue by fabianhelm** [crowdin/crowdin-cli#647]
**Describe the bug**
Cannot download sources when `source` and `dest` are different

**To Reproduce**
I have following configuration

```
# Files configuration
files: [
    {
      "source": "backend/locale/en/LC_MESSAGES/django.po",
      "dest": "crowdin/backend/django.po",
      "translation": "crowdin/backend/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%",
    },
    {
      "source": "webclient/apps/app/src/i18n/messages.en.xlf",
      "dest": "crowdin/webclient/messages.en.xlf",
      "translation": "crowdin/webclient/apps/app/src/i18n/messages.%two_letters_code%.xlf",
    }
]
```

download of translations is working, listing of sources is working, but downloading of sources is not working:

```
(py311) ➜  core git:(crowdin-download) ✗ ./webclient/node_modules/.bin/crowdin list sources    
✔️  Fetching project info    
✔️  File 'backend/locale/en/LC_MESSAGES/django.po'
✔️  File 'webclient/apps/app/src/i18n/messages.en.xlf'
```

Failing to download sources:

```
(py311) ➜  core git:(crowdin-download) ✗ ./webclient/node_modules/.bin/crowdin download sources
✔️  Fetching project info    
⚠️  No sources found for 'crowdin/backend/django.po' pattern. Check the source paths in your configuration file
⚠️  No sources found for 'crowdin/webclient/messages.en.xlf' pattern. Check the source paths in your configuration file
```

**Screenshots**
The structure on the crowdin server looks like this:

![image](https://github.com/crowdin/crowdin-cli/assets/109150546/5ddd9d1a-1b70-4d02-af5e-301f47030e30)

**Expected behavior**
Should download the sources with the correct destination path in my local project

**Environment:**
 - Ubuntu OS
 - crowdin-cli version 3.14

**Comment by fabianhelm** [comment]
I've tried it with all previous versions down to version 3.9.3 without success, so either something is configured wrong on my side or the download sources with differing `dest` is broken for quite some time already.

**Comment by andrii-bodnar** [comment]
@fabianhelm thanks a lot for reporting and investigating this!

**Comment by fabianhelm** [comment]
i just did some more research and I think it's related to the github integration, which is also active:

for a test-file which is outside the `crowdin` folder in my workspace, which is connected to github, it was working, but not for the files which are connected to github:

```
(py311) ➜  core git:(crowdin-download) ✗ ./webclient/node_modules/.bin/crowdin download sources
✔️  Fetching project info    
⚠️  No sources found for '/crowdin/webclient/messages.en.xlf' pattern. Check the source paths in your configuration file
⚠️  No sources found for '/crowdin/backend/django.po' pattern. Check the source paths in your configuration file
✔️  File 'crowdin-test/backend.en.po'
```

![image](https://github.com/crowdin/crowdin-cli/assets/109150546/ee0d2638-8094-4900-95f5-375059dda08e)

**Comment by fabianhelm** [comment]
I even removed the `dest` attribute of the files, but it still doesn't work for files, which are in the `crowdin` folder (=github sync)

![image](https://github.com/crowdin/crowdin-cli/assets/109150546/53183612-0ecb-4159-9939-e3283cbf30f9)

**Comment by andrii-bodnar** [comment]
@fabianhelm because your source files were uploaded using the native GitHub integration, they are located in the branch named  `crowdin`. 

In order to manage these sources and translations using the CLI, you need to add the `--branch <branch-name>` parameter to your commands. The yml configuration file is compatible with the GitHub integration and the Crowdin CLI. You don't need to specify the `crowdin` folder subpath in your patterns.

**Comment by fabianhelm** [comment]
@andrii-bodnar i'm actually uploading the sources with `crowdin upload sources` via the CLI to have full control over it.

also i've tried your suggestions with specifying the branch, and after adapting also the `dest` parameter it works now:

```
(py311) ➜  core git:(release) ./webclient/node_modules/.bin/crowdin download sources --branch crowdin 
✔️  Fetching project info    
✔️  File 'backend/django.po'
✔️  File 'webclient/messages.en.xlf'
```

thanks for your help, I'm closing the issue now!!
