### ISSUE TITLE
Add more Unit tests for the `Utils` class

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-cli#652]
The `Utils` class has some methods that are not covered by Unit tests. We should add more Unit tests for this class.

References:
- [Current tests coverage](https://app.codecov.io/gh/crowdin/crowdin-cli/blob/main/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fcli%2Futils%2FUtils.java)
- [`Utils.java`](https://github.com/crowdin/crowdin-cli/blob/main/src/main/java/com/crowdin/cli/utils/Utils.java)

**Comment by VAIBHAVCES** [comment]
@andrii-bodnar  Please assign this to me. I will cover up all the cases

**Comment by VAIBHAVCES** [comment]
Will send PR shortly !!

**Comment by Monoradioactivo** [comment]
I've created a PR for this issue https://github.com/crowdin/crowdin-cli/pull/655. Please review and provide feedback.
