### ISSUE TITLE
Add more Unit tests for the `FileUtils` class

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-cli#653]
The `FileUtils` class has some methods that are not covered by Unit tests. We should add more Unit tests for this class.

References:
- [Current tests coverage](https://app.codecov.io/gh/crowdin/crowdin-cli/blob/main/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fcli%2Futils%2Ffile%2FFileUtils.java)
- [`FileUtils.java`](https://github.com/crowdin/crowdin-cli/blob/main/src/main/java/com/crowdin/cli/utils/file/FileUtils.java)

**Comment by Sweetdevil144** [comment]
Hello @andrii-bodnar. Is the issue fixed yet?
--
If not, then I would like to work on it.

**Comment by andrii-bodnar** [comment]
Hi @Sweetdevil144, it's still available, assigning it to you, thanks!

**Comment by Sweetdevil144** [comment]
@andrii-bodnar Created a PR for the same !!
