### ISSUE TITLE
Add Unit tests for the Branch Action classes

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-cli#656]
**References:**

- [`BranchAddAction.java`](https://github.com/crowdin/crowdin-cli/blob/main/src/main/java/com/crowdin/cli/commands/actions/BranchAddAction.java) ([Tests coverge](https://app.codecov.io/gh/crowdin/crowdin-cli/blob/main/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fcli%2Fcommands%2Factions%2FBranchAddAction.java))
- [`BranchDeleteAction.java`](https://github.com/crowdin/crowdin-cli/blob/main/src/main/java/com/crowdin/cli/commands/actions/BranchDeleteAction.java) ([Tests coverage](https://app.codecov.io/gh/crowdin/crowdin-cli/blob/main/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fcli%2Fcommands%2Factions%2FBranchDeleteAction.java))

These classes have no code coverage. We should add Unit tests for it.

**Comment by subhashree9898** [comment]
@andrii-bodnar Please assign this issue to me!

**Comment by andrii-bodnar** [comment]
Hi @subhashree9898, do you have any updates on this?

**Comment by andrii-bodnar** [comment]
@MikeVarchola

**Comment by MikeVarchola** [comment]
> @MikeVarchola

@andrii-bodnar, nice. Please assign it to me, I will start working on it later this week, thanks :)

**Comment by andrii-bodnar** [comment]
@MikeVarchola any updates on this?
