### ISSUE TITLE
Add Unit tests for the `DistributionReleaseAction.java` class

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-cli#657]
**References:**

- [`DistributionReleaseAction.java`](https://github.com/crowdin/crowdin-cli/blob/main/src/main/java/com/crowdin/cli/commands/actions/DistributionReleaseAction.java)
- [`DistributionReleaseAction.java` coverage](https://app.codecov.io/gh/crowdin/crowdin-cli/blob/main/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fcli%2Fcommands%2Factions%2FDistributionReleaseAction.java)

This class has no coverage by Unit tests. We need to add more Unit tests to cover it.

**Comment by ayusheshan** [comment]
hi @andrii-bodnar , have raised a PR: https://github.com/crowdin/crowdin-cli/pull/662 for this issue. Please review it and let me know if there are any concerns!
