### ISSUE TITLE
Add Unit tests for the `ListLanguagesAction.java` class

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-cli#658]
**References:**

- [`ListLanguagesAction.java`](https://github.com/crowdin/crowdin-cli/blob/main/src/main/java/com/crowdin/cli/commands/actions/ListLanguagesAction.java)
- [`ListLanguagesAction.java` coverage](https://app.codecov.io/gh/crowdin/crowdin-cli/blob/main/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fcli%2Fcommands%2Factions%2FListLanguagesAction.java)

This class has no coverage by Unit tests. We need to add more Unit tests to cover it.

**Comment by Sweetdevil144** [comment]
Hey @andrii-bodnar. I can help you with this one too!!
