### ISSUE TITLE
Add Unit tests for the `PreTranslateAction.java` class

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-cli#659]
**References:**

- [`PreTranslateAction.java`](https://github.com/crowdin/crowdin-cli/blob/main/src/main/java/com/crowdin/cli/commands/actions/PreTranslateAction.java)
- [`PreTranslateAction.java` coverage](https://app.codecov.io/gh/crowdin/crowdin-cli/blob/main/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fcli%2Fcommands%2Factions%2FPreTranslateAction.java)

This class has no coverage by Unit tests. We need to add more Unit tests to cover it.

**Comment by itzk7** [comment]
@andrii-bodnar I will take a look

**Comment by Sweetdevil144** [comment]
Hey @andrii-bodnar . I'll fix this too.☺️

**Comment by Sweetdevil144** [comment]
I'm so sorry @andrii-bodnar . But, at the end, I still couldn't get a grip for these test cases.
Nice working with you. !!
