### ISSUE TITLE
Add Unit tests for the `CheckNewVersionAction.java` class

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-cli#665]
**References:**

- [`CheckNewVersionAction.java`](https://github.com/crowdin/crowdin-cli/blob/main/src/main/java/com/crowdin/cli/commands/actions/CheckNewVersionAction.java)
- [`CheckNewVersionAction.java` coverage](https://app.codecov.io/gh/crowdin/crowdin-cli/blob/main/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fcli%2Fcommands%2Factions%2FCheckNewVersionAction.java)

This class has no coverage by Unit tests. We need to add more Unit tests to cover it.

**Comment by kuv2707** [comment]
Hey Andrii!
Can you assign me this issue?

**Comment by andrii-bodnar** [comment]
@kuv2707 assigned, thank you!

**Comment by MikeVarchola** [comment]
@andrii-bodnar hello, do you have some similar issue for me ? Thanks :)

**Comment by andrii-bodnar** [comment]
Hi @MikeVarchola, yes, you can write unit tests for the following classes:

- [`BranchAddAction.java`](https://app.codecov.io/gh/crowdin/crowdin-cli/blob/main/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fcli%2Fcommands%2Factions%2FBranchAddAction.java)
- [`BranchDeleteAction.java`](https://app.codecov.io/gh/crowdin/crowdin-cli/blob/main/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fcli%2Fcommands%2Factions%2FBranchDeleteAction.java)

**Comment by kuv2707** [comment]
Hi @andrii-bodnar 
It appears that the CheckNewVersionAction class uses static methods (of Utils class etc) for its functionality.
So it cannot be mocked by plain Mockito- instead we would need to use PowerMockito.

**Comment by andrii-bodnar** [comment]
Hi @kuv2707, I think we can try using PowerMockito for this

but according to [this Stackoverflow answer](https://stackoverflow.com/a/62860455/7328018), it should be possible now even without PowerMockito

**Comment by MikeVarchola** [comment]
@andrii-bodnar  can you create an issue and assign it to me ? Thanks, I need it as part of submission of school project

**Comment by andrii-bodnar** [comment]
Hi @kuv2707, any updates on this?

**Comment by kuv2707** [comment]
I am on it. Got busy with other commitments.

**Comment by kuv2707** [comment]
@andrii-bodnar Upon much inspection and research, it seems that :
- It doesn't make sense to write a test for the getNewVersionMessage function as the test would involve copy-pasting the same code that generates the string and then making the redundant comparison.
- The getAppNewLatestVersion was private and hence could not be tested. So I removed the private access modifier.

The only crucial part (and a potential point of failure) that needs to be tested is fetching the new version data from the URL.
The test I have written does exactly that and is quite trivial.

I assume this was the reason this file was left out of testing in the first place.

I have made a pull request (#678)

**Comment by andrii-bodnar** [comment]
@kuv2707 thank you! The `getNewVersionMessage` method returns a formatted text like this:

![Screenshot 2023-10-27 at 17 27 09](https://github.com/crowdin/crowdin-cli/assets/29282228/0f1724d6-c4d6-4bd5-b773-e486ed91e190)

We can probably test this part as well, to make sure that this formatting is not broken.

What do you think?

**Comment by kuv2707** [comment]
I think doing that would be redundant as it is guaranteed that the formatting will not break. It is so because the only text that will ever change is the version number, and it will always be of the format ```0.00.0```

**Comment by andrii-bodnar** [comment]
@kuv2707 yes, it makes sense

**Comment by kuv2707** [comment]
@andrii-bodnar So is there anything else to be done on this issue?

**Comment by andrii-bodnar** [comment]
@kuv2707 I'll probably close the PR since it doesn't make much sense.

It tests the version number returned by an external URL. Every time a new version is released, we'll have to update this test as well.

In addition, this is the extra call to the URL on each test execution and as a result slower and more fragile unit tests.

Anyway, thanks a lot for your effort and contribution!
