### ISSUE TITLE
Failed to collect project info when running Github action

### ISSUE THREAD

**Issue by doct0r** [crowdin/crowdin-cli#668]
**Describe the bug**
When trying to sync localization data with the crowdin CLI in a GitHub action, it fails to get project information due to a serialization error.

**To Reproduce**
1. Configuration file: https://github.com/doct0r/LanguageApp/blob/main/crowdin.yml
2. See error in screenshot

**Expected behavior**
The CLI should be able to fetch project information correctly and synchronize localization data.

**Environment:**
 - OS:  Ubuntu
 - Version: 22.04

**Screenshots**
<img width="1325" alt="image" src="https://github.com/crowdin/crowdin-cli/assets/11046971/b1eb8d1f-a8da-4c48-af89-9dd128bb7df4">

**Additional context**
Here is a full log for a failed check run producing the error:
https://github.com/doct0r/LanguageApp/actions/runs/6548625503/job/17783716150

The repo is a random repo I cloned to test this integration as I'm evaluating Crowdin

**Comment by andrii-bodnar** [comment]
Hi @doct0r, is there any chance you have some unconfigured spreadsheet files in your Crowdin project?

**Comment by andrii-bodnar** [comment]
@doct0r also, I noticed that you're using a very old version of Crowdin GH Action. Please try updating to the `v1`:

```yml
uses: crowdin/github-action@v1
```

**Comment by doct0r** [comment]
Hey @andrii-bodnar this is what I was using for most of my runs and had the same issue, just tried out some things after I opened the bug. But I do have some spreadsheets in my project that I'm not really using, was just trying Crowdin features within the same project basically. Is that a problem when I'm defining what the sources are in my config file?

**Comment by andrii-bodnar** [comment]
@doct0r it shouldn't be a problem. Just try updating the GH Action version first

**Comment by doct0r** [comment]
The output that is linked to the original report is done with that version - you can ignore the current file. I will change it in the main branch so that the linked file is up to date

**Comment by andrii-bodnar** [comment]
@doct0r could you please provide your Crowdin project **ID**?

**Comment by doct0r** [comment]
@andrii-bodnar it's 597847

**Comment by andrii-bodnar** [comment]
@doct0r thank you. Please try removing the **unconfigured** **xlsx** file from your project or configure it

**Comment by doct0r** [comment]
Hi @andrii-bodnar, that worked, thank you! Not sure if that's something you see a lot but maybe would be useful to document somewhere? I was focusing on the code part while trying to get the integration to work and didn't even think to check at my Crowdin project.

**Comment by andrii-bodnar** [comment]
@doct0r glad to hear it's working now. We'll definitely look into this case more closely to avoid such issues in the future.
