### ISSUE TITLE
`skip_untranslated_strings` downloads empty keys

### ISSUE THREAD

**Issue by bennetgallein** [crowdin/crowdin-cli#683]
**Describe the bug**
As already mentioned in #428, #457 and #497 - I have empty strings which I do not want.

**To Reproduce**
Config: 
```
#
# Your Crowdin credentials
#
"project_id": "610495"
"api_token": "JWT",
"base_path": "."
"base_url": "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": false

#
# Files configuration
#
files: [
  {
    "source": "/_languages/en/*.json",
    "translation": "/_languages/%two_letters_code%/%original_file_name%",
    "skip_untranslated_strings": true,
    "export_only_approved": true
  }
]
```

**Expected behavior**
`skip_untranslated_strings` should not return them as empty strings but just remove them completly.

**Environment:**
 - OS: Debian
 - Version 12

**Screenshots**

**Additional context**
[Link to project](https://crowdin.com/project/bennetgalleinde-proxmoxcp)

**Comment by andrii-bodnar** [comment]
Hi @bennetgallein, we have enabled a special post-processor for your project that will remove the empty strings from the files during the export. Could you please check if it's working now?

**Comment by bennetgallein** [comment]
It is working now, thank you. 

None the less I would consider this to be a valuable feature for others as well :)

**Comment by andrii-bodnar** [comment]
@bennetgallein great, thanks for confirmation!

> None the less I would consider this to be a valuable feature for others as well :)

We will definitely provide a better way to configure this behavior in the future.

**Comment by hugotiger** [comment]
> We will definitely provide a better way to configure this behavior in the future.

Has any work been done to be able to configure this? I'm having the same problem.

**Comment by andrii-bodnar** [comment]
Hi @hugotiger, currently it's possible by using the [Custom Pre-Export Processor](https://store.crowdin.com/custom-pre-export-processor).

**Comment by jimmydjabali** [comment]
Hello @andrii-bodnar, how exactly it is possible using this module ?
After trying many different ways in JS, deleting the `[languageId]` object inside of `translations` (according to your [string array structure documentation](https://support.crowdin.com/developer/crowdin-apps-module-file-post-import-processing/#strings-array-structure)), strings are still being exported either as empty strings `""`, or with the default (English) values.

Can you provide an exemple script ?

Thanks a lot

**Comment by andrii-bodnar** [comment]
@jimmydjabali, could you please provide a sample file?

It looks like you’re referring to the **File Post-Import** module, but in this case, the **Pre-Export module** is required.

By the way, we've trained our own GPT to help users receive custom code for the app based on their requirements: [Crowdin File Processors Developer
](https://chat.openai.com/g/g-8FG4IgXyr-crowdin-file-processors)
