### ISSUE TITLE
Change in the directory structure of the crowdin-cli.zip archive in 3.16.0?

### ISSUE THREAD

**Issue by hwhsu1231** [crowdin/crowdin-cli#701]
### Problem Description

Hello, crowdin-cli Development Team.

I've noticed that in the latest release, version 3.16.0, there has been a change in the directory structure of the crowdin-cli.zip archive.

This is the archive's directory structure of 3.16.0:

```
crowdin-cli/
    crowdin
    crowdin.bat
    crowdin-cli.jar
    crowdin_completion
    install-crowdin-cli.sh
    README.txt
    setup_crowdin.bat
```

This is the archive's directory structure of below 3.15.0:

```
3.X.Y/
    crowdin
    crowdin.bat
    crowdin-cli.jar
    crowdin_completion
    install-crowdin-cli.sh
    README.txt
    setup_crowdin.bat
```

Is this a mistake, or is it intended that from version 3.16.0 onwards, the archives are structured this way?

### Screenshots

![image](https://github.com/crowdin/crowdin-cli/assets/71438617/494ae8b8-93c8-4b31-b481-c8dd1f06d5b7)

**Comment by andrii-bodnar** [comment]
Hi @hwhsu1231, thanks for pointing this out!

Already fixed it for the latest release.
