### ISSUE TITLE
Installation on Windows errors with Java 21

### ISSUE THREAD

**Issue by lifehackerhansol** [crowdin/crowdin-cli#706]
**Describe the bug**
As title says, I have a laptop with Windows 10 and Java 21 installed.

```
java --version
openjdk version "21" 2023-09-19 LTS
OpenJDK Runtime Environment Microsoft-8425986 (build 21+35-LTS)
OpenJDK 64-Bit Server VM Microsoft-8425986 (build 21+35-LTS, mixed mode, sharing)
```

This causes it to error out:
```
Checking JAVA version
1은(는) 예상되지 않았습니다. (translates to "1 was not expected.")
```

**To Reproduce**

0. Install Java 21. I'm using Microsoft's builds: https://learn.microsoft.com/en-us/java/openjdk/download
1. Execute CLI command: setup_crowdin.bat
2. See an error

**Expected behavior**

There should be no error. The crowdin-cli webpage says Java 8 or later, so Java 21 should be working.

**Environment:**
 - OS: Windows
 - Version: 10.0.19045.3930
 - Crowdin-CLI package version 3.16.0

**Comment by lifehackerhansol** [comment]
The title of the issue was incorrect: the script appears to have finished doing its job by that point, based on what I read in the batch file, so the error is a no-op. Still, the error shouldn't be there.

**Comment by andrii-bodnar** [comment]
Script reference - https://github.com/crowdin/crowdin-cli/blob/main/packages/zip/setup_crowdin.bat

**Comment by andrii-bodnar** [comment]
Will be available in the v4 release.
