### ISSUE TITLE
Can the indentation of 'crowdin status' command's outputs uses Spaces instead of Tabs?

### ISSUE THREAD

**Issue by hwhsu1231** [crowdin/crowdin-cli#710]
**Is your feature request related to a problem? Please describe.**

I want to write outputs of `crowdin status` command into a commit message created by GitHub Workflows. However, I noticed that the indentation it uses is Tabs instead of Spaces. That way, the size of indentation may change and looks strange.

**Describe the solution you'd like**

Make the indentation of `crowdin status` command's output to Spaces instead of Tabs. (0 space, 2 spaces, and 4 spaces are recommended)

**Describe alternatives you've considered**

Alternatively, maybe crowdin-cli can provide a parameter/option for `crowdin status` command to let use _choose whether to use Spaces or Tabs_. Even, maybe crowdin-cli can provide a parameter/option to let us _decide the size/number of Spaces Indentation_.

**Additional context**

crowdin-cli version: 3.16.1

![image](https://github.com/crowdin/crowdin-cli/assets/71438617/0c12f162-e166-49d1-98cf-f3e419a5dd91)

**Comment by andrii-bodnar** [comment]
I think it would be better to replace the tab with two spaces. There are other places in the CLI with similar formatting, we should make the appropriate changes there as well.

**Comment by andrii-bodnar** [comment]
This may break the existing integrations, let's do it later.
