### ISSUE TITLE
Suppress the available update message when using crowdin-cli

### ISSUE THREAD

**Issue by hwhsu1231** [crowdin/crowdin-cli#717]
**Is your feature request related to a problem? Please describe.**

I want to write the outputs of `crowdin status` into a commit message in a GitHub Workflow. However, I found that if there's an available update for crowdin-cli, there will be an available update message showed up, which is what I want to exclude from my commit message.

```cmd
D:\Test\test-crowdin-readme>crowdin status --branch test
[OK] Fetching project info
Translated:
        - zh-CN: 0%
        - zh-TW: 0%
Approved:
        - zh-CN: 0%
        - zh-TW: 0%

┌──────────────────────────────────────────────────────────────────────────────┐
│          New version of Crowdin CLI is available! 3.16.1 -> 3.17.0           │
├──────────────────────────────────────────────────────────────────────────────┤
│      Changelog: https://github.com/crowdin/crowdin-cli/releases/latest       │
│                    Please update for the best experience!                    │
└──────────────────────────────────────────────────────────────────────────────┘

D:\Test\test-crowdin-readme>
```

All I want is the following contents:

```
Translated:
        - zh-CN: 0%
        - zh-TW: 0%
Approved:
        - zh-CN: 0%
        - zh-TW: 0%
```

**Describe the solution you'd like**

There are 2 solutions that I suggest to solve this issue:

1. Still show the available update message by default, but add an option (e.g. `--no-update`) to suppress it.
2. Redirect the available update message to `stderr` as warning message.

**Describe alternatives you've considered**

In my opinion, the 1st solution is better than the 2nd one.

**Additional context**

crowdin-cli version: 3.16.1

**Comment by andrii-bodnar** [comment]
I would suggest adding the `--plain` parameter to the `status`, `status translation`, and `status proofreading` commands. We already have this parameter for most CLI commands.

**Comment by hwhsu1231** [comment]
> I would suggest adding the `--plain` parameter to the `status`, `status translation`, and `status proofreading` commands. We already have this parameter for most CLI commands.

@andrii-bodnar That's it! I tested [`crowdin label list`](https://crowdin.github.io/crowdin-cli/commands/crowdin-label-list) with `--plain` parameter, and found that this is what I want.

```cmd
D:\Test\test-crowdin-readme>crowdin label list
[OK] No labels found

┌──────────────────────────────────────────────────────────────────────────────┐
│          New version of Crowdin CLI is available! 3.16.1 -> 3.17.0           │
├──────────────────────────────────────────────────────────────────────────────┤
│      Changelog: https://github.com/crowdin/crowdin-cli/releases/latest       │
│                    Please update for the best experience!                    │
└──────────────────────────────────────────────────────────────────────────────┘

D:\Test\test-crowdin-readme>crowdin label list --plain
No labels found

D:\Test\test-crowdin-readme>
```

**Comment by andrii-bodnar** [comment]
@hwhsu1231 would you like to create a PR? It should be easy

**Comment by hwhsu1231** [comment]
Sorry. I'm actually not familiar with Java development, currently.

**Comment by andrii-bodnar** [comment]
Will be available in the v4 release.
