### ISSUE TITLE
crowdin download --all do not work

### ISSUE THREAD

**Issue by olegakbarov** [crowdin/crowdin-cli#726]
**Describe the bug**

``` 
crowdin download --all  
✔️  Fetching project info     
❌ Cannot invoke "java.util.List.stream()" because "this.directories" is null
``` 

**To Reproduce**
1. Configuration file: '...'
```
...
files: [
    {
      'source': 'public/i18n/en-US.json',
      'translation': 'public/i18n/%locale%.json'
      }
]
```
3. Execute CLI command: `crowdin download --all  `
4. See an error

**Expected behavior**
I would expect to have translation files to be dowloaded

**Environment:**
 - OS: MacOS
 - 14.3.1
 - CLI version 3.18.0

**Comment by andrii-bodnar** [comment]
@olegakbarov could you please specify what type of project you use in Crowdin: file-based or string-based?

**Comment by olegakbarov** [comment]
String based. Solved the problem by creating file-based.
