### ISSUE TITLE
Provide a command to analyze whether the sources to be uploaded comply with the syntax

### ISSUE THREAD

**Issue by hwhsu1231** [crowdin/crowdin-cli#732]
**Is your feature request related to a problem? Please describe.**

Suppose my GitHub Actions workflow automatically executes an `crowdin upload` whenever there's an update to any `*.md` file. However, if the edited `*.md` file includes content that does not comply with the proper syntax, an error similar to the following occurs:

```bash
❌ File 'README.md'
❌ Wrong parameters: 
<key: storageId, code: fileInvalid, message: An unknown error occurred while importing the file.>
❌ Current execution finished with errors
```

This situation is quite troubling. It would be much more convenient if crowdin-cli could provide a command to check whether the sources to be uploaded comply with the syntax.

**Describe the solution you'd like**

Provide a command (ex `crowdin parse`) to analyze whether the sources to be uploaded in `crowdin.yml` comply with the syntax.

**Describe alternatives you've considered**

I noticed that there's a [`crowdin lint`](https://crowdin.github.io/crowdin-cli/commands/crowdin-lint) command, which is used to **analyze your configuration file for possible errors**. Maybe crowdin-cli can extend its function to not just analyze the configuration file (`crowdin.yml`) but also the sources.

**Additional context**

crowdin-cli version: `v3.18.0`

**Comment by andrii-bodnar** [comment]
Thanks for the request, there are too many file formats to provide such checks on the CLI side. I'm afraid it's not feasible to validate that the file syntax is correct before uploading.

**Comment by laurent22** [comment]
We have a file also that gives us this error "`<key: storageId, code: fileInvalid, message: An unknown error occurred while importing the file.>`". What does that even mean? Is it possible to know what part of the file is causing a problem?

**Comment by andrii-bodnar** [comment]
@laurent22 it depends on the file format, there is no automated way to detect the cause of the problem. Is it reproducible via UI as well?

**Comment by laurent22** [comment]
@andrii-bodnar, thank you for your reply.

Yes same error on the UI:

<img width="433" alt="image" src="https://github.com/crowdin/crowdin-cli/assets/1285584/2594339e-a558-4f49-a7ed-bb2727a49f48">

Presumably the parser you're using would tell you what particular line and character is causing an issue - any reason this is not exposed? Is the parser you're using open source by any chance? In which case I could try with this, and fix the Markdown file.

The problem file is this one:

https://raw.githubusercontent.com/laurent22/joplin/dev/readme/apps/drawing_tool.md

It's valid Markdown, other than maybe the `:::note` tags, but even after removing this it still doesn't work.

**Comment by andrii-bodnar** [comment]
@laurent22 Thanks for the details. This is a parser issue. Could you please [contact](https://crowdin.com/contacts) our customer success team with these details? They will pass it directly to the dev team to investigate in more detail. Thank you very much!

**Comment by laurent22** [comment]
Thanks @andrii-bodnar, I have now sent them an email.
