### ISSUE TITLE
Error code 15 when trying to upload iOS Localizable.strings

### ISSUE THREAD

**Issue by soberman** [crowdin/crowdin-cli#74]
Hi!

I am trying to upload my localization files for an iOS project. Upload of the file structure goes correctly, I can see corresponding folders persisted, however as soon as Crowdin tries to upload `Localizable.strings` file I get this error in my console (I am using Crowdin CLI version is 2.0.22):
```
$ crowdin upload --identity ./crowdin.credentials.yml
Directory 'MyAppName' - OK
Directory 'MyAppName/Localization' - OK
Directory 'MyAppName/Localization/en.lproj' - OK
File 'MyAppName/Localization/en.lproj/Localizable.strings' - ERROR
code : 15
message : Invalid file type
```

What am I doing wrong? Could you help me out please?
Here is how my configuration file looks like (it passes the `lint` command successfully):
```
"project_identifier" : "MyProjectName"
"base_path" : "."
"preserve_hierarchy": true

files: [
 {
  "source" : "/MyAppName/Localization/en.lproj/Localizable.strings",
  "translation" : "/MyAppName/Localization/%osx_code%/%original_file_name%",
  "type" : "strings",
  "languages_mapping" : {
   "two_letters_code" : {
     "no" : "nb"
    }
  },
 }
]
```

**Comment by crowdin** [comment]
-- Please reply above this line --


Hello, 

Could you tell us your project name so we can investigate it more
thoroughly?

Looking forward to your reply.


How would you rate my reply?
Great [1]    Okay [2]    Not Good [3]

--
Sincerely,
Mariana Diediukh
Customer Success Manager

Links:
------
[1]
https://secure.helpscout.net/satisfaction/173474414/record/1481066979/1/
[2]
https://secure.helpscout.net/satisfaction/173474414/record/1481066979/2/
[3]
https://secure.helpscout.net/satisfaction/173474414/record/1481066979/3/

**Comment by soberman** [comment]
24onoff

**Comment by crowdin** [comment]
-- Please reply above this line --


Thank you, 

Once we find a reason, we'll immediately let you know.


How would you rate my reply?
Great [1]    Okay [2]    Not Good [3]

--
Sincerely,
Mariana Diediukh
Customer Success Manager

Links:
------
[1]
https://secure.helpscout.net/satisfaction/173500562/record/1481098230/1/
[2]
https://secure.helpscout.net/satisfaction/173500562/record/1481098230/2/
[3]
https://secure.helpscout.net/satisfaction/173500562/record/1481098230/3/

**Comment by yavorysynka** [comment]
Hi again!

I guess I found the reason for the error. :)

Could you please try this configuration?

```
"project_identifier" : "MyProjectName"
"base_path" : "."
"preserve_hierarchy": true

files: [
 {
  "source" : "/MyAppName/Localization/en.lproj/Localizable.strings",
  "translation" : "/MyAppName/Localization/%osx_code%/%original_file_name%",
  "type" : "macosx",
  "languages_mapping" : {
   "two_letters_code" : {
     "no" : "nb"
    }
  },
 }
]
```
Just replace ```"type" : "strings",``` with ```"type" : "macosx",``` since this particular value is meant for .strings files. Here is a quick guide: [Add file](https://support.crowdin.com/api/add-file/)

It should help!

**Comment by soberman** [comment]
Hi @yavorysynka!

Thanks, that did the trick! However I can see that only english localization has been uploaded. I have Norwegian and Polish as well. Do I have to include something more in the `.yml` file? Or I have to make translations on the website and then I will be able to get those localizations for those two languages as well?

**Comment by yavorysynka** [comment]
Hi @soberman!

>Or I have to make translations on the website and then I will be able to get those localizations for those two languages as well?

Exactly :) When you make translations for Polish and Norwegian, it will be downloaded to your computer\machine this way: /MyAppName/Localization/%osx_code%/%original_file_name%
