### ISSUE TITLE
Autodetect current branch

### ISSUE THREAD

**Issue by AlexWayfer** [crowdin/crowdin-cli#75]
Hello!

Why CLI tool doesn't apply current branch automatically?

It can try to detect VCS type and get the current branch.

For example, `git branch | grep -e "^*" | cut -d' ' -f 2`.

**Comment by Andrulko** [comment]
@ihor-popyk, can you please check?

@AlexWayfer, did you try our GitHub / Bitbucket / GitLab sync? It should make things even easier

**Comment by AlexWayfer** [comment]
> @AlexWayfer, did you try our GitHub / Bitbucket / GitLab sync? It should make things even easier

Yes, I saw it. But I'm not sure that I want Crowdin servers pull all of our project code, not only translation files. :grimacing:

**Comment by AlexWayfer** [comment]
> We pull only those files you specify during configuration, no need to upload everything of course. There will be crowdin.yml file created in your repository, it has the same configuration as CLI but here you need to specify only files section, no need to specify your project credentials!

But how Crowdin servers will get `crowdin.yml` and localization files without `git clone/pull`?

> Also you may have a separate repo where only files for localization are being hosted, nothing else. It's very common approach right now

And use git submodules? I'm not sure that this is a good idea. Also, what should I do with project branches (about which I wrote) in this case? Create two branches with the same name in two repositories? Oh, come on.

**Comment by ihor-popyk** [comment]
@Andrulko @AlexWayfer 
I am going to implement this feature.
Thanks for suggestion.
