### ISSUE TITLE
Use nonzero exit codes when an error happens

### ISSUE THREAD

**Issue by jleclanche** [crowdin/crowdin-cli#77]
I've been having a lot of trouble catching errors related to crowdin-cli in CI because whenever there's an error and it exits, it always uses exit code 0 (success).

For example, `crowdin --config does_not_exist.yml upload sources && echo "Success!"` will in fact print success.

**Comment by v3ctorman** [comment]
Hello @jleclanche !
Thanks for pointing the issue. We'll recheck the behavior with the dev team and reverе to you in short run
