### ISSUE TITLE
Do not show a progress bar when the output is piped (not a terminal)

### ISSUE THREAD

**Issue by jleclanche** [crowdin/crowdin-cli#78]
Otherwise it gets weird in CI systems:

![image](https://user-images.githubusercontent.com/235410/39672213-54353a6e-512e-11e8-88a5-8b2c63c7ad11.png)

**Comment by v3ctorman** [comment]
@jleclanche thanks! The task on the issue is created, we will investigate and try to fix this glitch.

**Comment by andrii-bodnar** [comment]
Fixed in [CLI 3](https://github.com/crowdin/crowdin-cli-2/tree/cli3#readme). Try to use `--no-progress` option.
