### ISSUE TITLE
Not working on Macbook m3

### ISSUE THREAD

**Issue by LevDavydovSolidgate** [crowdin/crowdin-cli#792]
**Describe the bug**
Crowdin cli fails with wrong java version (non-ARM) on Macbook M3

**To Reproduce**
1. UseMacbook Pro M3
2. Install crowdin-cli via npm 
3. Run `crowdin push`
3. See an error

```
Downloading java runtime environment for version 11
/bin/sh: /Users/#MASKED/.jdeploy/jre/11/jre/zulu11.72.19-ca-jre11.0.23-macosx_x64/zulu-11.jre/Contents/Home/bin/java: Bad CPU type in executable
```

**Expected behavior**
Sources pushed to crowdin platofrm

**Environment:**
 - OS: Mac OS Sonoma
 - Version 14.5

**Comment by andrii-bodnar** [comment]
Probably not related to the CLI itself, but more of a jDeploy or shelljs issue.

Also, found similar issue - https://stackoverflow.com/questions/76808648/bad-cpu-type-in-executable-error-pop-up-when-run-flutter-commands

**Comment by SarmanAulakh** [comment]
had the same issue on my new m3. run the following command in ur terminal to instal rosetta 2: `softwareupdate --install-rosetta`. then it should work fine
