### ISSUE TITLE
Is there a way to prevent updating po files if the translations all match?

### ISSUE THREAD

**Issue by jleclanche** [crowdin/crowdin-cli#81]
I have a workflow that involves auto-committing to a repository with the updated files from crowdin.

But po files always get updated with a `PO-Revision-Date`, even if they *didn't* get updated:

https://github.com/HearthSim/hsreplaynet-i18n/commit/05dd4d07431a446bb84a6dbac1f0de4354b77daa

So two questions:

1. Is there a way not to update po files if only the po-revision-date changed?
2. Why did the po-revision-date change in the first place if no translations were updated? That seems like a bug

**Comment by Andrulko** [comment]
We already have such improvement on our roadmap, so update won't be performed if only `PO-Revision-Date` was modified. It might be released even in a few days, so both questions of yours will be resolved 😄

**Comment by jleclanche** [comment]
That's great to hear! Would be great if you can ping this issue once released :)

**Comment by Andrulko** [comment]
Definitely, we're also eager to see this issue as closed :)

**Comment by crowdin** [comment]
Everything works just great for a while, closing the issue
