### ISSUE TITLE
crowdin download sources results in "No sources found for '*.strings' pattern

### ISSUE THREAD

**Issue by jkbullard** [crowdin/crowdin-cli#821]
**First, thanks to everyone working on Crowdin CLI** (I'm using version 4.0.0). Your work is much appreciated.

**Describe the bug**
Error message "No sources found for '*.strings' pattern" when trying to download the source file.

**To Reproduce**
1. Configuration file:
```
"project_id": "*****"
"api_token": "*****"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
files: [
  {
    "source": "*.strings",
    "translation": "/StringsFiles/%two_letters_code%.lproj/%original_file_name%",
  }
]
```
2. File hierarchy:
```
   ~/Crowdin
   |
   -- crowdin.yml
   -- Localizable.strings        <-- This is the source file
   -- StringsFiles
      |
      -- en.lproj
         |
         -- Localizable.strings  <-- This is the file with English translations
      -- es.lproj
         |
         -- Localizable.strings. <-- This is the file with Spanish translations
      -- de.lproj
         |
         -- Localizable.strings. <-- This is the file with German translations
```
3. Execute CLI command:
```
cd ~/Crowdin
crowdin download sources --dryrun
```
4. See an error:
```
No sources found for '*.strings' pattern. Check the source paths in your configuration file
```

And the source file does not appear to have changed.

**Expected behavior**
No error, and the source file at Crowdin/Localizable.strings updated from the Crowdin website.

**Environment:**
 - OS: macOS 14.5
 - Crowdin CLI version 4.0.0

**Screenshots**
(Not applicable.)

**Additional context**
I'm trying to replace home-grown scripts that use the v1 API that Crowdin has discontinued.

I actually don't want to download the source file, I want to upload it, but I want to get downloading working first since that doesn't risk disturbing the existing Crowdin data.

My project has a single English source file, Localizable.strings, which was uploaded using the Crowdin website ten years ago and has been updated periodically using the v1 API.

I set up the file hierarchy as described above because:
 * When I download the source using the Crowdin website, it downloads a single file named "Localizable.strings".
 * When I download translations using the Crowdin website, it downloads a .zip that expands into a folder named "StringsFiles" which contains a subfolder for each language ("de", "en", "es"). Each subfolder contains a "Localizable.strings" file.

I've tried a few things, such as:
 * Changing the "source" setting from `"*.strings"` to `"/*.strings"`, `"Localizable.strings"`, and `"/Localizable.strings"`
 * Setting "preserve_hierarchy" to false

I don't want to upload the source file (as suggested for similar problems with translations) because don't want to cause problems with the existing translations on Crowdin. (I've tried using the API to upload the source file; that resulted in missing strings and other problems, which is why I'm trying to use the Crowdin CLI.)

Thanks in advance!

**Comment by andrii-bodnar** [comment]
Hi @jkbullard, glad to hear you are using CLI v4!

Please have a look at this FAQ section - https://crowdin.github.io/crowdin-cli/faq#no-sources-found-for-pattern

Most likely this is the "Resulting file after translations export" issue and setting the `translation` pattern value there should help.

**Comment by jkbullard** [comment]
Thanks, @andrii-bodnar. I had looked at the FAQ section, but don't understand how it applies to my situation. Isn't the yaml "source" setting a pattern to show:
 * When uploading, where the source file(s) are, relative to the folder the yaml is in, and
 * When downloading, where the source files from Crowdin should be placed (again, relative to the yaml file)?

What does the "translation" setting have to do with that?

But, OK, assuming that the "translation" setting tells where to put the downloaded _source_ file, I tried `"source": "*.strings"` with `"translation": "Localizable.strings"`. That results in a complaint that the "'translation' parameter should contain at least one language placeholder…".

So I moved the source file into a folder named "source.en.lproj", and, with `"source": "source.en.lproj/*.strings"` and `"translation": "source.%two_letters_code%.lproj/%original_file_name%"`, I get "No sources found…".

(I also tried several other variations, but all have the same result.)

The "No sources found…" message seems to say that no source files were found _on Crowdin_.
 * If that's true, is the problem that Crowdin is storing the source file somewhere other than at the root of some file hierarchy for my project, and because I'm not specifying that, CLI isn't looking in the right place? Or that what CLI downloaded isn't a file named "Localizable.strings"? How can I find out where and under what name Crowdin is storing the source file so I can specify that?
 * If that's false, and the source file was downloaded from Crowdin, but is in an archive's subfolder or isn't named "Localizable.strings", that's a different problem. **How do I find out what (if anything) the CLI downloaded from Crowdin?** That is, I can make my file hierarchy and names match whatever Crowdin has, but how do I find out what Crowdin has? (I tried `crowdin download sources --debug --dryrun` but didn't get any additional output.)

Also, can you clarify what a leading "/" character does (if anything) in the "source" and "translation" settings? I've seen examples with and without one, so I've been trying each setting change four times – with and without leading a "/" in each of "source" and "translation", and am getting tired of that  : ) (And sometimes Crowdin rate limits me, even though I'm doing it all manually!)

**Comment by andrii-bodnar** [comment]
@jkbullard the leading slash shouldn't affect anything in the download process.

I just tried your configuration and everything works as expected for me. The `Localizable.strings` file is located at the root of my Crowdin project.

**Comment by jkbullard** [comment]
OK, thanks @andrii-bodnar.

I guess the problem is the way the source file is stored on Crowdin: I can't find any combination of `source` and `translation` that lets me download Crowdin's copy of my source file with the CLI. That's reinforced by the comment in the FAQ that uploading the source might cure the problem -- implying that using the CLI to upload the source will tell Crowdin to store the source in a different folder or under a different name than it is stored currently and that subsequent downloading with the CLI will successfully use that different folder and/or name.

**Comment by andrii-bodnar** [comment]
@jkbullard there is another way to manage files - by using the [`crowdin file`](https://crowdin.github.io/crowdin-cli/commands/crowdin-file) command. It's more lightweight and doesn't include that complicated logic as the `crowdin download` command.

See the [File Management](https://crowdin.github.io/crowdin-cli/blog/2024/01/23/files-management) article for more details.

**Comment by jkbullard** [comment]
`crowdin file` works perfectly, especially for my decidedly non-complicated requirements. I'm embarrassed that I didn't notice that possibility. Thank you very much, @andrii-bodnar.
