### ISSUE TITLE
Typo in constant "COMMAND_DOWNLAOD(_*)"

### ISSUE THREAD

**Issue by Zarthus** [crowdin/crowdin-cli#83]
https://github.com/crowdin/crowdin-cli-2/blob/4a0475a795c5d90a76b8ad5b6b8d25b9a13756ae/src/main/java/com/crowdin/cli/commands/CrowdinCliCommands.java#L26-L28

Should be DOWNLOAD.

**Comment by andrii-bodnar** [comment]
Hi @Zarthus !
This issue is fixed in [CLI 3](https://github.com/crowdin/crowdin-cli-2/tree/cli3#readme)
