### ISSUE TITLE
Ability to run pre-translate for whole project

### ISSUE THREAD

**Issue by whitipet** [crowdin/crowdin-cli#830]
When I call pre-translate, I need to specify either --file --directory. I have not found a way to specify all files at once, or the root folder.
`crowdin pre-translate --method tm --translate-with-perfect-match-only --translate-untranslated-only`
`✔️  Fetching project info`
`❌ The '--file' or '--directory' parameter is required for this type of project`

A possible solution is to add `*` for --directory, or `all` for --file as possible values

**Comment by andrii-bodnar** [comment]
Thanks for the suggestion!

I think we can add `all` as a possible value for the `--file` parameter. It should also consider the `--branch` parameter and pre-translate all the files from the specified branch only.

It shouldn't be a default value but should be specified explicitly.

---

**UPD**: We've decided to simply allow the `pre-translate` command to be run without the `--file` or `--directory` parameters. In this case, it will pre-translate the whole project by default.

**Comment by whitipet** [comment]
Great, that will help a lot
