### ISSUE TITLE
Options not working

### ISSUE THREAD

**Issue by mrexodia** [crowdin/crowdin-cli#833]
**Describe the bug**

When doing `java -jar crowdin-cli.jar --help` it says there are `--no-progress` and `--no-colors` options, but these options are silently ignored if placed at the wrong place on the command line.

**To Reproduce**

```sh
java -jar crowdin-cli.jar --no-progress --no-colors upload sources
```

This will show progress and colors.

**Expected behavior**

I would expect it to do one of two things:

1. Not show progress and colors (preferred)
2. Hard error that the options are in the wrong spot

**Environment:**
 - OS: Windows
 - Version x64 10 LTSC

**Screenshots**

**Additional context**

Just wanted to clarify that it works correctly with the following command. This issue is just a user experience problem, not a 'bug' per-se.

```
java -jar crowdin-cli.jar upload sources --no-progress --no-colors
```

**Comment by andrii-bodnar** [comment]
We use [Picocli](https://picocli.info/) for the CLI experience. The issue is probably more related to Picocli, not Crowdin CLI itself.

**Comment by andrii-bodnar** [comment]
The SYNOPSIS:

```
crowdin [SUBCOMMAND] [OPTIONS]
```

So there is a strict requirement about the order of the commands and options.

**Comment by mrexodia** [comment]
That's nice and all, but this is the end-user experience for **your** tool. I understand it's tempting to push this off as someone else's problem or call it user error, but this issue has been extremely frustrating to debug for me. I only used the new CLI because you forced me to, and I'm reporting a user experience problem that anyone could run in to.

**Comment by andrii-bodnar** [comment]
@mrexodia I understand, thanks for reporting this anyway!

**Comment by mrexodia** [comment]
Another issue is that the behavior is inconsistent. If I do

```
java -jar crowdin-cli.jar --badoption
```

It throws an error, but `--no-progress` at the same spot silently does nothing...

**Comment by andrii-bodnar** [comment]
Do you mean `java -jar crowdin-cli.jar --no-progress`?

**Comment by mrexodia** [comment]
I mean that the following invalid command errors:

```
java -jar crowdin-cli.jar --invalid status
Unknown option: '--invalid'

SYNOPSIS:
crowdin [SUBCOMMAND] [OPTIONS]

DESCRIPTION:
Crowdin CLI is a command-line tool that allows you to manage and synchronize localization resources with your Crowdin
project.
Visit the official documentation for more details: https://crowdin.github.io/crowdin-cli
```

But the equally invalid command does not:

```
java -jar crowdin-cli.jar --no-progress status
```

Anyway, I opened #834 that fixes my issue. I do agree that this is a bug in picocli, but I don't know Java so it will be tough to construct a minimal test case for them to fix it properly.
