### ISSUE TITLE
download translations: export options improvement

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-cli#841]
**Is your feature request related to a problem? Please describe.**

The [`crowdin download translations`](https://crowdin.github.io/crowdin-cli/commands/crowdin-download-translations) command supports the following options to control the export of translations:

- `--skip-untranslated-strings`
- `--skip-untranslated-files`
- `--export-only-approved`

Currently, it's only possible to set "true" values for these parameters. So it's not possible to explicitly set the "false" values for the `skipUntranslatedStrings`, `skipUntranslatedFiles`, and `exportApprovedOnly` [API](https://support.crowdin.com/developer/api/v2/#tag/Translations/operation/api.projects.translations.builds.post) parameters. 

**Describe the solution you'd like**

Make all the three options [negatable](https://picocli.info/#_negatable_options).

- `--[no-]skip-untranslated-strings`
- `--[no-]skip-untranslated-files`
- `--[no-]export-only-approved`

This way, it will be possible to explicitly pass the "false" value. This will allow to override the default project export options.

**Comment by nottrif** [comment]
I would like to work on this.

**Comment by nottrif** [comment]
@andrii-bodnar why is it not possible to set false values those parameters currently?

**Comment by nottrif** [comment]
I'm unavailable to push changes to the branch that I created.
This is the error that I'm getting, seems like an access issue to publish changes. Can you please check?
Error:
16:18:37.724: [crowdin-cli] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/fix/set-negatable-true:refs/heads/fix/set-negatable-true --set-upstream
remote: Permission to crowdin/crowdin-cli.git denied to nottrif.
fatal: unable to access 'https://github.com/crowdin/crowdin-cli.git/': The requested URL returned error: 403

**Comment by nottrif** [comment]
> This way, it will be possible to explicitly pass the "false" value. This will allow to override the default project export options.

Also, I want to clarify that by making those options negatable we can pass a false value by using (for ex.) --no-skip-untranslated-files=true?

**Comment by andrii-bodnar** [comment]
@nottrif thank you for digging into this!

I just double-checked everything and it appears that it is currently **possible** to pass the `false` value in the following way: `crowdin pull --skip-untranslated-strings=false`.

So there is no need to make these export options negatable and the issue could be closed.
