### ISSUE TITLE
.NET resx files, variables name changed

### ISSUE THREAD

**Issue by skini82** [crowdin/crowdin-cli#85]
Hello, I have an issue on .resx files when downloading translations:
I have a variable called like "ServiceStatus_Active.Text", but when downloading translations through CLI, i found in the same file the correct translation, but the variable name changed from "ServiceStatus_Active.Text" to "ServiceStatus_Active".
Obviously this thing is compromising my website translation.
Is it a bug or something I have to fix in settings?

Thank you.

PS: my CLI version is 2.0.22

**Comment by yavorysynka** [comment]
Hello!

Could you please tell me your project name?

I will check everything in our database :)

**Comment by skini82** [comment]
the project is official-cloudcontrolpanel15be

**Comment by yavorysynka** [comment]
Thanks!

So here is what I figured out: 

ServiceStatus_Active.Text is a source string key (unique identifier) and it is also displayed as context information in the [Editor](https://crowdin.com/translate/official-cloudcontrolpanel15be/16688/it-en#q=ServiceStatus_Active.Text)

The thing is that a colleague of yours changed the initial string context from "MonitoringServiceStatus_Active " to "MonitoringServiceStatus_Active.Text " but this change is meant to be reflected only on Crowdin and it does not change the real source string key inside the source file.

Hope it makes sense :)

**Comment by skini82** [comment]
Hello, unfortunately it makes not sense, because in our source file, checking the older version before the crowdin update, the source have correct key names ("MonitoringServiceStatus_Active.Text"), the same names as in crowdin (and to be more specific: the name is the same in the main file .resx and in all translated files .cs.resx, .en.resx and so on). 
After the update from crowdin, the CLI changed the key name in the translated file ("MonitoringServiceStatus_Active"), removing the ".Text".

Am I missing the point?

**Comment by skini82** [comment]
OK, I see.
So I was talking about the case of MonitoringDetails.aspx.resx
(full path: /CloudPanelWebSite_1.5/CloudPanelWebSite/CloudPanelWebSite/Monitoring/Manage/App_LocalResources/MonitoringDetails.aspx.resx)

![immagine](https://user-images.githubusercontent.com/5445572/44843382-82fc5d80-ac48-11e8-8d30-13c55d147333.png)
This is referenced in particular to file MonitoringDetails.aspx.cs.resx


The correct name string in my source code and even in crowdin is MonitoringServiceStatus_Active.Text.
As you can see in right part of the screenshot, after update the string was changed.

**Comment by skini82** [comment]
I made some investigations.. :D

I checked in older versions of the file. At first that variable name was "MonitoringServiceStatus_Active". Then it was changed in the source code ("MonitoringServiceStatus_Active.Text") and we updated the crowdin branch.
I think the trouble (or maybe it's something you wanted like that, so I have to act in consequences), it takes down the variable as it is in the TRUNK (it's first version, so it's still as "MonitoringServiceStatus_Active"), and so it takes the old name.
I expected to download the branch with correct variable names, than see if everything is right and only after tests merge the modification to the trunk (and so the trunk was indipendent from translations download of the branch).

I hope I explained well. Let me know!

**Comment by yavorysynka** [comment]
Thanks for the details! 

Yes, I also downloaded this file from our database and checked the string you described - this is what I can see inside source file MonitoringDetails.aspx.resx (branch path /CloudPanelWebSite_1.5/CloudPanelWebSite/CloudPanelWebSite/Monitoring/Manage/App_LocalResources/):
http://prntscr.com/kol8ig

The source value in the file is ATTIVO while on your screenshot I can see text ACTIVE; tried to find such source text in the project across all files but did not manage to do it:
https://crowdin.com/translate/official-cloudcontrolpanel15be/all/it-hu#q=ACTIVE

I feel like we're missing something here, are you sure we check the same very file right now?

Could you please download MonitoringDetails.aspx.cs.resx file from the Files tab and look for the string on your screenshot again? 

We can also switch to email instead, please feel free to reach me on olga@crowdin.com!

**Comment by skini82** [comment]
yes I think it's better by email :) see you there

**Comment by yavorysynka** [comment]
Thanks a lot for the explanation!

I checked the file in TRUNK folder too - old key is there

sure, looking forward!
