### ISSUE TITLE
Json files miss a new line at end of file

### ISSUE THREAD

**Issue by ghost** [crowdin/crowdin-cli#96]
Our standard code formatting requires newlines at end of file. There's no option to tell crowdin to do the same. This results in unnecessary white-space commits or reformatting when stored in a repository.

Please add a setting that controls new line at end of file.

**Comment by Yuliya-Crowdinteam** [comment]
Hi @mes3yd 

I will check this information with developers and will get back to you in the short run!

**Comment by yuliiaR** [comment]
@mes3yd We've improved the behavior so from now on you should see the newlines at end of file :)

Can you please check and confirm that everything works as expected?

**Comment by ghost** [comment]
@yuliiaR Sorry, but I can't check. Everything seems frozen in time at Oct 26: no new releases in deb repository, no new crowdin-cli.zip, no code updates in github repository.
I previously checked with one of our scripts that I now know rewrites the json so it looked to be OK at the time.

**Comment by v3ctorman** [comment]
@mes3yd Hi, you can add and delete translation to any string to trigger the activity in the project so updated translation files will be pushed to repo and this way you can check it without updating source files locally

**Comment by Andrulko** [comment]
Hey @mes3yd ! Sorry for the confusion, there was nothing to improve in CLI (it doesn't build files, it simply initiates requests to our API and saves downloaded files on your machine). Instead, we've improved our JSON parser, so now translations will be exported properly. No need to update CLI, please re-download translations and it should work 👍 

Will appreciate your confirmation

**Comment by ghost** [comment]
Hmm, giant reorganization with the files on our end doesn't help. I'll get back to you on Monday.

**Comment by v3ctorman** [comment]
@mes3yd sure, drop us a message any time early next week here or at support@crowdin.com
I believe there is no need to reorganize your files if you appeal to the new line issue. We've exported some translations from your project and seems they contain new line as expected. Let's talk about it later; and for now wish you a great weekend!

**Comment by Andrulko** [comment]
@mes3yd, can you please try download translations (`crowdin pull`) from the project again? Each downloaded file should contain a newline in the end of the file from now.

Happy Holidays :)

**Comment by ghost** [comment]
Took a bit ;) Yes, it's working reliably now. We even managed to add a new language. ;)
