### ISSUE TITLE
Translation file does not exist when it contains 'en' in the path

### ISSUE THREAD

**Issue by syastrov** [crowdin/crowdin-cli#97]
My crowdin.yml file looks like this:
```
"project_identifier": "..."
"api_key": "..."
"base_path": ""
"preserve_hierarchy": true
files: [
{
  "source": "/**/locale/en/LC_MESSAGES/*.po",
  "translation": "/**/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%",
  "ignore": ["venv/**/*", "node_modules/**/*"],
  "update_option": "update_as_unapproved",
}
]

```

I have these files:
```
./core/locale/sv/LC_MESSAGES/django.po
./core/locale/de/LC_MESSAGES/django.po
./core/locale/en/LC_MESSAGES/django.po
./payment/locale/sv/LC_MESSAGES/django.po
./payment/locale/de/LC_MESSAGES/django.po
./payment/locale/en/LC_MESSAGES/django.po
```

After running: `$ crowdin upload translations`, I get this output..
```
Uploading translation file '/core/locale/de/LC_MESSAGES/django.po' - uploaded
Translation file '/Users/sy/project/paymt/en/locale/de/LC_MESSAGES/django.po' does not exist
Uploading translation file '/core/locale/sv/LC_MESSAGES/django.po' - uploaded
Translation file '/Users/sy/project/paymt/en/locale/sv/LC_MESSAGES/django.po' does not exist
Uploading translation file '/core/locale/en/LC_MESSAGES/django.po' - uploaded
Translation file '/Users/sy/project/paymt/en/locale/en/LC_MESSAGES/django.po' does not exist

...
```

The end result is that the translations files beneath ./payment/ are not uploaded.

**Comment by yavorysynka** [comment]
Hello!

Could you please tell me your project name? I'll check everything in our database! 

I can see there is a /**paymt**/en/locale/sv/LC_MESSAGES/django.po folder in the path while locally translations seems to be stored in /**payment**/locale/en/LC_MESSAGES/django.po

Is there any chance it could be a reason?

**Comment by Andrulko** [comment]
Hmm, from what I see on the output, looks like "en" folder is stored before "locale" folder on your local machine.

I think that specifying `/Users/sy/project/paymt` for `base_path` might be helpful. Then configuration might be:

`  "source": "/locale/en/LC_MESSAGES/*.po",`
`  "translation": "/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%",`

**Comment by syastrov** [comment]
> Hello!
> 
> Could you please tell me your project name? I'll check everything in our database!
> 
nml-newmarkets

> I can see there is a /**paymt**/en/locale/sv/LC_MESSAGES/django.po folder in the path while locally translations seems to be stored in /**payment**/locale/en/LC_MESSAGES/django.po
> 
> Is there any chance it could be a reason?

There is no such folder as `paymt` in the path. It's something that crowdin-cli seems to make up itself.
I am not sure if it has anything to do with that I have English as both source / target language on Crowdin?

**Comment by syastrov** [comment]
OK, I just tried again and I think the problem might have been that I may have run `crowdin upload sources` with a different configuration and perhaps the source file for payment hadn't gotten uploaded to crowdin. After running `crowdin upload sources` and rerunning `crowdin upload translations`, it seems to work.
It would be nice if that situation was handled more gracefully.

**Comment by Gosteeva** [comment]
Hello :)

Just checked your project in our database and it seems `paymnt` folder is no longer there. That great to know that it worked smoothly with a different configuration!

Would you, please, tell me if you tried to specify `/Users/sy/project/paymt` for base_path as @Andrulko suggested? We would really appreciate the details to make sure this doesn't happen again!

**Comment by syastrov** [comment]
No, I did not specify anything other than "" as base_path.

**Comment by syastrov** [comment]
I don't have it, unfortunately. But I can see in "activity" of the crowdin project that some of the files are shown twice, which is strange -- not sure if that helps.

![screen shot 2018-12-17 at 10 09 47](https://user-images.githubusercontent.com/5605897/50077211-0c2da500-01e4-11e9-8f5e-ff0750586ca4.png)

**Comment by rohalskyy** [comment]
Sure, no problem. We'll try to find some good solution for such kind of situations

**Comment by Andrulko** [comment]
From what I've noticed, for some reason letters "disappear" when the system tries uploading translations. For example:
`Translation file '/Users/sy/project/paymt/en/locale/de/LC_MESSAGES/django.po' does not exist`

I've managed to reproduce it on Windows machine, with the same paths as yours. So for example `agent` folder became `agt`:
`Translation file 'C:\Users\Andriy\Downloads\test\agt\en\locale\fr\LC_MESSAGES\django.po' does not exist`

I had translations in this path on my machine:
`Translation file 'C:\Users\Andriy\Downloads\test\agent\locale\fr\LC_MESSAGES\django.po'`

My configuration was:

```
files: [
 {
  "source" : "/en.po",
  "translation" : "/%two_letters_code%.po"
 },
 {
  "source" : "/**/locale/en/LC_MESSAGES/*.po",
  "translation" : "/**/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%"
 }
]
```

Everything started to work normally after I've defined the full path to each file:

```
files: [
 {
  "source" : "/en.po",
  "translation" : "/%two_letters_code%.po"
 },
 {
  "source" : "/agent/locale/en/LC_MESSAGES/*.po",
  "translation" : "/agent/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%"
 },
 {
  "source" : "/core/locale/en/LC_MESSAGES/*.po",
  "translation" : "/core/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%"
 },
 {
  "source" : "/digest/locale/en/LC_MESSAGES/*.po",
  "translation" : "/digest/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%"
 },
 {
  "source" : "/payment/locale/en/LC_MESSAGES/*.po",
  "translation" : "/payment/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%"
 },
 {
  "source" : "/web_ui/locale/en/LC_MESSAGES/*.po",
  "translation" : "/web_ui/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%"
 }
]
```

@ihor-popyk Can you please check?

@syastrov We've noticed that you store identifiers in the `msgid` and sources/translations are stored in the `msgstr`. Right now, Crowdin displays identifiers as translatable texts (because according to the Gettext PO, `msgid` contains source texts).

Please add `"X-Crowdin-SourceKey: msgstr\n"` to the header of each PO file of yours, then update source files in Crowdin. Then texts from `msgstr` will be shown to your translators as English texts for translation. Hope it helps!

**Comment by rohalskyy** [comment]
Hello @syastrov!
I've got some good news for you! The export patter issue you've reported earlier has been already fixed.
Kindly install the latest CLI version which is attached in a ZIP archive and let me know about the results.
[crowdin-cli-2.0.25.zip](https://github.com/crowdin/crowdin-cli-2/files/2868798/crowdin-cli-2.0.25.zip)
