### ISSUE TITLE
Option to download pseudotranslations

### ISSUE THREAD

**Issue by capncodewash** [crowdin/crowdin-cli#98]
It would be really useful to be able to be able to download pseudotranslations through this CLI tool.

I think there is already support in the API:
https://support.crowdin.com/api/pseudo-export/
https://support.crowdin.com/api/pseudo-download/

Thanks!

Graeme

**Comment by Andrulko** [comment]
Graeme,

Thanks for raising an issue too 👍 Already shared the feedback, much appreciated!

**Comment by andrii-bodnar** [comment]
More about pseudolocalization: [KB article](https://support.crowdin.com/pseudolocalization/)

API - [Build Project Translation](https://support.crowdin.com/api/v2/#operation/api.projects.translations.builds.post) `TranslationCreateProjectPseudoBuildForm`

---

Command:

`crowdin download --pseudo`

Configuration (`crowdin.yml`):

```
"pseudo_localization": {
  "length_correction": "",
  "prefix": "",
  "suffix": "",
  "character_transformation": ""
}
```

---

`length_correction` - int range `-50` - `100`
`prefix` - string
`suffix` - string
`character_transformation` - enum "asian", "cyrillic", "european", "arabic"
